### PR TITLE
Replace IStateful with State design pattern

### PR DESCRIPTION
**Pull request by UselessToucan**
Current object state code(`IStateful<T>` implementation with some enum) can be replaced with the State design pattern.
For demonstration I rewrote `FrameStatisticsDisplay` and `PerformanceOverlay`. I know that incapsulation is messed up, but it will be fixed if required. Pay attention to the state management logic(`PerformanceOverlayState`, `FrameStatisticsDisplayState`).

### CODE REVIEW

**Comment by peppy** [comment]
What's the benefit of this? It's about three times the code.

**Comment by UselessToucan** [comment]
- It reduces the use of if-else statements. In other words, the
conditional complexity is reduced.
- It allows you to add new states and extend a state’s behavior easily.

**Comment by peppy** [comment]
What if-else? I can't see any.

Also how does it dedupe state changes?

**Comment by UselessToucan** [comment]
> What if-else? I can't see any.
I forgot to mention switch statement which is similar to if-else.

**Comment by peppy** [comment]
It's just replacing switch with methods. I'm not sure that counts as reducing complexity.

**Comment by smoogipoo** [comment]
I really don't see what's gained from this - I don't see removal of switches and ifs as a gain, and this has its own potential implications (like being able to set states to `null`).

The only argument for it to me is `it allows you to add new states and extend a state’s behavior easily` but this is kind-of iffy as it means you have to expose private implementation details of the object `public`ly so that e.g. `OsuGame` can change whatever it needs from the `FrameStatisticsDisplay`.

I would like to keep implementation details private, and expose `CreateFrameStatisticsDisplay()` along with a `SetState()` method inside `FrameStatisticsDisplay`, if such functionality is required.

**Pull request closed without merging**
