### PR TITLE
Add automated SpriteText invalidation tests

### PR DESCRIPTION
**Pull request by smoogipoo**
With a small layout validation framework, which will be used more in the future.

I didn't want to live on the dark side without knowing that invalidations are occurring as intended.

A single change to SpriteText - not handling parent colour invalidations, as their colour/presence has no effect on our layout. Presence changes are only applicable going children-to-parent, where it may affect, e.g. flow layout.

### CODE REVIEW

**Comment by ekrctb** [comment]
I'm against for doing tests in such way.
A problem is all those `false, true, false` etc. lists have to be manually checked but it is hard to do so. In general a test case should be self-explanation but I can't find why a particular bool is `true` or `false`.
Also,
> `Although it's probably not necessary for them to be invalidated unless a non-DrawSize/DrawScale component of DrawInfo is changed`.

Something like this is an evidence of checking against current implementation rather than testing implementation against intended semantics. While this kind of regression testing can be sometimes beneficial, I think there is a little or no benefit in this case.

**Comment by ekrctb** [comment]
@smoogipoo For example, "An extra `Invalidate` call should not make an observable difference" is a necessary property for invalidation.

**Comment by smoogipoo** [comment]
Again, I don't see how you can test the semantics of that beyond taking a screenshot and comparing - functionality which we don't have right now and which is a long ways off anyway. Otherwise you have no choice but to test the implementation.

**Comment by ekrctb** [comment]
Instead of taking a graphical screenshot, getting various properties like `DrawSize` should works.

**Comment by smoogipoo** [comment]
So you'd be fine with instead exposing `ScreenSpaceCharacters` and `ShadowOffset` and testing against their properties?

There's another problem with your proposed change as well. I want to reduce the number of invalidations happening, e.g. the `Colour` invalidation that I removed in this PR. Since this all has an impact on performance. How would you tackle that?

**Comment by ekrctb** [comment]
For first part of your question, having internal `ScreenSpaceCharacters` seems reasonable for me.

**Comment by ekrctb** [comment]
For the second part, I think if a change is solely to make less invalidation, a specific test for this case is not a problem.

**Comment by peppy** [comment]
Is there a reason for closing this? I was pretty okay with it being merged (there's no downside to having more tests, even if some are redundant).

**Pull request closed without merging**
