### PR TITLE
Fix hard crash on MIDI initialisation failure

### PR DESCRIPTION
**Pull request by peppy**
- Closes https://github.com/ppy/osu/issues/9008

### CODE REVIEW

**Comment by iiSaLMaN** [comment]
While this fixes the linked issue specifically, it'll still potentially fail if a MIDI device got plugged in post-initialization while another program looking for MIDIs "opens" the device before the framework. I guess the only solution here is to move the try-catch to inside `refreshDevices`.

**Comment by peppy** [comment]
Have you reproduced this scenario? Do you have a specific application which has this kind of "looking for MIDIs" behaviour?

**Comment by iiSaLMaN** [comment]
Not really, just envisioned as a potential scenario. Looks good now.

**Comment by Stedoss** [comment]
Putting the whole method in a try-catch means that MIDI devices that are lower in the input list will get ignored I think; something like this might be more appropriate?
```csharp
foreach (IMidiPortDetails input in inputs)
{
    if (openedDevices.All(x => x.Key != input.Id))
    {
        IMidiInput newInput;
        try
        {
            newInput = MidiAccessManager.Default.OpenInputAsync(input.Id).Result; //This is the line that is throwing the exception.
        }
        catch
        {
            Logger.Log($"Unable to open MIDI input stream on device {input.Name} (is another application using this MIDI device?)");
            continue;
        }
        newInput.MessageReceived += onMidiMessageReceived;
        openedDevices[input.Id] = newInput;

        Logger.Log($"Connected MIDI device: {newInput.Details.Name}");
    }
}
```

This also allows for the MIDI device to be detected once the application that is using it stops (from my testing).

**Comment by peppy** [comment]
That just gets complicated and is out of scope in my opinion. You would be getting that log output *every* 500ms. Restarting osu! after closing other apps is probably what we want for now.

**Pull request merged**
