### PR TITLE
Fixing window with no window size

### PR DESCRIPTION
**Pull request by Memorix101**
Quick fix for osu framework
Fixing creating a window with no resolution.

### CODE REVIEW

**Comment by peppy** [comment]
Did you figure why this isn't being set via the draw hierarchy? On windows at least, it works without this extra default code (the default comes from OsuConfigManager).

**Comment by Memorix101** [comment]
The default code is for framework only. Because without that happens ...

at start
screenshot 305

after resizing by mouse
screenshot 306

**Comment by peppy** [comment]
Ah yep, fair point. Want to merge upstream master into your branch to bring it up-to-date?

**Comment by Memorix101** [comment]
ah, sure :)

**Pull request merged**
