### PR TITLE
Fix SliderBar's Current implementation

### LINKED ISSUE #3088: SliderBar doesn't use BindableWithCurrent
Not correctly holding a reference.

### PR DESCRIPTION
**Pull request by peppy**
Closes #3088.

- [x] Depends on https://github.com/ppy/osu-framework/pull/3089

### CODE REVIEW

**Comment by peppy** [comment]
Tested against osu!, can confirm fixes the related issue.

**Comment by smoogipoo** [comment]
Shouldn't there be a framework-side test for this?

**Comment by peppy** [comment]
The behaviour is tested in `AggregateBindableTest` already, so I thought it was pretty redundant to add one specifically for this.

**Comment by smoogipoo** [comment]
I meant a test for SliderBar, but alright.

**Pull request merged**
