### PR TITLE
Implement OnCloseRequested for SDL

### PR DESCRIPTION
**Pull request by swoolcock**
Implements the missing `OnExitRequested` flow.

### CODE REVIEW

**Comment by peppy** [comment]
This doesn't catch alt-f4 on windows, while our old logic did.

**Comment by swoolcock** [comment]
Ah, I see SDL does not general `SDL_QUIT` events for Alt+F4/Cmd+Q etc.  Will look into it.

**Comment by swoolcock** [comment]
What is the expected functionality of pressing Alt+F4?  Instant quit/window dismissal?

**Comment by peppy** [comment]
the ability to intercept as you've implemented. we need to save changes etc.

**Comment by swoolcock** [comment]
`Window.Close` => `Sdl2WindowBackend.Close` was performing a forceful close rather than requesting one as per osuTK.

Normally Alt+F4 and Cmd+Q both send an `SDL_QUIT` message and safely handle the request flow.  However, recent changes in `WindowGameHost` catch Alt+F4 as a `PlatformAction` and redirect it to `Window.Close`.  On osuTK this was not a problem due to `Window.Close` following the request flow.  I have updated the SDL backend to work in the same way.

**Comment by swoolcock** [comment]
Setting the `SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4` hint prevents SDL from redirecting Alt+F4 to `SDL_QUIT`, solving the problem of a double `OnExitRequested` being called on Windows.

Given we only define the Alt+F4 `PlatformAction.Exit` in `WindowsGameHost`, there is currently no need to use a similar hint or workaround on other desktop platforms.

Tested in Windows 10.

**Comment by peppy** [comment]
Added test coverage. Looks to work as expected.

**Review by peppy — DISMISSED** [review]

**Review by peppy — APPROVED** [review]

**Review by bdach — APPROVED** [review]

**Pull request merged**
