### PR TITLE
Fix libbass_fx load errors during tests on linux

### PR DESCRIPTION
**Pull request by smoogipoo**
Anything that touched bass would fail with:
```
Reason: Test host process crashed : /usr/share/dotnet/dotnet: symbol lookup error: /home/smgi/Repos/osu/osu.Game.Rulesets.Mania.Tests/bin/Debug/netcoreapp3.1/runtimes/linux-x64/native/libbass_fx.so: undefined symbol: BASS_GetVersion
```
This also affected nunit tests since they use `HeadlessGameHost` (not `LinuxGameHost`).

### CODE REVIEW

**Comment by peppy** [comment]
Does this mean no tests have ever been run on linux by anyone?

**Comment by smoogipoo** [comment]
No unit tests, at least. Visual tests work fine.

**Comment by peppy** [comment]
Concerning, considering how many linux contributors we have..

**Comment by bdach** [comment]
Can't say I've ran CLI tests on my Linux install anytime recently either. I hardly ever use it anymore at this point.

**Comment by peppy** [comment]
It should also occur from nUnit runs inside of rider / vs though, right?

**Comment by smoogipoo** [comment]
Yeah, in rider it'll show up as "test not run" and give a very unhelpful log file.

**Pull request merged**
