### PR TITLE
Implement remaining parts for Veldrid support

### PR DESCRIPTION
**Pull request by smoogipoo**
This is a WIP branch that supersedes https://github.com/ppy/osu-framework/pull/5596 https://github.com/ppy/osu-framework/pull/5597 https://github.com/ppy/osu-framework/pull/5598 https://github.com/ppy/osu-framework/pull/5599

### CODE REVIEW

**Comment by frenzibyte** [comment]
Since this supersedes #5599 as well, I've ported a change from that PR which fixes framebuffers being rendered upside down in Veldrid. I've also included support for circular progress/blobs as well since it's in scope of this PR. And finally one little change that I didn't want to open another PR for.

This is working pretty well on Metal for me according to the visual tests we have, but upon testing [osu!](https://github.com/ppy/osu/compare/master...frenzibyte:osu:veldrid?expand=1), there are actually some rendering issues:

CleanShot 2023-02-08 at 01 29 19

CleanShot 2023-02-08 at 01 29 52

But not sure if we want those resolved immediately or in follow-up PRs. Would choose the latter to keep this one from getting more complicated than it is already, but that depends on the purpose of this PR.

**Comment by adiantek** [comment]
Hi,

I tried to test it on Surface Pro X (Windows arm64), but I stuck with compiling it xd
image
The same problem had [Github Ci](https://github.com/ppy/osu-framework/pull/5647/commits/272b7a0962eca7942847c9d2fac847d7d6ab79b7#file-osu-framework-utils-convexpolygonclipper-cs-L42):


From branch master (578394629e9b265ec34d406e27f2a92145f5cd15 & https://github.com/ppy/osu/commit/28897b6e18ab08159407a77e3d3b36a0d6e6db7f) I was able to compile it to arm64 and it runs on SPX:

Screenshot 2023-02-09 140349

Some dependencies are in PE x86 like Newtonsoft.Json.dll or OpenTabletDriver (maybe sth wrong with NuGet configuration), but Windows arm64 supports mixed mode (ARM64EC), so it's not a problem if sth stays in x86 (the most important is rendering and there is a huge difference between full osu in x86 and osu-arm64;osu-framework-arm64;osuTK-x86).

**Comment by smoogipoo** [comment]
Running TestSceneVideo under Vulkan:
```
Unhandled exception. Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Vulkan.VulkanNative.vkCreateImageView(Vulkan.VkDevice, Vulkan.VkImageViewCreateInfo ByRef, Vulkan.VkAllocationCallbacks*, Vulkan.VkImageView ByRef)
   at Veldrid.Vk.VkTextureView..ctor(Veldrid.Vk.VkGraphicsDevice, Veldrid.TextureViewDescription ByRef)
   at Veldrid.Vk.VkResourceFactory.CreateTextureViewCore(Veldrid.TextureViewDescription ByRef)
   at Veldrid.ResourceFactory.CreateTextureView(Veldrid.TextureViewDescription ByRef)
   at Veldrid.ResourceFactory.CreateTextureView(Veldrid.TextureViewDescription)
   at Veldrid.ResourceFactory.CreateTextureView(Veldrid.Texture)
   at Veldrid.Texture.CreateFullTextureView(Veldrid.GraphicsDevice)
   at Veldrid.Texture.GetFullTextureView(Veldrid.GraphicsDevice)
   at Veldrid.Util.GetTextureView(Veldrid.GraphicsDevice, Veldrid.BindableResource)
   at Veldrid.Vk.VkResourceSet..ctor(Veldrid.Vk.VkGraphicsDevice, Veldrid.ResourceSetDescription ByRef)
   at Veldrid.Vk.VkResourceFactory.CreateResourceSet(Veldrid.ResourceSetDescription ByRef)
   at Veldrid.ResourceFactory.CreateResourceSet(Veldrid.ResourceSetDescription)
   at osu.Framework.Graphics.Veldrid.Textures.VeldridTextureResource.GetResourceSet(osu.Framework.Graphics.Veldrid.VeldridRenderer, Veldrid.ResourceLayout)
   at osu.Framework.Graphics.Veldrid.VeldridRenderer.DrawVertices(Veldrid.PrimitiveTopology, Int32, Int32)
   at osu.Framework.Graphics.Veldrid.Buffers.VeldridVertexBuffer`1[[osu.Framework.Graphics.Rendering.Vertices.TexturedVertex2D, osu.Framework, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].DrawRange(Int32, Int32)
   at osu.Framework.Graphics.Veldrid.Batches.VeldridVertexBatch`1[[osu.Framework.Graphics.Rendering.Vertices.TexturedVertex2D, osu.Framework, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Draw()
   at osu.Framework.Graphics.Rendering.Renderer.FlushCurrentBatch(System.Nullable`1<osu.Framework.Graphics.Rendering.FlushBatchSource>)
   at osu.Framework.Graphics.Rendering.Renderer.setShader(osu.Framework.Graphics.Shaders.IShader)
   at osu.Framework.Graphics.Rendering.Renderer.BindShader(osu.Framework.Graphics.Shaders.IShader)
   at osu.Framework.Graphics.Veldrid.Shaders.VeldridShader.Bind()
   at osu.Framework.Graphics.Sprites.SpriteText+SpriteTextDrawNode.Draw(osu.Framework.Graphics.Rendering.IRenderer)
```

**Comment by smoogipoo** [comment]
Effects are broken under D3D:
image

**Comment by smoogipoo** [comment]
Superseded by https://github.com/ppy/osu-framework/pull/5655 and https://github.com/ppy/osu-framework/pull/5661

**Pull request closed without merging**
