### PR TITLE
Implement binary bitmap font format

### LINKED ISSUE #1858: Switch bitmap fonts to binary format
Will avoid hundreds of megabytes of string allocations during startup (and greatly reduce cpu overhead).

We can likely use this library: https://www.nuget.org/packages/SharpFNT/

Can use [this utility](https://www.npmjs.com/package/convert-bmfont) to convert our existing ascii formatted `.fnt` files to binary.

### PR DESCRIPTION
**Pull request by FreezyLemon**
Do not merge (yet) - the new logic breaks compatibility with the current format.

This uses SharpFNT and its binary format instead of the current textual format (Cyotek.Drawing.BitmapFont only supports XML and textual font files).

The conversion to this binary font format was done using SharpFNT itself:

```c#
var font = BitmapFont.FromFile(file.FullName);

// there's a bug with empty Charset that crashes on Save()
if (font.Info.Charset == string.Empty)
{
    font.Info.Charset = "ANSI";
}

font.Save(Path.GetFileNameWithoutExtension(file.Name) + ".bin", FormatHint.Binary);
```

[Benchmark for font loading](https://gist.github.com/FreezyLemon/5d1bf2b4eebfa9197ae610a58ef589e8)

- Closes #1858 

---

Change font files to use a binary format for better performance.

### CODE REVIEW

**Comment by FreezyLemon** [comment]
Yes, this PR is complete.

I planned on doing some benchmarks with osu and maybe find a way to measure the reduction in string allocations, but if you're fine without that, this is ready to merge.

**Comment by peppy** [comment]
Looks good!

**Comment by ToddBertaOldham** [comment]
Hi, I'm the developer of SharpFNT.  Sorry for commenting on a closed thread but I saw that you encountered a bug when writing files. I’ll have a fix for that soon and update the NuGet package. I apologize for the issue but if you happen to encounter any more please [report it](https://github.com/ToddBertaOldham/SharpFNT/issues) and I’ll get it fixed. Also, I saw that there were some concerns about the binary format. I simply followed the specification on the [website for BMFont](http://www.angelcode.com/products/bmfont/doc/file_format.html#bin) which is the original tool for creating fnt files.  That conversion tool you mentioned is likely outdated. The magic numbers just help identify what kind of file it is. Thanks for using my library!

**Comment by peppy** [comment]
@ToddBertaOldham thanks for the clarification!

**Comment by ToddBertaOldham** [comment]
I just posted an [update](https://www.nuget.org/packages/SharpFNT/1.0.1) that should fix some issues and inconsistencies with null strings. Your workaround works about the same so there's no rush to update but I figured I'd mention it.

**Pull request merged**
