### PR TITLE
Add Interpolation.ValueAt for strings

### PR DESCRIPTION
**Pull request by iiSaLMaN**
Simple implementation to allow text transforms.

### CODE REVIEW

**Comment by peppy** [comment]
I still think this feels a bit weird. Transforms are generally performing an action over time, so it is not immediately obvious what one would do with strings (one could assume it would gradually add characters over the specified duration, which would actually be a more understandable implementation).

@smoogipoo what are your thoughts on this? i know that it does help with reversing gameplay because transforms are actually rewound, while using something like `OnComplete` (see `IntroTriangles` for an example https://github.com/ppy/osu/blob/8917f7cc95b12216eb15d7f80a6309bdf27831b9/osu.Game/Screens/Menu/IntroTriangles.cs#L231) is not, but kinda makes more sense?

**Comment by smoogipoo** [comment]
Maybe this is a case where we want implementations local to osu! itself since the functionality is pretty arbitrary. I wouldn't be against removing this from the framework altogether.

**Comment by swoolcock** [comment]
What's the use case for this?  I don't really see any point in having an interpolation function that doesn't do any kind of easing, and is essentially just a delayed property change.  If I were to interpolate between two strings, I would expect to be doing some kind of time-based transformation such that you can see the words changing letter by letter.

Something vaguely along the lines of:

```
Text = "hello";
...
TransformTo(nameof(Text), "world");
...
"hello"
"helld"
"horld"
"world"
```

**Comment by peppy** [comment]
Yeah, the transformation between strings is a case i wasn't considering, and gets hard to implement in a standardised way. I'm all for dropping this function out of framework.

**Comment by smoogipoo** [comment]
It looks like only osu! implements the text transforms, closing this PR as discussed.

**Pull request closed without merging**
