### PR TITLE
Fix Quad.ConservativeArea being inaccurate in some cases

### PR DESCRIPTION
**Pull request by smoogipoo**
Fixes pixel count being wholly incorrect on the transition into songselect (sheared buffered wedge).

Uses the same calculations as in the FTB pass. I've left the `Area` property as a ground-truth for unit testing.

Performance:

```diff
  |           Method |       Mean |     Error |    StdDev |
  |----------------- |-----------:|----------:|----------:|
- |             Area | 162.900 ns | 1.4873 ns | 1.3912 ns |
- | ConservativeArea |  60.541 ns | 0.8097 ns | 0.7178 ns |
+ |             Area |   4.551 ns | 0.0609 ns | 0.0540 ns |
```

Breaking changes:

# vNext

## `Quad.ConservativeArea` has been removed

It was inaccurate for certain `Quad`s. Use `Area` as a replacement.

### CODE REVIEW

**Comment by peppy** [comment]
Do we know the Area is correct? If not, might be good to pepper in a few tests against known values.

**Comment by smoogipoo** [comment]
I've actually replaced the old `Area` function with the new calculation, since I found it was incorrect in the case of self-intersecting quads, whereas the new calculation gives a decent interpretation.

**Comment by Tom94** [comment]
Woah, the speed-up over the 2-triangles method is crazy! Any idea where that kind of difference comes from?

Also, super nice that you managed to get rid of `ConservativeArea`

**Comment by smoogipoo** [comment]
Likely just not instantiating structs + copying vertices during that construction.

**Pull request merged**
