### PR TITLE
Add SDL support to SampleGame

### PR DESCRIPTION
**Pull request by peppy**
Caught me off-guard that this isn't a thing.

### CODE REVIEW

**Comment by bdach** [comment]
Think it's worth doing the same for the flappy template while we're at it?

**Comment by smoogipoo** [comment]
I really don't think we should be promoting this argument so far as to add it to the templates/samples... The eventual goal _is_ to remove osuTK, right?

**Comment by peppy** [comment]
Yeah, would be against adding it to the template. But samplegame is kinda required because i use it for benchmarking and almost got numbers incorrect because it wasn't being applied.

**Comment by bdach** [comment]
Oh, the empty template and sample game are two disparate things. My bad, I just associated template with "spinning box" without realising both have it.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
