### PR TITLE
Make DrawQuad/DrawTriangle generic to reduce construction overhead

### PR DESCRIPTION
**Pull request by smoogipoo**
For cases where we're doing, e.g:

```
Texture.DrawQuad(..., v => buffer.Add(new CustomVertex { ... });
```

we can now instead do:

```
Texture.DrawQuad<CustomVertex>(..., v =>
{
    { /* set custom vertex properties here */ }
    buffer.Add(v);
}
```

### CODE REVIEW

**Comment by peppy** [comment]
Update: no change (0.25ms / 4000fps)
Draw: +0.23ms (0.58 -> 0.71ms or 1700 -> 1400fps)

Tested over 8 runs (main menu, no song playing, menu open)

image

Probably worth profiling further, that's quite a large difference.

**Comment by smoogipoo** [comment]
Blocked. @peppy when you next have time I'm really interested to see if this improves performance vs your last run. It's kinda crazy to me that it's not inlining these properties. Obviously this is not the final solution but I'm super intrigued now.

**Comment by peppy** [comment]
No difference from first benchmarks.

**Comment by smoogipoo** [comment]
@peppy if you can test one more time, that'd be stellar. Last attempt for me, otherwise we're just gonna have to live with this.

**Comment by smoogipoo** [comment]
Closing due to aforementioned performance issues. Maybe in the future.

**Pull request closed without merging**
