### PR TITLE
Inline out variables

### PR DESCRIPTION
**Pull request by UselessToucan**
We might want to do it in order to reduce LOC number a little.

### CODE REVIEW

**Comment by peppy** [comment]
Agree with inline out variables, disagree with `var`.

**Comment by smoogipoo** [comment]
Idk. I agree with the vars. What's your reason against them?

**Comment by smoogipoo** [comment]
I discussed this with @peppy. Let's change all these cases back to using strong types.

**Comment by peppy** [comment]
For transparency, my main argument is that in most cases the types are only a few characters longer than `var`, and give good extra information in some cases which cannot be easily obtained without intellisense (ie. when viewing diffs on github).

@smoogipoo's argument is that some cases are just return values where type can be inferred, and that IDE support isn't great for autocompleting the strong type.

I think we both agree that primitive types should never be replaced by var, at which point I think there's more value in just making a general rule to always use strong types in this specific case.

I'm still all for `var x = new y()`, where the type would othrwise be duplicated on the same line.

**Pull request merged**
