### PR TITLE
Added StorageResourceStore

### PR DESCRIPTION
**Pull request by tacchinotacchi**
This class is for loading resources off of a storage. For example, loading texture and sounds from skins.

### CODE REVIEW

**Comment by peppy** [comment]
This probably isn't so useful on its own (would need to at very least be namespaced to a specific location).

Is this a dependency for another PR you have pending? If so, please link that for context.

**Comment by tacchinotacchi** [comment]
It is a dependency for my SkinManager, which I did not deem worthy of a PR yet.

**Comment by peppy** [comment]
Honestly i think a better usage pattern for this would be

`storage.GetResourceStore(path)`

forcing the namespacing of the path (ie. it can't just be top-level storage)

**Comment by tacchinotacchi** [comment]
I agree, but with the generalized ArchiveManager this will not be useful for SkinManager I think ( may be useful in the future? )

**Comment by peppy** [comment]
Closing for now as per discord discussion. Skins will not need this as they will not be folder based.

**Pull request closed without merging**
