### PR TITLE
Fix SafeAreaContainer padding not updating with transforms

### PR DESCRIPTION
**Pull request by swoolcock**
Invalidates the padding cache on `DrawInfo` rather than `Parent`.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Is this to cover the case where the parent's size changes?

**Comment by swoolcock** [comment]
It's to cover the case where the `SafeAreaContainer` moves or resizes such that its children need to be padded by a different amount.

If you'd like, I'll take another look tonight to verify that this is correct.

**Comment by swoolcock** [comment]
@smoogipoo so invalidate the padding when *any* of `DrawInfo`, `DrawSize`, or `MiscGeometry` are present in `invalidation`?

**Comment by smoogipoo** [comment]
I believe so, as it is it may not work when the size of the container itself changes.

**Pull request merged**
