### PR TITLE
Add simple shading options

### PR DESCRIPTION
**Pull request by Tom94**
This allows us to simplify the shaders and blending used on select Drawables to optimize performance. Making the background and the osu! logo (and ripple) simpler gives me a 30% speedup when running at fullscreen. A much bigger win on my surface. (see https://github.com/ppy/osu/pull/124 )

### CODE REVIEW

**Comment by peppy** [comment]
This is a two-edged sword because it could split up draw batches and increase gl calls for the shader switching. May be worth adding a comment mentioning this in the UseSimpleShader xmldoc.

I feel like in cases we'd want to use this, it'd be nice to be able to set it at a container level (everything nested in said container uses simple shader).

If it's seen as enough of a win, it may also be worthwhile considering making it default for sprites (or everything?) and automatically switch to the complex shader when anything is applied that requires it. i'd much rather this to a manual toggle left up to the developer.

**Comment by Tom94** [comment]
The reason I didn't make it the default, is that it'd need to propagate down from parents. (If some parent container does masking, all children need to use the non-simple shader.) I deemed that too complex to add for a simple optimization tweak that we will only ever apply to a handful of sprites.

The gain is significant, but only for those very few sprites that are big and have no masking or effects. This is also the reason why splitting draw batches is not really a concern. only a handful of extra draw calls and shader switches.

**Comment by peppy** [comment]
My point is that if all gameplay elements are making no use of masking (or only simple scissor masking) or glow, it may end up being a potentially large performance gain to bypass the complex shader.

**Comment by Tom94** [comment]
Simple scissor masking won't do if we want to support rotated masking. Also Hitcircles already mask away the inner triangles. I don't think we want to think this far ahead. Lastly, the amount of fillrate occupied by gameplay is still relatively low compared to the background image unless you are playing centipede or some other crazy stuff.

**Comment by peppy** [comment]
An example would be when not using the default skin, where everything is sprite based, and approach circles are HUGE mostly-transparent sprites. The fill added in such a case would potentially be quite high.

Another example would be legacy storyboards, where we don't need to support any advanced features and need to optimise for fill rate.

**Pull request merged**
