### PR TITLE
Allow framework types to cache structs as dependencies

### PR DESCRIPTION
**Pull request by smoogipoo**
#### DependencyContainer
```diff
+ internal void CacheValue<T>(T instance)
+ internal void CacheValueAs<T>(T instance)
```

#### ReadOnlyDependencyContainerExtensions
```diff
+ internal static T GetValue<T>(this IReadOnlyDependencyContainer container)
```

Functionality is also provided through `[Cached]`, with the same soft limitation that only framework types can define this on structs. If another assembly tries to use `[Cached]` on structs, an `ArgumentException` will be thrown (as it already was).

Replaces the eventual implementation in https://github.com/peppy/osu-framework/tree/cancellation-drawables .

### CODE REVIEW

**Comment by peppy** [comment]
You say "soft" limitation in the PR, but it looks pretty hard to me (as it should be).

**Comment by peppy** [comment]
Is it intended that this work with nullable types? It doesn't seem to be at the moment.

**Comment by smoogipoo** [comment]
Haven't tested nullable types. Should get that working before this is merged tho

**Comment by peppy** [comment]
Seems to work as expected for cancellation tokens 👍

**Pull request merged**
