### PR TITLE
Fix double clicking on dropdown header not changing menu state

### PR DESCRIPTION
**Pull request by smoogipoo**
Prereqs:
- [x] https://github.com/ppy/osu-framework/pull/6345

Fixes https://github.com/ppy/osu-framework/issues/6342

### CODE REVIEW

**Comment by smoogipoo** [comment]
Given there's been no reviews on this, I've taken the liberty of re-basing it upon https://github.com/ppy/osu-framework/pull/6345 because I believe it'll be easier/more agreeable to review alongside that fix.

**Comment by peppy** [comment]
@smoogipoo would be good to have a test for this one to better understand what it's fixing. did you want to add one or shall i?

**Comment by smoogipoo** [comment]
I'll add one.

**Comment by peppy** [comment]
This does what it says, but what are your thoughts on also making the case where there's a search header also close on a second click? Would probably be a separate effort, but I feel it may be more natural to have it close.

**Review by peppy — APPROVED** [review]

**Pull request merged**
