### PR TITLE
 Introduce InputManager.IdleTime property 

### PR DESCRIPTION
**Pull request by UselessToucan**
Required for implementing [this](https://github.com/ppy/osu/issues/3406) proposal

### CODE REVIEW

**Comment by peppy** [comment]
- You can't make framework changes without xmldoc on all public and protected properties.
- Is there a reason this can't be local to its usage? ie. in the menu implementation's `OnMove`/`OnMouseDown` etc. (ie. do you see any benefit in doing it at an `InputManager` level?)

**Comment by UselessToucan** [comment]
As far as I understand, in the main menu context, Idle means the following:
1. There are no mouse movements.
2. There are no interactions with the button system.
3. There are no interactions with the toolbar.
4. There are no interactions with overlays.

In order to track idle time locally, I will have to add UI event handlers to all of this things. It turns out that there are too many places for tracking idle time locally.

**Comment by peppy** [comment]
Still not sure `InputManager` (or the framework) is the correct place for this. Why not do it at an `OsuGame` level in that case? Possibly as an IdleTracker component.

**Comment by UselessToucan** [comment]
Implemented at an `OsuGame` level
see [#3415](https://github.com/ppy/osu/pull/3415)

**Pull request closed without merging**
