### PR TITLE
Make dropdown tabbable

### PR DESCRIPTION
**Pull request by nyquillerium**
Resolves https://github.com/ppy/osu-framework/issues/2508

### CODE REVIEW

**Comment by peppy** [comment]
Clicking dropdown breaks tabbing

**Comment by nyquillerium** [comment]
Do you mean losing focus? I must have misunderstood when we were discussing the behavior, because I was under the impression we were going to leave that be for now.

Not a big deal though, I was adding that behavior for maintaining tabbed states for checkboxes anyway. Can merge that into this.

**Comment by peppy** [comment]
Is this abandoned?

**Comment by nyquillerium** [comment]
The last thing we discussed with regards to this was your proposal for changing `TabbaleContainer`s such that they only exist as a `TabbableContentContainer`, and that individual components should not be `TabbableContainer`s. That would require rewriting `TextBox` as well as `TabbableContainer`, so this has been pending https://github.com/ppy/osu-framework/issues/2550

**Comment by nyquillerium** [comment]
Closing this and re-writing when I finish https://github.com/ppy/osu-framework/issues/2550. I'll be moving these tests into the new PR as well.

**Pull request closed without merging**
