### PR TITLE
Various improvements to textbox input

### PR DESCRIPTION
**Pull request by smoogipoo**
* Fixes TextBoxes blocking all key input.
  * Not entirely sure why this was here, if any case comes up where this breaks we'll analyse it/comment it appropriately.
* Removes unnecessary returns which are already handled in `OnAction`.
* Fixes `PlatformActions` not being handled before keys.
  * Fixes not being able to Cmd+Left/Cmd+Right in the search box in SongSelect.
* Fixes readonly textboxes being able to be tabbed to. Browsers do the same thing.

### CODE REVIEW

**Comment by peppy** [comment]
Breaks song select left/right arrows.

**Comment by peppy** [comment]
Correction: breaks left/right arrow keys game-wide (slider bars don't work, for instance). I think this is related to the priority change.

**Comment by UselessToucan** [comment]
I think you should merge #1365 and #1362 before working on this PR because it will allow you to see how everything fits together.

**Comment by peppy** [comment]
We generally merge required fixes before breaking changes.

**Comment by smoogipoo** [comment]
The reason why I did this is to fix the behaviour in those PRs prior to merging them. They're my target but there are a few interactions and quirks with input handling before those can be merged.

Focus is one last thing remaining before those two can be merged.

**Pull request merged**
