### PR TITLE
Add support for glow around masked regions.

### PR DESCRIPTION
**Pull request by Tom94**
Todo for the future: We need to make it easier to share static shaders among multiple modules. I am not happy with the way ContainerDrawNode just grabs the shader from SpriteDrawNode.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
LGTM but it's bigger than I feel comfortable merging alone. Tested this and it was fine. Something to be aware of is that the glow is masked in its parent container and we'll have to start using padding to accomodate.

**Comment by peppy** [comment]
- GlowRadius and GlowColour need invalidation property logic.
- Glow can be used as a fill. Maybe a better method of making container backgrounds than using an implicit Box?

**Comment by Tom94** [comment]
> GlowRadius and GlowColour need invalidation property logic:
Oh, I see, there is some invalidation logic for `DrawNodes`. For some reason I still assumed they were created anew every frame.

> Glow can be used as a fill. Maybe a better method of making container backgrounds than using an implicit Box?
Glow works this way because I could re-use the existing unified shader like this without making it more complicated. If it's _really_ necessary to not put a background below glowing drawables (only cases I could think of are if the object is transparent) I'll have to make some modifications to shaders and potentially switch between them upon glow rendering. What do you think?

**Comment by peppy** [comment]
not sure which is more correct, but let's leave it until it becomes an issue.

**Comment by Tom94** [comment]
Also, I am not sure if this should be used to get container background instead of an implicit box. It currently comes with a higher computational overhead, because the ScreenSpaceDrawQuad of the glow itself is not cached (re-computed every frame). I felt like this was okay given the relative rarity of glow drawables, but we may want to change that in the future.

**Pull request merged**
