### PR TITLE
Allow classes to be generic arguments for ButtonInput

### PR DESCRIPTION
**Pull request by iiSaLMaN**
- Dependency for multi-touch button input which inherits `ButtonInput<PositionalPointer>` as `PositionalPointer` is a class.

### CODE REVIEW

**Comment by smoogipoo** [comment]
What is `PositionalPointer` and why is it a class?

**Comment by iiSaLMaN** [comment]
> What is `PositionalPointer`

`PositionalPointer` is simply a class that contains a `Vector2` position and `MouseButton` pointer source.

> why is it a class?

Because using `struct` will not allow me to modify its position.

**Comment by smoogipoo** [comment]
That sounds super unsafe.

**Comment by smoogipoo** [comment]
Closing as the desired usage pattern is invalid.

**Pull request closed without merging**
