### PR TITLE
Reduce locks on TextureStore

### PR DESCRIPTION
**Pull request by huoyaoyuan**
Found these locks blocking when investigating ppy/osu#8160 .

Replacing single-consumer `lock` statements with `ReaderWriterLockSlim` and `ConcurrentDictionary`.

This PR does not solve the issue, but helps. It _enables concurrent loading_ for online texture store. Before the changes, every network request is under a lock and blocking each other.

Performance improvement should be observed in Social Browser.

### CODE REVIEW

**Comment by peppy** [comment]
Throws exceptions when running osu-side tests:

```csharp
osu.Game.Tests.Visual.Background.TestSceneUserDimBackgrounds.StoryboardBackgroundVisibilityTest

TearDown : System.AggregateException : One or more errors occurred. (The read lock is being released without being held.)
  ----> System.Threading.SynchronizationLockException : The read lock is being released without being held.
Data:
  unhandled: unhandled

--TearDown
   at osu.Framework.Testing.TestScene.checkForErrors() in /Users/dean/Projects/osu-framework/osu.Framework/Testing/TestScene.cs:line 140
   at osu.Framework.Testing.TestScene.RunTests() in /Users/dean/Projects/osu-framework/osu.Framework/Testing/TestScene.cs:line 130
--SynchronizationLockException
   at System.Threading.ReaderWriterLockSlim.ExitReadLock()
   at osu.Framework.IO.Stores.ResourceStore`1.Get(String name) in /Users/dean/Projects/osu-framework/osu.Framework/IO/Stores/ResourceStore.cs:line 165
   at osu.Framework.IO.Stores.ResourceStore`1.Get(String name) in /Users/dean/Projects/osu-framework/osu.Framework/IO/Stores/ResourceStore.cs:line 157
   at osu.Framework.Graphics.Textures.TextureStore.getTexture(String name) in /Users/dean/Projects/osu-framework/osu.Framework/Graphics/Textures/TextureStore.cs:line 69
```

**Comment by huoyaoyuan** [comment]
I'm always failing with *another* exception:
```
System.IO.IOException : The process cannot access the file 'D:\Code\osu\osu.Game.Tests\bin\Debug\netcoreapp3.1\headless-TestSceneUserDimBackgrounds-f4175f68-c7a6-42ec-ae92-72138b0840da\cache\fonts\57302b981c4deb011671c82fe789d7a9#dd9f54baf84b45edcd4cbf944cb107b3#1018#612'
because it is being used by another process.

--TearDown
    TestScene.checkForErrors() line 139
    TestScene.RunTests() line 128
    --IOException
    FileSystem.DeleteFile(String fullPath)
    File.Delete(String path)
    NativeStorage.Delete(String path) line 41
    RawCachingGlyphStore.createCachedPageInfo(Int32 page) line 79
    RawCachingGlyphStore.LoadCharacter(Character character) line 40
    GlyphStore.Get(String name) line 119
    ResourceStore`1.Get(String name) line 157
    TextureStore.getTexture(String name) line 69
    <>c__DisplayClass11_0.<Get>b__1() line 115
    Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
    --- End of stack trace from previous location where exception was thrown ---
    Lazy`1.CreateValue()
    Lazy`1.get_Value()
    TextureStore.Get(String name) line 112
    FontStore.Get(String name) line 119
    FontStore.Get(String fontName, Char character) line 145
    SpriteIcon.updateTexture() line 82
    SpriteIcon.load(FontStore store) line 65
```

Maybe an OS difference?

**Comment by huoyaoyuan** [comment]
There should be some *threading issues*. When I'm changing break points, my exception is no longer thrown.

I think that this PR reduces locks and increases concurrency, thus exposes some threading issue.

**Comment by bdach** [comment]
As for the font cache being held open by another process I've seen a similar thing before at ppy/osu#8420 (seemed to be caused by `Game.Fonts` not being disposed), but I'm not sure if that scenario is also relevant here.

**Comment by smoogipoo** [comment]
I don't understand how you're able to assert that. I'd like the required fix to be provided/investigated before this PR is merged, as I see no indication of such an issue in code.

**Comment by huoyaoyuan** [comment]
There is no longer Get call (potentially network IO) under `lock` statement now. Closing.

**Pull request closed without merging**
