### PR TITLE
Fix `GetBackwardWordAmount()` going back two words if the last word is only one character long

### LINKED ISSUE #4742: Ctrl+Backspace in TextBox deletes two words if last word is one character long
1. image
2. Press <kbd>Ctrl</kbd>+<kbd>Backspace</kbd>
3. image

I'd expect the text to be "this is a text "

<kbd>Ctrl</kbd>+<kbd>Del</kbd> is unaffected by this bug.

### PR DESCRIPTION
**Pull request by Susko3**
Fixes #4742 

I've tested this and it works fine.
Not sure if tests should be added for this.

### CODE REVIEW

**Comment by bdach** [comment]
Please do add tests if it is viable. I believe doing so should be relatively straightforward, as I recall tests have been added in the past for other textbox platform action failures, so the road should be paved.

**Comment by Susko3** [comment]
Closest TestScene is [TestSceneTextBoxEvents](https://github.com/ppy/osu-framework/blob/master/osu.Framework.Tests/Visual/UserInterface/TestSceneTextBoxEvents.cs), but this tests events, not test text editing.
TestSceneTextBoxEvents doesn't offer a simple way to: put text in textbox, perform action, check if the text looks the way it should.

A new test scene would be in order, but I don't feel like adding that and testing all text editing events right now.

**Comment by bdach** [comment]
That isn't really true. See `TestSceneTextBox.TestNextWordDeletion()` for one example.

**Comment by Susko3** [comment]
Have added tests now. `TestSceneTextBox.TestPreviousWordDeletionWithShortWords()` fails on master.

**Comment by bdach** [comment]
I've stared at this a bit and I'm reasonably certain that this change is correct, despite the old `- 2` code being quite old (pre-2016!). Index math is confusing as ever, especially that the selection position has fencepost error "built in", but it does make sense to start searching from index `i - 1` backwards and index `i` forwards, as I conceived by going off the following demonstrative example:

```
selection indexing    0 1 2 3 4 5 6 7 8
actual string          A B _ A|_ A B C
character indexing     0 1 2 3 4 5 6 7
```

**Review by bdach — APPROVED** [review]

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
