### PR TITLE
Add ScheduleAfterChildren()-API to Containers

### PR DESCRIPTION
**Pull request by default0**
Does what it says: Schedules a call to run the next time
UpdateAfterChildren() gets called.

### CODE REVIEW

**Comment by peppy** [comment]
what's the use-case for this one?

**Comment by Tom94** [comment]
The use case is to schedule stuff post-layout. Like chat scroll to end
without a hack delay that breaks at low frame times as is done in osu.

**Comment by peppy** [comment]
Is there an osu-level PR to move such things over? I would've thought there was at least one potential usage in the framework for this...

**Comment by Tom94** [comment]
Planned to make an osu pr with at least the chat fix once this is in. Can't
immediately think of a good use case within the framework, but I imagine
callbacks post-layout will be a thing in more places.

**Comment by peppy** [comment]
TO be honest, every place I can find UpdateAfterChildren usages, a `Cache-Invalidate-Refresh` pattern looks to work better...

**Comment by peppy** [comment]
Adding a scheduler specifically for scrollToEnd feels very wrong. Just add a single internal state for that instead?

I mean there's so many other scenarios where scrollToEnd won't work too (if new content appears when a ScrollContainer is off-screen it won't work etc.) to the point we probably want a permanent `ShouldBeAnimatedScrollingToTop`  bool or something.

management of keeping a scroll position should be the `ScrollContainer`s responsibility IMO.

**Comment by default0** [comment]
Regarding UpdateAfterChildren(): While using the framework I've encountered situations where the literal action, ie "let my children update, then update me" is necessary to get the right order of operations, where this wasn't purely related to just sizes not getting invalidated.
The concrete situation is that I needed a parent container to update based on a childs position, and the childs positioning was managed by the child itself, so the parent has to wait for the childs update to complete before making decisions based on it.

I can imagine similar situations where I will want to use ScheduleAfterChildren() because I need to do an action of a similar kind - but schedule it to the next frame - even though the only use-case I currently have in my own code is making sure that a ScrollContainer properly scrolls to its end.

**Comment by peppy** [comment]
override UpdateAfterChildren in the parent?

**Pull request merged**
