### PR TITLE
Add support for D3D tearing and waitable swapchains

### PR DESCRIPTION
**Pull request by smoogipoo**
- [x] https://github.com/mellinoe/veldrid/pull/484
- [x] https://github.com/mellinoe/veldrid/pull/485
- [x] New veldrid release

Input lag testing (PresentMon/CapFrameX):

| Mode | Input lag [Bound] |
| --- | --- |
| Before | ~70ms |
| New (no flags, never the case) | 29.3ms [24.5ms ~ 34.0ms] |
| `AllowTearing` (fullscreen) | 2ms [0.8ms - 3.0ms] |
|`WaitForNextFrameReady()` (windowed/borderless) | 12ms [5.4ms - 19.3ms] |

Historically, tearing has only been a thing in fullscreen mode and so I've kept it that way for now, however do note that it can also be applied in borderless ("exclusive fullscreen" does not exist in D3D).

### CODE REVIEW

**Comment by bdach** [comment]
When I spam alt-enter to toggle the display mode really fast, every now and again I can enter a wrong state such as this:

image

Not really sure what's going on there.

**Comment by smoogipoo** [comment]
Ah, I thought that was just my VM acting up. Will investigate.

**Comment by smoogipoo** [comment]
Will be fixed by https://github.com/ppy/veldrid/commit/068700a0a645f4af3ce37ba8d2ea95c7aaeb884d

**Comment by bdach** [comment]
Wrong sizing issue is fixed for me with the latest changes 👍 

I've also done some one-shot testing on my setup with capframex and while I'm not sure how to interpret the results exactly, it *seems* better?

| | current master | this PR |
| :-: | :-: | :-: |
| **primary monitor (165Hz)** | image | image |
| **secondary monitor (60Hz)** | image | image |

**Review by bdach — APPROVED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
