### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by bdach**
Bundled PRs from dependabot for easier testing/merging.

- [x] Needs testing on Apple devices.
- Includes #4119, #4120, #4121, #4123, #4125, #4126, #4127, #4128.
- Does **NOT** include #4122 - [see reason](https://github.com/ppy/osu-framework/pull/4122#issuecomment-753404061).
- Does **NOT** include #4124 - [see reason](https://github.com/ppy/osu/pull/11392#issuecomment-753373677).

Have checked linux, windows and android. All can boot sample game and visual test browser. Dynamic recompilation also works where it has a chance to.

### CODE REVIEW

**Comment by frenzibyte** [comment]
On macOS sample game and visual test browser runs fine, but dynamic recompilation seems to be actually broken on master, yields the following exception:
```
[runtime] 2021-01-02 00:20:25 [error]: System.IO.FileLoadException: Could not load file or assembly 'NuGet.Frameworks, Version=5.4.0.2, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)
[runtime] 2021-01-02 00:20:25 [error]: File name: 'NuGet.Frameworks, Version=5.4.0.2, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[runtime] 2021-01-02 00:20:25 [error]: at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
[runtime] 2021-01-02 00:20:25 [error]: at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
[runtime] 2021-01-02 00:20:25 [error]: at System.RuntimeType.get_DeclaringType()
[runtime] 2021-01-02 00:20:25 [error]: at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
```

Not sure if it's only me though, will do a quick investigation when I have a chance.

**Comment by bdach** [comment]
Wait, please clarify - you're saying that it's broken on `master` already, not just with this PR?

**Comment by frenzibyte** [comment]
Yeah, not sure why.

**Comment by peppy** [comment]
Was seeing the same thing. This turned out to be due to the specification in `global.json`. Removing the old version reference is enough to fix macOS, but this in turn breaks mobile builds (both iOS and android alike) as their csproj specifications require `MSBuild.Sdk.Extras` to be present.

I've added local `global.json` copies in the two projects which require it and removed the specification from the top level. Everything seems fine now.

**Review by peppy — APPROVED** [review]

**Pull request merged**
