### PR TITLE
Document `CursorEffectContainer` and update outdated name

### PR DESCRIPTION
**Pull request by voidedWarranties**

### CODE REVIEW

**Comment by frenzibyte** [comment]
I'm not sure I see the point in this PR. If there no follow-up changes containing actual useful changes following up on the presence of this documentation then there's no point in PR'ing this.

**Comment by frenzibyte** [comment]
ll

**Comment by voidedWarranties** [comment]
Sorry, but I don't understand why this was closed outright.

If the question is why I decided to document this class, then it's because I am working on generic text selection (possibly towards an implementation of #1618) and ended up deriving this class and encountering the non-trivial behavior I documented in this PR.

That being said, I don't see how that is relevant to this PR's merit. The beginning and end of this changeset is that I am trying to improve the code quality of `CursorEffectContainer` and allow future developers/consumers of framework to easily use/understand it by adding missing documentation. In my opinion, for changes like this, there shouldn't be any need for further justification.

Sorry if I am off base, I just want to understand the reasoning here.

**Review by peppy — APPROVED** [review]

**Comment by bdach** [comment]
> If there are no follow-up changes containing actual useful changes following up on the presence of this documentation then there's no point in PR'ing this

Huh? Where is *this* coming from? When has any of us ever said this? Baffled by this reaction as well.

Documentation is always welcome if someone is willing to contribute it.

**Comment by frenzibyte** [comment]
I hope you understand where I'm coming from here, all I'm seeing is a PR out of nowhere just adding comments over a class and moving on. If you don't then it's fine, I will leave such PRs alone, sure.

**Comment by peppy** [comment]
A quick check that the PR is of good quality and merge takes much less time than what happened in this thread as a result of closing it. And resulted in better code quality, so seems like a win-win to not go against the grain and raise questions.

Putting yourself in the PR opener's shoes can sometimes help!

**Pull request merged**
