### PR TITLE
Fix crash on minimising from non-native fullscreen resolutions

### PR DESCRIPTION
**Pull request by smoogipoo**
On a Windows PC, I noticed that running osu/osu-framework at non-native resolutions (1280x1024 on a 1920x1080 screen) would crash when minimising a fullscreen window, with:

```
2023-08-24 04:45:55 [error]: An unhandled error has occurred.
2023-08-24 04:45:55 [error]: NUnit.Framework.AssertionException: Stored Displays don't match actual displays: Stored displays:
2023-08-24 04:45:55 [error]: Name: Dell AW2521H, Bounds: {X=0,Y=0,Width=1280,Height=1024}, DisplayModes: 66, Index: 0
2023-08-24 04:45:55 [error]: 
2023-08-24 04:45:55 [error]: Actual displays:
2023-08-24 04:45:55 [error]: Name: Dell AW2521H, Bounds: {X=0,Y=0,Width=1920,Height=1080}, DisplayModes: 66, Index: 0
2023-08-24 04:45:55 [error]: at osu.Framework.Logging.ThrowingTraceListener.Fail(String message1, String message2) in C:\Users\mangos\Desktop\Share\osu-framework\osu.Framework\Logging\ThrowingTraceListener.cs:line 27
2023-08-24 04:45:55 [error]: at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
2023-08-24 04:45:55 [error]: at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage)
2023-08-24 04:45:55 [error]: at System.Diagnostics.Debug.Fail(String message, String detailMessage)
2023-08-24 04:45:55 [error]: at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
2023-08-24 04:45:55 [error]: at osu.Framework.Platform.SDL2Window.assertDisplaysMatchSDL() in C:\Users\mangos\Desktop\Share\osu-framework\osu.Framework\Platform\SDL2Window_Windowing.cs:line 318
2023-08-24 04:45:55 [error]: at osu.Framework.Platform.SDL2Window.<handleWindowEvent>b__282_0() in C:\Users\mangos\Desktop\Share\osu-framework\osu.Framework\Platform\SDL2Window_Windowing.cs:line 512
2023-08-24 04:45:55 [error]: at osu.Framework.Threading.ScheduledDelegate.InvokeTask() in C:\Users\mangos\Desktop\Share\osu-framework\osu.Framework\Threading\ScheduledDelegate.cs:line 106
2023-08-24 04:45:55 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal() in C:\Users\mangos\Desktop\Share\osu-framework\osu.Framework\Threading\ScheduledDelegate.cs:line 92
2023-08-24 04:45:55 [error]: at osu.Framework.Threading.Scheduler.Update() in C:\Users\mangos\Desktop\Share\osu-framework\osu.Framework\Threading\Scheduler.cs:line 124
2023-08-24 04:45:55 [error]: at osu.Framework.Platform.SDL2Window.RunFrame() in C:\Users\mangos\Desktop\Share\osu-framework\osu.Framework\Platform\SDL2Window.cs:line 303
2023-08-24 04:45:55 [error]: at osu.Framework.Platform.SDL2Window.RunMainLoop() in C:\Users\mangos\Desktop\Share\osu-framework\osu.Framework\Platform\SDL2Window.cs:line 278
2023-08-24 04:45:55 [error]: at osu.Framework.Platform.SDL2Window.Run() in C:\Users\mangos\Desktop\Share\osu-framework\osu.Framework\Platform\SDL2Window.cs:line 262
2023-08-24 04:45:55 [error]: at osu.Framework.Platform.GameHost.Run(Game game) in C:\Users\mangos\Desktop\Share\osu-framework\osu.Framework\Platform\GameHost.cs:line 788
2023-08-24 04:45:55 [error]: at osu.Framework.Tests.Program.Main(String[] args) in C:\Users\mangos\Desktop\Share\osu-framework\osu.Framework.Tests\Program.cs:line 23
```

This could be related to the recent AMD drivers that rewrote their OpenGL subsystem, or related to their private drivers which my testing's being done with, or could be a simple expectation of all desktop platforms. Here's the SDL events that happen at startup, minimise, and maximise:

```
Startup:

2023-08-24 04:37:58 [verbose]: SDL Event: SDL_WINDOWEVENT_MOVED, Displays changed: True
2023-08-24 04:37:58 [verbose]: SDL Event: SDL_WINDOWEVENT_SIZE_CHANGED, Displays changed: False
2023-08-24 04:37:58 [verbose]: SDL Event: SDL_WINDOWEVENT_RESIZED, Displays changed: False
2023-08-24 04:37:58 [verbose]: SDL Event: SDL_WINDOWEVENT_SHOWN, Displays changed: False
2023-08-24 04:37:58 [verbose]: SDL Event: SDL_WINDOWEVENT_FOCUS_GAINED, Displays changed: False
2023-08-24 04:37:58 [verbose]: SDL Event: SDL_WINDOWEVENT_ENTER, Displays changed: False
2023-08-24 04:37:58 [verbose]: SDL Event: SDL_WINDOWEVENT_EXPOSED, Displays changed: False
2023-08-24 04:37:58 [verbose]: SDL Event: SDL_WINDOWEVENT_EXPOSED, Displays changed: False

Minimised:

2023-08-24 04:42:15 [verbose]: SDL Event: SDL_WINDOWEVENT_SIZE_CHANGED, Displays changed: True
2023-08-24 04:42:15 [verbose]: SDL Event: SDL_WINDOWEVENT_MINIMIZED, Displays changed: False
2023-08-24 04:42:15 [verbose]: SDL Event: SDL_WINDOWEVENT_FOCUS_LOST, Displays changed: False
2023-08-24 04:42:15 [verbose]: SDL Event: SDL_WINDOWEVENT_LEAVE, Displays changed: False

Maximised:

2023-08-24 04:42:23 [verbose]: SDL Event: SDL_WINDOWEVENT_FOCUS_GAINED, Displays changed: False
2023-08-24 04:42:24 [verbose]: SDL Event: SDL_WINDOWEVENT_SIZE_CHANGED, Displays changed: True
2023-08-24 04:42:24 [verbose]: SDL Event: SDL_WINDOWEVENT_RESTORED, Displays changed: False
2023-08-24 04:42:24 [verbose]: SDL Event: SDL_WINDOWEVENT_ENTER, Displays changed: False
2023-08-24 04:42:24 [verbose]: SDL Event: SDL_WINDOWEVENT_EXPOSED, Displays changed: False

Minimised:

2023-08-24 04:42:30 [verbose]: SDL Event: SDL_WINDOWEVENT_SIZE_CHANGED, Displays changed: True
2023-08-24 04:42:30 [verbose]: SDL Event: SDL_WINDOWEVENT_MINIMIZED, Displays changed: False
2023-08-24 04:42:30 [verbose]: SDL Event: SDL_WINDOWEVENT_FOCUS_LOST, Displays changed: False
2023-08-24 04:42:30 [verbose]: SDL Event: SDL_WINDOWEVENT_LEAVE, Displays changed: False
```

Technically, the display change happens on `SDL_WINDOWEVENT_SIZE_CHANGED`, however that's a very wide-reaching event and I'm not sure on the cost of this particular method call. All of these events appear to be "batched" together, so it seems fine to use `SDL_WINDOWEVENT_FOCUS_GAINED`/`SDL_WINDOWEVENT_FOCUS_LOST`.

At least for the most part... WndProc wouldn't guarantee the batching is truly happening, but doing it on `SIZE_CHANGED` and `MOVED` seems excessive/expensive. Curious on @Susko3 's thoughts.

This PR adds code to refetch the displays on `SDL_WINDOWEVENT_FOCUS_LOST`, which seems appropriate since this was already being done in the `SDL_WINDOWEVENT_FOCUS_GAINED` pathway. Also on `SDL_WINDOWEVENT_SHOWN`/`SDL_WINDOWEVENT_HIDDEN` to handle startup (because it looks like `FOCUS_GAINED` is not batched appropriately there).

### CODE REVIEW

**Comment by smoogipoo** [comment]
Blocking for one sec. There's another issue at startup too, will likely add tests if I can.

**Comment by smoogipoo** [comment]
Added `SHOWN` event to handle the startup case, since there it appears like `FOCUS_GAINED` doesn't happen early enough. `HIDDEN` event added for good measure.

I can't add tests because this only happens with Alt+Tab and not via window state changes, which is handled by this code:

https://github.com/ppy/osu-framework/blob/ca5eb35deac5ae38b1b12403e4064e20165688ae/osu.Framework/Platform/SDL2Window_Windowing.cs#L521-L547

There's still another issue, which is that spam-clicking outside of the window at startup (with a game that is supposed to enter full screen) currently changes the resolution but does not raise the window. The SDL events in this case are:
```
[runtime] 2023-08-24 05:47:21 [verbose]: SDL Event: SDL_WINDOWEVENT_MOVED
[runtime] 2023-08-24 05:47:21 [verbose]: SDL Event: SDL_WINDOWEVENT_SIZE_CHANGED
[runtime] 2023-08-24 05:47:21 [verbose]: SDL Event: SDL_WINDOWEVENT_RESIZED
[runtime] 2023-08-24 05:47:21 [verbose]: SDL Event: SDL_WINDOWEVENT_SHOWN
[runtime] 2023-08-24 05:47:21 [verbose]: SDL Event: SDL_WINDOWEVENT_EXPOSED
[runtime] 2023-08-24 05:47:21 [verbose]: SDL Event: SDL_WINDOWEVENT_EXPOSED
```
(Note the absent `SDL_WINDOWEVENT_FOCUS_GAINED`)

The result is a desktop resolution change without the game being shown. `SDL_RaiseWindow` doesn't seem to resolve this. But I'll take this as a separate issue as I'm only intending to fix the crash here.

**Comment by bdach** [comment]
> This could be related to the recent AMD drivers that rewrote their OpenGL subsystem, or related to their private drivers which my testing's being done with, or could be a simple expectation of all desktop platforms

I can reproduce this on my windows/nvidia setup so definitely not drivers. My sequence of events is:

```
(tabbing in)
[runtime] 2023-08-24 11:51:00 [verbose]: SDL application log [info]: SDL EVENT: SDL_WINDOWEVENT (timestamp=32112 windowid=1 event=SDL_WINDOWEVENT_FOCUS_GAINED data1=0 data2=0)
[runtime] 2023-08-24 11:51:00 [verbose]: SDL application log [info]: SDL EVENT: SDL_WINDOWEVENT (timestamp=32113 windowid=1 event=SDL_WINDOWEVENT_ENTER data1=0 data2=0)
[runtime] 2023-08-24 11:51:01 [verbose]: SDL application log [info]: SDL EVENT: SDL_WINDOWEVENT (timestamp=32569 windowid=1 event=SDL_WINDOWEVENT_SIZE_CHANGED data1=1280 data2=960)
[runtime] 2023-08-24 11:51:01 [verbose]: SDL application log [info]: SDL EVENT: SDL_WINDOWEVENT (timestamp=32569 windowid=1 event=SDL_WINDOWEVENT_RESTORED data1=0 data2=0)
[runtime] 2023-08-24 11:51:01 [verbose]: SDL application log [info]: SDL EVENT: SDL_WINDOWEVENT (timestamp=32680 windowid=1 event=SDL_WINDOWEVENT_EXPOSED data1=0 data2=0)

(tabbing back out)
[runtime] 2023-08-24 11:51:03 [verbose]: SDL application log [info]: SDL EVENT: SDL_WINDOWEVENT (timestamp=35255 windowid=1 event=SDL_WINDOWEVENT_SIZE_CHANGED data1=1280 data2=960)
[runtime] 2023-08-24 11:51:03 [verbose]: SDL application log [info]: SDL EVENT: SDL_WINDOWEVENT (timestamp=35376 windowid=1 event=SDL_WINDOWEVENT_LEAVE data1=0 data2=0)
[runtime] 2023-08-24 11:51:03 [verbose]: SDL application log [info]: SDL EVENT: SDL_WINDOWEVENT (timestamp=35406 windowid=1 event=SDL_WINDOWEVENT_MINIMIZED data1=0 data2=0)
[runtime] 2023-08-24 11:51:03 [verbose]: SDL application log [info]: SDL EVENT: SDL_WINDOWEVENT (timestamp=35407 windowid=1 event=SDL_WINDOWEVENT_FOCUS_LOST data1=0 data2=0)
```

This PR does appear to fix this for me too, and it looks pretty safe. I'll test on my linux too in a sec (need to log into a wm with actual windows for this one).

**Review by bdach — APPROVED** [review]

**Comment by Susko3** [comment]
> Technically, the display change happens on SDL_WINDOWEVENT_SIZE_CHANGED, however that's a very wide-reaching event and I'm not sure on the cost of this particular method call. All of these events appear to be "batched" together, so it seems fine to use SDL_WINDOWEVENT_FOCUS_GAINED/SDL_WINDOWEVENT_FOCUS_LOST.
>
> At least for the most part... WndProc wouldn't guarantee the batching is truly happening, but doing it on SIZE_CHANGED and MOVED seems excessive/expensive. Curious on @Susko3 's thoughts.

Fetching the displays as soon as they're changed is not really that important. What's important is eventual consistency.
In my testing, the `SDL_WINDOWEVENT_SIZE_CHANGED`, `SDL_WINDOWEVENT_MINIMIZED` and `SDL_WINDOWEVENT_FOCUS_LOST` are handled within the same `pollSDLEvents()` call, so it's not that much of a difference anyway.

**Pull request merged**
