### PR TITLE
Add support for horizontal mouse scroll wheels

### PR DESCRIPTION
**Pull request by bdach**
Closes https://github.com/ppy/osu/issues/11326.

First commit makes the game not-crash if the wheel is used in a binding, second adds actual support.

Tested with the `xdotool` as suggested in the issue thread and it seems to work fine, however - @bob8677 - it'd be nice if you were able to test this game-side with a framework checkout (steps how to do this are described [here](https://github.com/ppy/osu-framework/wiki/Testing-local-framework-checkout-with-other-projects)).

### CODE REVIEW

**Comment by bob8677** [comment]
I can confirm that this change works, however I think the buttons are reversed (moving the wheel right says wheel left and vice versa).

**Comment by bdach** [comment]
That's pretty perplexing... I'd surely expect the positive X axis on the scroll to be right?

**Comment by frenzibyte** [comment]
It's correct for me on my trackpad, scrolling left (by moving my fingers to the left) presses "scroll left".

**Comment by bdach** [comment]
On my linux box, compared to firefox it does seem to be backwards, but [SDL docs seem to agree with my choice of coordinates](https://wiki.libsdl.org/SDL_MouseWheelEvent#Remarks) - but also helpfully state:

> SDL does not abstract the mouse wheel scroll directions to be consistent across all platforms (`SDL_MOUSEWHEEL_NORMAL`). If direction is `SDL_MOUSEWHEEL_FLIPPED` the values in `x` and `y` will be opposite. Multiply by -1 to change them back.

Quite helpful... Inclined to leave as-is as not in our scope.

**Comment by bob8677** [comment]
I don't think its a big deal for it to be backwards in some situations, as its not commonly used and doesn't affect anything that much anyway, as it still works.

**Comment by bob8677** [comment]
@frenzibyte could it be that way because of natural scrolling? Moving your fingers to the left is often set to moving things right. It seems wrong on my trackpad without natural scrolling turned on.

**Comment by peppy** [comment]
Tested on windows (directions seem correct).

- Added basic test coverage
- Fixed the test browser display cursor being back-to-front for x scroll

**Review by peppy — DISMISSED** [review]

**Comment by bdach** [comment]
Thanks a bunch. I pushed one more tiny cosmetic change as the test scene was looking a little busted with the new buttons on it:

2020-12-27-124403_1920x1080_scrot

Afterwards:

2020-12-27-124523_1920x1080_scrot

**Review by peppy — APPROVED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
