### PR TITLE
Make better use of generics in DependencyContainer

### PR DESCRIPTION
**Pull request by jorolf**

### CODE REVIEW

**Comment by peppy** [comment]
Looks good to me. Gonna get @smoogipoo to check this just in case.

**Comment by smoogipoo** [comment]
Do you have an osu!-side PR ready for this? LGTM

**Comment by peppy** [comment]
I have osu!-side changes ready to go. It' just two or three lines.

**Comment by smoogipoo** [comment]
Let's do this.

**Pull request merged**
