### PR TITLE
Open context menus when releasing

### PR DESCRIPTION
**Pull request by Joehuu**

### CODE REVIEW

**Comment by peppy** [comment]
Why on release? Every UI I’ve worked with is on down, to allow for single-click menu navigation.

**Comment by Joehuu** [comment]
Idk, right clicking a song on song select on stable had the same behavior.

And if you didn’t want to right click it in the first place, you can simply go out of the box or overlay while dragging.

**Comment by peppy** [comment]
After further consideration I tend to agree with this change for context menus. It should still be on mouse down for program-level menus (ie. the top menus in the editor) but that is already handled in a separate code path.

That said, the target for which the context menu is going to be displayed still needs to be *captured on MouseDown*. If this is not done, you are able to trigger the menu for a drawable which was nowhere near where you clicked.

**Comment by Tom94** [comment]
I think the `OnClick` logic is perfect for handling this due to it making sure _both_ the mouse down _and_ up event were on the same drawable.

**Comment by peppy** [comment]
@Tom94 unfortunately `OnClick` doesn't work for right mouse button clicks currently. Open for discussion on whether it should.

**Comment by Joehuu** [comment]
Closing as I cannot implement this.

**Pull request closed without merging**
