### PR TITLE
Framework Config Option to Change the Location of Saved Files

### PR DESCRIPTION
**Pull request by nobbele**
- Progress towards closing of https://github.com/ppy/osu/issues/2936

---

Adds a framework config option that allows you to change the location of all the saved files except for framework.ini since the framework needs a constant location to search for it in

### CODE REVIEW

**Comment by peppy** [comment]
This looks like it's going to read the config from one place and write to another.

**Comment by 4ppleCracker** [comment]
@peppy (insert method where framework.ini is written to) could be modified to use Storage.DefaultBasePath instead of BasePath

**Comment by peppy** [comment]
On further discussion we believe that the configuration file should not be moved to the storage directory. You may be able to create a `UserStorage : DesktopStorage` which adds the customiastion of the base path to ekep things tidy.

**Comment by peppy** [comment]
Closing in favour of #2271.

**Pull request closed without merging**
