### PR TITLE
Fix up FlowContainer conditional not properly accounting for fit fill…

### PR DESCRIPTION
**Pull request by smoogipoo**
Fixes Drawings crashing because this is being used in the case of `GroupTeam` which is auto-sized in the y-axis but the flag is fillmode-fit inside it.

### CODE REVIEW

**Comment by Tom94** [comment]
Can you describe your thought process behind how the if statement looks like now, potentially updating the comment above it? I have a hard time grasping what it is supposed to mean with this change.

**Comment by smoogipoo** [comment]
In the case that a child is relatively-sized on any of the parent's auto-sizing axes:
* If the child is fitting with relative size = both
  * The exception is not triggered. This is as per the comment above.
* If the child is fitting with relative size != both, then the "fit" size won't actually be calculated due to https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/Drawable.cs#L689
  * The exception should be triggered if the following conditions are also met.
* If the child is not fitting, same as above.

To be honest I'm not entirely sure what the conditions after this actually prevent, so that's my thought process purely on the fit change.

The other possibility is to remove the relativechildsize checks, which seem wrong in the first place, but I'm not sure if they had a use somewhere.

In-fact this has also led me to realize the AutoSizeAxes check is also in the incorrect place.

**Comment by smoogipoo** [comment]
@Tom94 I've removed the RelativeChildSize checks from the conditional, and hopefully simplified things a bit. Let me know if you agree with these changes, because as far as I can test this does not result in an autosize feedback loop in the following case:
```
Add(new FillFlowContainer
{
    Anchor = Anchor.Centre,
    Origin = Anchor.Centre,
    AutoSizeAxes = Axes.Y,
    Width = 60,
    Children = new Drawable[]
    {
        new Box
        {
            RelativeSizeAxes = Axes.Both,
            FillMode = FillMode.Fit,
            Size = new Vector2(1.5f)
        },
        new SpriteText
        {
            Text = "Testing!!!"
        }
    }
});
```

**Comment by Tom94** [comment]
Can't the child be larger than the parent, even if it has `FillMode.Fit` if one of its relative axes is larger than `Parent.RelativeChildSize`? This would cause a feedback-loop, so I believe the checks which you removed are actually necessary.

**Pull request merged**
