### PR TITLE
Add ability to configure double/float precision per config bindable

### PR DESCRIPTION
**Pull request by swoolcock**
Incoming PR for `OsuConfigManager` once this is merged.

### CODE REVIEW

**Comment by peppy** [comment]
I'd consider making this not have a default value, so every call explicitly states a value (or null if it *really* thinks that's a good idea)

**Comment by swoolcock** [comment]
Will do, but I'll have to make sure the osu! PR gets pushed through with the next framework update or it'll break the build.

**Comment by peppy** [comment]
That's fine.

**Comment by swoolcock** [comment]
To make `precision` a mandatory argument, it needs to go before `min`.  This could cause a regression for anyone using the framework, since their existing code would be passing in what they think is `min` and `max`, but the actual arguments in those positions are `precision` and `min`.  I suggest we leave it as optional by default.

**Pull request merged**
