### PR TITLE
Fix for Raw Input cursor leaving the window

### PR DESCRIPTION
**Pull request by Tom-Plummer**
It appears the OpenTK MouseState for Raw Input does not map the
coordinates received to the window, so a quick check against the bounds
of the current window allows for proper readjustment. This fix does not
work on windowed programs, but that is beneficial as the cursor
seamlessly follows the OS cursor.

This fixes issue #811.

### CODE REVIEW

**Comment by peppy** [comment]
This is not a correct fix. There is already a setting for confine mode, which this is not abiding to.

**Comment by Tom-Plummer** [comment]
Changes were working when I pushed them and cleaned them up, but now are broken when I pulled the updated repo. Debugging and will update.

**Comment by Tom-Plummer** [comment]
After a little accident of deleting the branch a proper fix is up and functioning properly.

**Comment by Tom-Plummer** [comment]
FUBAR'd the pull request with a bad push from git bash.

**Pull request closed without merging**
