### PR TITLE
Move Android native libs to osu.Framework.Android

### PR DESCRIPTION
**Pull request by swoolcock**
Similar to iOS changes in #2715.

### CODE REVIEW

**Comment by jorolf** [comment]
Don't we need the arm libraries to support linux systems that run on an arm chip? (e.g. a raspberry pi)

**Comment by swoolcock** [comment]
If that's the case, we'll need someone with a Raspberry Pi to test it out.  I think I have one somewhere, will need to fish it out though.

**Comment by jorolf** [comment]
It seems that the libraries that are currently in the framework are the wrong ones, it wouldn't run on a raspberrypi anyway (see https://github.com/ppy/osu-framework/pull/1955#issuecomment-432312265)

**Comment by swoolcock** [comment]
Alright, well for now let’s continue with moving them.

**Pull request merged**
