### PR TITLE
Parent fixes

### PR DESCRIPTION
**Pull request by smoogipooo**
I found only 35a7a932b7df0cc77f37bbfd055dfbed9752f268 as the reasoning for this check, however that was coded in a time when we were very dependent on parent, and it doesn't seem like this causes any problems through my testing.

### CODE REVIEW

**Comment by Tom94** [comment]
I don't think I like this. This gives the child `Drawable` the option to access `Parent` from within `load`, which we do _not_ want to support ever. I think it's best if children aren't made aware of their `Parent` to prevent them from accidentally depending on it too early.

**Comment by smoogipooo** [comment]
Why would we not support the child accessing `Parent` from `load`?

**Comment by smoogipooo** [comment]
Can you propose a better solution that would fix both https://github.com/ppy/osu-framework/issues/839 and https://github.com/ppy/osu-framework/issues/821 ?

**Comment by Tom94** [comment]
First because load can be on another thread. Almost all of `Drawable` stuff assumes both sides are on the update thread. All kinds of havoc will break lose if we start violating that.

Second, because anything inheriting Drawable should get their dependencied either via dependency injection or via their constructor. They should be usable anywhere in a scene graph, regardless of parent.

**Comment by default0** [comment]
Maybe just fix the ``Debug.Assert`` in ``Container.Remove`` to take ``IsLoaded`` into account or something along those lines? Sounds like the assertion is broken, not the logic of the ``Container.Add`` method.

**Comment by peppy** [comment]
that was my proposed solution too

**Comment by smoogipooo** [comment]
That covers one of the two issues, but what about the Depth issue? At some point we _need_ a parent reference to fix one, but this covers both.

**Comment by default0** [comment]
You could add a bool ``HasParent`` and explicitly document that it does NOT imply that ``Parent != null`` unless ``IsLoaded`` is ``true`` and use that for the check in ``Depth.set`` (and set ``HasParent`` to true regardless of load state). Or just make it internal to begin with (but even then the documentation would be helpful).

**Comment by smoogipooo** [comment]
Good solution.

**Comment by peppy** [comment]
Merging because this solves some potentially serious issues when using the framework and does not change the meaning or flow of any existing properties any more.

**Pull request merged**
