### PR TITLE
Fix glyph edge interpolation for non-transparent pixels

### PR DESCRIPTION
**Pull request by peppy**
Uploading glyphs, which are usually `rgba(255,255,255,x)` to a texture atlas initialised with `rgba(0,0,0,0)` would cause incorrect interpolation of edge pixels in the case where a glyph has a non-zero alpha value.

I attempted to fix this in multiple different ways, but the solution here is the best combination of being performant and future-proof. A faster method would be to change the initialisation colour of the texture atlas in the case of glyph stores and call it a day, but this would break any potential usages where a user has fonts with colour data.

Note that the new `initialisationColour` flow is (in the end) unused in this PR, but I've left it in place for potential future usage and clarity as to what is going on. If you want to test the performance of the alternative method (initialising with transparent white) you can do so by changing only the `initialisation_colour` constant in `TextureGLAtlas` (and commenting out the padding upload methods if you want to avoid the performance incurrence they carry).

In some quick testing, the overhead of this is negligible now that the span retrieval is outside of the loops. This turned out to be a huge performance concern (as you might expect) and is probably also the reason for https://github.com/ppy/osu-framework/blob/58eea16f51b401f4138986a80c19467d7e0cca55/osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs#L153, but that's for another day.

Cross-tested with `TestSceneWrapModes` to ensure the expectations there have not been altered.

Before:

20210806 163431 (dotnet)

After:

20210806 163455 (dotnet)

Before:

20210806 163725 (dotnet)

After:

20210806 163848 (dotnet)

---

If unsure about what is going on, here's some further details to hopefully ease review:

You can visualise the edges that are being drawn/interpolated to by altering the transfer function:

```csharp
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private void transferBorderPixel(ref Rgba32 dest, Rgba32 source)
        {
            dest.R = 255;
            dest.G = 0;
            dest.B = 0;
            dest.A = 255;
        }
```

This branch:
20210806 170403 (dotnet)
20210806 170626 (dotnet)

With the `initialisation_colour` change mentioned above:
20210806 170456 (dotnet)
20210806 170545 (dotnet)

Notice that with the `initialisation_colour` change it causes less of the border/padding uploads, which may be something we should investigate in the future (potentially better performance due to the "normal" case of glyph uploads requiring less uploads? but it does also incur a small i# overhead to initialise the `Image`).

### CODE REVIEW

**Comment by smoogipoo** [comment]
Some text looks really bad with this.

| before | after |
| --- | --- |
| spritetext_before | spritetext_after |

For example:
- "Run all steps"
- Fat top lines on `T` characters (e.g. in the test listing)
- Pixels to the sides of characters (`e` from `testy` at size 29, `9` at size 29, `3` at size 23).

**Comment by peppy** [comment]
I'll revert back the last commit, which will fix that case. It means that behaviour will change slightly, but I think it shouldn't be a huge concern (basically the alpha rule will be applied based on `wrapmode=none` rather than `alpha<255`). I had it this way initially and tried to change it as a "will fit better" rule, but seems like that can't be counted on.

**Comment by smoogipoo** [comment]
Just keep in mind, perhaps you know this, but `wrapmode=none` indicates no wrapping whatsoever. It doesn't mean that the texture stops at the border, but that GL has unlimited access to the rest of the texture. Based on that, I find it a bit weird that these rules are being applied to `wrapmode=none` in the first place imo.

**Comment by peppy** [comment]
That's the whole fix here - the padding was *not* applied with wrapmode none previously, which meant there were transparent black pixels there.

**Comment by smoogipoo** [comment]
Doesn't that indicate that `SpriteText` simply shouldn't use `wrapmode=none`? I find this change being applied in the general case to be very weird, it means every texture added to an atlas has an extra pixel of padding everywhere, and I'm not sure if that's wrong in some cases where normal sprites are used.

@Tom94 If you have a few minutes... Do you remember if there's a reason why we didn't apply padding to `wrapmode=none`? Was it purely a performance thing, or was there more to it?

**Comment by peppy** [comment]
It *is* using `wrapmode=none`. Please read through my opening post again. If still unclear let's voice since this should only take a few minutes of understanding.

**Comment by smoogipoo** [comment]
And I'm saying that it shouldn't?

**Comment by peppy** [comment]
If that's the case, the default would need to be changed for every sprite (I don't think we'd ever want the previous behaviour).

**Comment by smoogipoo** [comment]
Yeah, I don't disagree. I mentioned that in the original implementation: https://github.com/ppy/osu-framework/pull/3511#issuecomment-625161963

**Comment by peppy** [comment]
I see. Either way, check the latest commit - it should behave more in line with expectations. Changing the wrapping mode alone would not have been enough to fix the reported issue. There's still the choice of "using a=0 or using a=source.a" which is required in some way.

**Review by smoogipoo — APPROVED** [review]
Yep. This makes sense to me.

**Comment by Tom94** [comment]
Heya, just to answer smoogi‘s question about WrapMode.None: yes, IIRC the reason it doesn’t get padding on top of the mipmap-reared padding is purely performance-related. In all cases where good border interpolation is needed, WrapMode.ClampToEdge should do the trick.

I very much like the solution of an initialization color for optimizing special cases like fonts. 👍

**Pull request merged**
