### PR TITLE
Update SDL libraries with native library bump

### PR DESCRIPTION
**Pull request by peppy**
Closes https://github.com/ppy/osu-framework/issues/2198.
Closes https://github.com/ppy/osu-framework/issues/2525.
Closes https://github.com/ppy/osu/issues/11489.

### CODE REVIEW

**Comment by bdach** [comment]
Linux looks fine with this bump. Have not checked windows yet.

**Comment by peppy** [comment]
I've only tested on macOS, and had no issues there. @Susko3 are you able to confirm this fixes (at least one of) the bugs linked to make sure we're on the right track?

**Comment by Susko3** [comment]
I'm not able to test right now, I'll be available to test in 1-2 days.

**Comment by bdach** [comment]
Have tested with windows and both the <kbd>Win</kbd>+<kbd>Space</kbd> case and the game bar case look to be fixed.

**Review by bdach — APPROVED** [review]

**Pull request merged**
