### PR TITLE
Fix zero-size sprites being drawn

### PR DESCRIPTION
**Pull request by smoogipoo**
The real issue I wanted to address here is the `InflationAmount / DrawRectangle` divisions leading to `NaN` values, but I think it makes more sense to simply not draw sprites with zero sizes than inlining conditions.

### CODE REVIEW

**Comment by peppy** [comment]
Is this in response to an issue or call stack?

**Comment by smoogipoo** [comment]
It's a callstack from an internal branch that ensures the last added vertex equals the one given to the method. Which, due to the implementation of `Vector2.Equals()` actually fails because of the `NaN` values...

**Comment by peppy** [comment]
I see. There's a few other custom implementations of `Blit` (`TextureVisualiser` looks like the most likely to be offensive), are these confirmed to not require the same checks?

**Comment by smoogipoo** [comment]
Hmm... I mean it's kind of a much of a muchness, I only did it this way to avoid doing inline ternaries on the inflation percentage, but I can add it to `TextureVisualiser` if you really want it. Or I can change it to use ternaries.

The one in `BlitOpaqueInterior` is also not strictly required for the same reason as above.

**Comment by peppy** [comment]
Let's go with it as-is for now then.

**Review by peppy — APPROVED** [review]

**Pull request merged**
