### PR TITLE
Change initial file picker path on Android to `/storage/emulated/0`

### PR DESCRIPTION
**Pull request by Rystars**
changing the file path to /storage/emulated/0

### CODE REVIEW

**Comment by bdach** [comment]
This was talked about in https://github.com/ppy/osu-framework/issues/4895. I'm not sure what the final conclusion is in that thread, though.

**Comment by peppy** [comment]
`emulator` or `emulated`?

I won't begin to pretend I understand android so I'll leave this up to others.

**Comment by Rystars** [comment]
> `emulator` or `emulated`?
> 
> I won't begin to pretend I understand android so I'll leave this up to others.



> `emulator` or `emulated`?
> 
> I won't begin to pretend I understand android so I'll leave this up to others.

emulated

**Comment by Susko3** [comment]
I don't know if this is better than the current way, but I do know that that this will not always work.
The `0` in `/storage/emulated/0` denotes the current user and if the Android device has multiple users, this number will be `1`, `2`, etc. breaking this fix.

**Comment by Rystars** [comment]
> I don't know if this is better than the current way, but I do know that that this will not always work. The `0` in `/storage/emulated/0` denotes the current user and if the Android device has multiple users, this number will be `1`, `2`, etc. breaking this fix.

is it true? but I see on the internet mostly 0

**Comment by Susko3** [comment]
> but I see on the internet mostly 0

Most people have only one user on their device (or have multiple users without being aware of it). See [these docs](https://source.android.com/docs/devices/admin/multi-user-testing#device-paths) for more about multiple users.

**Pull request closed without merging**
