### PR TITLE
Fix state inconsistencies of DecoupleableInterpolatingFramedClock

### LINKED ISSUE #1633: Decoupleable clock should start when the source is started
Currently the following works as expected:

```
source.Stop();
decoupleable.ProcessFrame();
Assert.IsFalse(decoupleable.IsRunning);
```

But the following fails:

```
source.Start();
decoupleable.ProcessFrame();
Assert.IsTrue(decoupleable.IsRunning);
```

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/59856324-decoupleable-clock-should-start-when-the-source-is-started?utm_campaign=plugin&utm_content=tracker%2F44024461&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F44024461&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1634: Decoupleable clock's stopped state lags one frame behind
```
decoupledClock.Start();
source.Seek(1000);

decoupledClock.ProcessFrame();
decoupledClock.Stop();

Assert.AreEqual(1000, decoupledClock.CurrentTime); // Fails

decoupledClock.ProcessFrame();

Assert.AreEqual(1000, decoupledClock.CurrentTime); // Passes
```

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/59858858-decoupleable-clock-s-stopped-state-lags-one-frame-behind?utm_campaign=plugin&utm_content=tracker%2F44024461&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F44024461&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by smoogipoo**
Resolves #1633
Fixes #1634

Blocked awaiting osu!-side testing.

---

Fixes the state of decoupled clocks (used commonly for increasing precision beyond the audio driver's capabilities) lagging behind one frame.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Looks fine on osu!'s end, even after removing the PauseContainer schedule.

**Comment by Jamiewu2** [comment]
gah. This is what I was trying to fix with part of #1590 but I never got a response if the old functionality was intentional

**Comment by smoogipoo** [comment]
I saw that, and that's what led me to this path. I needed to have the adequate testing in place because there was a reason we didn't do this in the past - start/stop used to be non-blocking.

**Comment by Jamiewu2** [comment]
Oh ok, and `isRunning` would change immediately and not on completion?

In this implementation, the DecouplableClock doesn't seek to the same time if the source isn't running and the source seeks to some new position (and they're coupled). Not sure if that's something you want or not, or if that would cause bugs

**Comment by smoogipoo** [comment]
Yeah I discussed this with @peppy, and we reached the conclusion that since Decoupled.Start() will seek the clock to the source time (which is something we definitely want), seeking the source clock should be an unsafe operation.

Ideally we'd disallow the possibility of seeking the source clock but I can't think of a neat way to prevent that.

**Comment by peppy** [comment]
Seems to work no worse than before 👍

**Pull request merged**
