### PR TITLE
Add option to limit at 1x refresh rate

### PR DESCRIPTION
**Pull request by DuckI1ng**
Related discussions:
https://github.com/ppy/osu/discussions/18745
https://github.com/ppy/osu/discussions/23161

### CODE REVIEW

**Comment by jai-x** [comment]
1x refresh rate is the same as VSync.

What are you trying to achieve?

**Comment by DuckI1ng** [comment]
> 1x refresh rate is the same as VSync.
> 
> What are you trying to achieve?

It is not, using VSync comes with a latency penalty.

**Comment by BlauFx** [comment]
> > 1x refresh rate is the same as VSync.
> > What are you trying to achieve?
> 
> It is not, using VSync comes with a latency penalty.

In which way is there a latency penalty compared to 1x refresh rate?

**Comment by peppy** [comment]
Thanks for your contribution.

Sorry but this is not the correct forward direction. Frame limiters need a re-think and that will happen in the coming days, but adding this right now is very confusing to a user.

**Pull request closed without merging**
