### PR TITLE
Simplify SetProportional in BindableNumber

### PR DESCRIPTION
**Pull request by jorolf**

### CODE REVIEW

**Comment by peppy** [comment]
Hmm, we don't have any automated tests in the visual test for `SliderBar`. This may be a good opportunity to add a few.

**Comment by jorolf** [comment]
Just a shower thought: Should we add some easy way to simulate mouse/keyboard actions? The SliderBar mostly reacts to user input only so something like that would be great. 

I would imagine it being something like transforms:
```csharp
TestInputManager(optional?).MoveMouse(new Vector2(100, 100), duration: 0).DragMouse(new Vector2(100, 200), duration: 200, easing: Easing.In);
```

**Comment by smoogipoo** [comment]
Would be good @jorolf , but that's for a future consideration.

**Comment by peppy** [comment]
We already have this in the osu! project, right?

**Pull request merged**
