### PR TITLE
Horizontal scroll

### PR DESCRIPTION
**Pull request by Tom94**
In the future this can be extended to allowing scroll in both dimensions simultaneously.
Technically, this should already is possible by nesting 2 scroll containers with little changes to how axes are assigned inside scroll containers.

This will be useful for things like the editor timeline.

### CODE REVIEW

**Comment by peppy** [comment]
What's the reasoning for `int` instead of `Axes` in some places?

**Comment by Tom94** [comment]
The int can be passed to vectors via the [] operator to select the coordinate. Much cleaner than wrapping every vector access with ? :

**Comment by peppy** [comment]
I don't mind if you handle it that way internally for performance, but this should not be exposed in the ctor args.

**Comment by Tom94** [comment]
It is not exposed

**Comment by peppy** [comment]
🥇

**Pull request merged**
