### PR TITLE
Fix race condition in ThreadedTaskScheduler when adding tasks

### PR DESCRIPTION
**Pull request by smoogipoo**
See: https://github.com/ppy/osu/runs/17361055215#r0s1

### CODE REVIEW

**Comment by peppy** [comment]
Is there a reason the test coverage for this can't be committed?

**Comment by smoogipoo** [comment]
How? It's a race condition... It's just fails at some random point.

**Comment by bdach** [comment]
We've added such tests to source in the past. Compare:
 https://github.com/ppy/osu-framework/blob/ecc3ce5cfe4c8467c152cb46ee1c464e4d5f0932/osu.Framework.Tests/Polygons/ConvexPolygonClipperFuzzingTest.cs#L17
https://github.com/ppy/osu-framework/blob/ecc3ce5cfe4c8467c152cb46ee1c464e4d5f0932/osu.Framework.Tests/Visual/Drawables/TestSceneStressGLDisposal.cs#L16

**Comment by peppy** [comment]
Even if it's just run a few hundred times (and only fails one out of several runs), I think having the test around as a reference is valuable for any future manual testing.

**Comment by smoogipoo** [comment]
TIL. Added the test.

**Review by peppy — APPROVED** [review]

**Pull request merged**
