### PR TITLE
Outlined text

### PR DESCRIPTION
**Pull request by default0**
- [x] Depends on #813

### CODE REVIEW

**Comment by smoogipooo** [comment]
- This needs a test case, even just an `AddToggle()` in TestCaseSpriteText would be fine.
- Is there a reason for OutlineSigmaX/OutlineSigmaY? From my experience with photoshop an "outline" (i.e. stroke) is constant width on all sides.
- This is not the way we want to do text outlines. We'll want to increase the size of SpriteText's characters individually and draw a layer underneath each character with those. At the moment this is not going to be very useful.
- Issues with the way BlurEffect works mentioned in Discord, awaiting further discussion.

**Comment by Tom94** [comment]
Doing text outlines by increasing the size of characters is not a good way to do them. It will have a weaker outline near the centre of the character, and the insides of the character won't have outlines at all. What you actually want it to translate the character in all directions a bit, and then render these tons of translated characters. That's slow. And it's the exact same thing as applying a box filter. Since we currently do not support box filters, but they could easily be added to `BufferedContainer` I feel like this blurring approach is the right thing to do.

My main gripe with this PR is that it requires making and maintaining 2 sprite text. I think we should make a custom container inheriting BufferedContainer, which draws its children twice. Once, with all the effects, and then a second time without on top. This will also allow us to have outlines on other drawables than just text.

**Comment by smoogipooo** [comment]
@Tom94 it was also previously brought up that you wanted to implement it more generically through draw nodes, and I like that idea. I think we should do that.

**Comment by Tom94** [comment]
Yup, the way I'd like to do that is what I described in the second paragraph of my previous comment. Drawing the children twice would be implemented via a custom draw node mostly.

**Comment by smoogipooo** [comment]
This implementation requires maintaining two SpriteTexts while not completely providing a complete API for all of SpriteText's members (shadows, etc) because the container doesn't inherit SpriteText. Instead, this should be done through draw nodes, it will lead to a cleaner (and possibly more extensible) implementation.

Based on the above, I'm going to close this PR for now.

**Pull request closed without merging**
