### PR TITLE
Replace SQLite dependency with newer .net standard compatible one

### PR DESCRIPTION
**Pull request by Tom94**

### CODE REVIEW

**Comment by smoogipooo** [comment]
I'm not merging this one yet until the MigrateTable stuff is fixed. The following is my status on this:

* osu! for some reason still fails to add new columns to the DB.
* Forked the sqlite-net-pcl library, noticed they have a Migration test, which seems to do exactly what we're trying to do, except without explicitly calling `MigrateTable` (adding a column to an entity).
* Attempted to get debug SQLite running locally - quite unsuccessfully.

**Comment by smoogipooo** [comment]
Fixed. Just required a library update (apparently we added a super old stable release). @peppy requesting review

**Comment by peppy** [comment]
Has been rolled back. Please resubmit.

We need to ensure
- works with 32 and 64 bit
- works on linux and macos (at least test one of these)
- works with old and fresh databases

**Comment by peppy** [comment]
The remaining issue seems to be https://github.com/praeclarum/sqlite-net/issues/631

**Pull request merged**
