### PR TITLE
Avoid creating a second popover when one is already displayed for the current target

### PR DESCRIPTION
**Pull request by peppy**
As dicussed.

- [x] Depends on #4595 to avoid merge conflicts in tests

### CODE REVIEW

**Comment by bdach** [comment]
There was a possible issue with the guard, namely that `SetTarget()` could return `true` when going from null target to null target, and because the return value of that is used directly in `OnClick()`, that would lead to clicks being unnecessarily handled by the popover container.

I've fixed that; the rest (sans dependency concerns) looks good :+1:

**Review by bdach — APPROVED** [review]

**Comment by peppy** [comment]
> There was a possible issue with the guard, namely that `SetTarget()` could return `true` when going from null target to null target, and because the return value of that is used directly in `OnClick()`, that would lead to clicks being unnecessarily handled by the popover container.
> 
> I've fixed that; the rest (sans dependency concerns) looks good 👍

Oh, that was actually intentional (I changed it to ensure this was the case). Feels weird that a popover container should let input fall through in some but not all cases. Up for discussion I guess. Probably need a use case to work with.

**Comment by bdach** [comment]
If it was intentional, then `OnClick` should probably just hard-return `true`. Because the popover -> null case has `SetTarget` return false, it felt inconsistent that it wasn't blocking input but the null -> null case did.

**Comment by peppy** [comment]
I think what you've changed it to is fine until we come up with a case where it doesn't meet expectations. As you say, it's not consistent at least.

**Comment by peppy** [comment]
Actual test failure here, I'll investigate.

**Comment by peppy** [comment]
As discussed (in discord) this behaviour is no longer feasible as the default `Popover` handling dismisses a previous popover on mouse down, rather than on click. Will close this for now - we can revisit if it's ever required.

**Pull request closed without merging**
