### PR TITLE
iOS Visual Tests

### PR DESCRIPTION
**Pull request by swoolcock**
Makes visual tests run on iOS.

Currently only uses the manual test runner, but could potentially be set up to use `AutomatedVisualTestGame` for the simulator for CI.

Reimplemented using source file links so that the original `osu.Framework.Tests` project can remain mostly untouched.  Localisation tests currently won't compile in the iOS project to due to conflicts with `System.ValueTuple`.

Also moves iOS configuration to a separate properties file for sharing between projects.

### CODE REVIEW

**Comment by peppy** [comment]
Also fonts are not loading for visualtests here. Will need to look into it further.

**Comment by swoolcock** [comment]
I mentioned the font thing earlier, it’s something to do with the version of ImageSharp we’re using.  Using the latest myget version works.  Using my image loader will also fix it.

**Comment by peppy** [comment]
Aha, I see.

**Comment by swoolcock** [comment]
Issues with the current setup:

1) `dotnet test` must point to the assembly that contains the test cases.
2) That project must contain a reference to the test adapter.
3) The test adapter cannot be added to a `netstandard` class library, it must be `netcore` or .NET framework, etc. else you will get:
`Package 'NUnit3TestAdapter 3.11.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.`

So it looks like the project split may not be an option.  I'm thinking we could revert the visual tests project as it was, and make the `osu.Framework.Tests.iOS` project have links to the source in the `osu.Framework.Tests` project.  This would ensure that visual tests worked as they once did, while not requiring us to add a project reference from the Xamarin project.

**Pull request merged**
