### PR TITLE
Move iOS native libraries to iOS project

### PR DESCRIPTION
**Pull request by swoolcock**
Moves the iOS BASS libraries out of `osu.Framework.NativeLibs` and into `osu.Framework.iOS`.

1) Reduces the size of the NativeLibs package.
2) Increases the size of the iOS package.
3) We will no longer be distributing iOS native libraries with osu! desktop, as they were being brought in with the NativeLibs package.  This is negligible at the moment, but will become apparent when the FFmpeg libraries are added, as they are quite large (138MB).
4) The iOS native libraries will be copied into the output directory when building Xamarin projects, so no need to duplicate them in the osu! repository.

There is a small caveat.  In the `osu.iOS` project, since the libraries are extracted into the output directory on build, the `NativeReference` items need to point directly to `$(OutputPath)` to tell mtouch to copy them into its cache for native linking.

~~The catch is that the files are not extracted to the build directory until AFTER mtouch has cached the native libraries.  This means that the first build after a clean will fail, and you will need to rebuild such that mtouch can cache the libraries.~~

~~Merging this PR will not cause any problems with the existing setup, as we currently store duplicates of the native libraries in the osu! repository.  This will only become a problem when we remove those duplicates and rely solely on the libraries from `osu.Framework.iOS`.~~

Edit:

After some more investigation I believe the files *are* being cached in the correct order.  The issue is that because the project uses a wildcard to match the libraries in the empty `$(OutputPath)`, no libraries are actually passed into the `mtouch` command line.  Manually specifying individual files should work fine.  I'll check this out tonight.

### CODE REVIEW

**Comment by swoolcock** [comment]
Note that this PR will likely be a requirement for using FFmpeg on mobile.  Once this PR is merged I will have more PRs incoming to add the FFmpeg libraries, and to update the osu! iOS project to remove the duplicate libraries and point to the ones from the `osu.Framework.iOS` package.  We will also need to do the same for Android.

**Comment by peppy** [comment]
Also keep in mind that macOS currently doesn’t have bundled ffmpeg and relies on it being installed on the host.

**Comment by swoolcock** [comment]
They'll be different libraries to the iOS ones though, so if we decide to distribute FFmpeg with desktop for macOS they will just go in `osu.Framework.NativeLibs` no problem.  The iOS project won't import them since `ExcludeAssets="all"` is specified.

**Comment by swoolcock** [comment]
Updated to indicate new findings in regards to the native reference wildcard.

**Comment by swoolcock** [comment]
Alright, this is good to go.  After this I'll be making a PR to the framework repo to add the FFmpeg libraries, and a PR to the osu! repo to remove duplicate libraries and reference FFmpeg.

**Pull request merged**
