### PR TITLE
 Add track and sample fixed latency

### PR DESCRIPTION
**Pull request by MattiaPette**
ppy/osu#1616

For now the fixed latency is set to 35ms.

### CODE REVIEW

**Comment by peppy** [comment]
Did you test this? it does nothing.

**Comment by MattiaPette** [comment]
Did not managed to test, but according to the Bass documentation it really should work and it's the method intended to use.
Or maybe i'm wrong.
image
https://managedbass.github.io/api/ManagedBass.ChannelAttribute.html

**Comment by peppy** [comment]
you have to test before PRing

**Comment by peppy** [comment]
please reopen after testing things work

**Comment by MattiaPette** [comment]
Let me get home and i'll test, reopening after tests.

**Pull request closed without merging**
