### PR TITLE
Fix D3D11 losing performance by constantly mapping/unmapping buffers

### PR DESCRIPTION
**Pull request by smoogipoo**
Resolves https://github.com/ppy/osu-framework/issues/5779

I've encapsulated the relevant logic in an `IStagingBuffer<T>`.
- Persistently-mapped buffers appear to work out-of-the-box on D3D11 and Vulkan, but not on OpenGL.
- Persistently-mapped buffers _may_ also work on MTL, either by grabbing the contained `IntPtr` of the device buffer and using the more optimal `renderer.Device.UpdateBuffer()`, _or_ by the way the class already works. This needs more testing, and I've chosen to not change MTL's behaviour here.
- Therefore, managed buffers are used for MTL, OpenGL, and OpenGL ES. There should be no behavioural changes on those platforms.

Tested:
- [x] D3D11
- [x] Vulkan (Linux)
- [x] Vulkan (Windows)
- [x] OpenGL (Linux)
- [x] OpenGL (Windows)
- [x] Metal

### CODE REVIEW

**Comment by smoogipoo** [comment]
Hold off on this one for a sec, it changes Metal behaviour very slightly still.

**Comment by smoogipoo** [comment]
Should be good to go now. Not really happy about it but also not really wanting to test uncharted waters right now.

**Comment by bdach** [comment]
I'm not gonna pretend I know what is being done here too much but it does seem to make thing go faster™.

I did remove a double disposal of `stagingBuffer` in https://github.com/ppy/osu-framework/pull/5785/commits/09d6ed5fb36d2a493141d94513e67749c8b083b9 because I would hope it wasn't doing anything important. Other than that...

**Review by bdach — APPROVED** [review]

**Review by peppy — APPROVED** [review]

**Comment by smoogipoo** [comment]
> I'm not gonna pretend I know what is being done here too much but it does seem to make thing go faster™.

Right, I forgot to actually mention that.

`Map()`/`Unmap()` are expensive because they cause flushes. Specifically, data is flushed on `Unmap()`, and `Map()` appears to do its own bit of synchronisation.

The obvious solution (to me) of keeping Veldrid's staging buffers persistently mapped doesn't work because the data is overwritten for multiple vertex batches. There would need to be some mechanism where buffers are returned back to the pool after the GPU is done with it, but I can't figure out the D3D incantation for that (something similar to [MTL's completed handler](https://github.com/ppy/veldrid/blob/f1f8dc043257420240196bf896da03e52842dbad/src/Veldrid/MTL/MTLGraphicsDevice.cs#LL206C36-L206C36)).

One thing we need to watch out for is if there's any weirdness/glitching. The assumption I'm making here is that _within a single frame_, the data in one VBO is completely isolated to it and its staging buffer.

**Comment by bdach** [comment]
> One thing we need to watch out for is if there's any weirdness/glitching. The assumption I'm making here is that _within a single frame_, the data in one VBO is completely isolated to it and its staging buffer.

https://github.com/ppy/osu/issues/23538 looks eerily similar to that description. Mind you it's intel, so it may just be doing usual intel things.

**Pull request merged**
