### PR TITLE
Disable macOS locate pointer feature

### PR DESCRIPTION
**Pull request by Gentoli**
prevent macOS showing a larger cursor when the user shakes the mouse when the default cursor is hidden

### CODE REVIEW

**Comment by peppy** [comment]
Please do not force push after creating a pull request.

**Comment by Gentoli** [comment]
This should be good if putting ```PresentationOptions``` checks in ```OnUpdateFrame``` is ok.

**Comment by peppy** [comment]
Not sure we want this running every update call. Is there any reference documentation which says this is how you're supposed to handle this?

**Comment by Gentoli** [comment]
There is not really any reference on this, [here](https://developer.apple.com/documentation/appkit/nsapplicationpresentationoptions/nsapplicationpresentationdisablecursorlocationassistance?language=objc) is the official documentation.

This should only need to be set every time the window get focused, but setting it at `FocusedChanged` does not work. It will be reset for some reason and need to be set again.

**Comment by Gentoli** [comment]
Adding it to update window mode should been my first choice. Idk why didn't I do that in the first place.

no reason to keep fbda780 in the history.

**Comment by peppy** [comment]
@Gentoli for future reference (again, since you seemed to not see my original request), please don't force push after creating a pull request, even if you think a certain commit should not be in history. it breaks CI tooling and destroys contextual comments on github.

**Pull request merged**
