### PR TITLE
Move midi initialisation to a thread

### PR DESCRIPTION
**Pull request by peppy**
MIDI is rarely used. On top of that, on macOS the overhead on first call to the `Devices` enum is very expensive (>1s). This shouldn't delay startup of the game.

JetBrains Rider 2023-06-13 at 06 18 12

Implementation is copied from `OpenTabletDriveHandler`, which should be quite reliable.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Is the `return refreshDevices()` not also relevant here?

**Comment by peppy** [comment]
Hold off, this is really dodgy.

**Comment by peppy** [comment]
> Is the `return refreshDevices()` not also relevant here?

yes.

**Comment by peppy** [comment]
After 06d630ba1e052ac7bcff515e69b31d85679e41a4:

JetBrains Rider 2023-06-13 at 06 37 43

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
