### PR TITLE
Update NativeLibs to new version

### PR DESCRIPTION
**Pull request by peppy**

### CODE REVIEW

**Comment by huoyaoyuan** [comment]
Also remove the `Platform/Architecture` class in this PR?

**Comment by smoogipoo** [comment]
```
[runtime:verbose] 2019-11-05 03:07:50: VideoDecoder faulted: System.DllNotFoundException: Unable to load DLL 'avutil.56': The specified module could not be found.
[runtime:verbose] 2019-11-05 03:07:50: at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName)
[runtime:verbose] 2019-11-05 03:07:50: at FFmpeg.AutoGen.ffmpeg.<>c__DisplayClass5_0.<.cctor>b__0(String name)
[runtime:verbose] 2019-11-05 03:07:50: at FFmpeg.AutoGen.ffmpeg.<>c.<LoadLibrary>b__14_0(String x)
[runtime:verbose] 2019-11-05 03:07:50: at System.Collections.Generic.List`1.ForEach(Action`1 action)
[runtime:verbose] 2019-11-05 03:07:50: at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName)
[runtime:verbose] 2019-11-05 03:07:50: at FFmpeg.AutoGen.ffmpeg.<>c__DisplayClass5_0.<.cctor>b__0(String name)
[runtime:verbose] 2019-11-05 03:07:50: at FFmpeg.AutoGen.ffmpeg.<>c.<LoadLibrary>b__14_0(String x)
[runtime:verbose] 2019-11-05 03:07:50: at System.Collections.Generic.List`1.ForEach(Action`1 action)
[runtime:verbose] 2019-11-05 03:07:50: at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName)
[runtime:verbose] 2019-11-05 03:07:50: at FFmpeg.AutoGen.ffmpeg.<>c__DisplayClass5_0.<.cctor>b__0(String name)
[runtime:verbose] 2019-11-05 03:07:50: at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__5_318()
[runtime:verbose] 2019-11-05 03:07:50: at FFmpeg.AutoGen.ffmpeg.avformat_alloc_context()
[runtime:verbose] 2019-11-05 03:07:50: at osu.Framework.Graphics.Video.VideoDecoder.prepareDecoding() in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Video/VideoDecoder.cs:line 295
[runtime:verbose] 2019-11-05 03:07:50: at osu.Framework.Graphics.Video.VideoDecoder.StartDecoding() in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Video/VideoDecoder.cs:line 191
```

Seems this isn't properly outputting the DLLs.

**Comment by huoyaoyuan** [comment]
Going to have a try. The package should be identical when I did the test manually.

**Comment by huoyaoyuan** [comment]
Close IDE -> `git clean -xdf` -> Run
Works for me in SampleGame and initial run of visual tests. If native folders are empty, it will fail to load bass from the start.
Haven't check ffmpeg yet.

**Comment by huoyaoyuan** [comment]
Suggest minimal workaround at https://github.com/huoyaoyuan/osu-framework/tree/ffmpeg-workaround .
Going to refactor it further.

**Pull request merged**
