### PR TITLE
Create Keyboard Height Utility

### PR DESCRIPTION
**Pull request by NullifiedJosh**
This utility allows osu! to detect the height of the on-screen keyboard. This is important because when the keyboard covers a text box, it has a bad UX experience.

### CODE REVIEW

**Comment by NullifiedJosh** [comment]
I can see that someone has viewed this PR, but an update would be nice. I just don't want this to get stale state. No rush! 😀

**Comment by smoogipoo** [comment]
This, as well as any mobile PRs in general, are very time consuming for us to review and quite low priority as such.

**Comment by bdach** [comment]
If you don't wish this PR to become stale, then you should probably make it *do something useful*. As far as I can tell from source nothing is using these "keyboard utils" for anything, making all of the code added in this PR essentially dead and untestable.

Then again I don't really agree with the general direction of this PR in the first place. In the ideal implementation to me `DesktopKeyboardUtils` does not exist, period.

**Comment by NullifiedJosh** [comment]
@bdach Do you mean make a project with it? ok.

**Comment by bdach** [comment]
No. I mean the following:

Make these "keyboard utils" automatically work with every single current or future framework project when the software keyboard is pulled up, by using the safe area feature (which is already in place in the framework and works automatically for devices with notches) in order to move the game content away form where the software keyboard is shown.

**Comment by NullifiedJosh** [comment]
I think I would need a bit of help with that.

**Comment by NullifiedJosh** [comment]
I have an idea of how this could work, but it would make a break and change.

**Pull request closed without merging**
