### PR TITLE
Store handleability of input separate for keyboard and mouse

### PR DESCRIPTION
**Pull request by UselessToucan**
At the moment both keyboard and mouse input queues are built using `CanReceiveInput`(which depends on `HandleInput` property).
Since `HandleInput` does not distinguish keyboard and mouse events this causes one small problem. Keyboard queue can contain drawables which handles only mouse events and mouse queue can contain drawables which handles only keyboard events which is not correct.

I guess that not having unnecessary drawables in input queues is good in terms of performance.

On the other hand, I did increase the number of properties. :(
I hope this is acceptable since we do not override `HandleInput` often.
All overrides in osu! solution:
handleinput_overrides

[osu! game](https://github.com/UselessToucan/osu/tree/RefactorInputQueues) branch which I can PR if required.

### CODE REVIEW

**Comment by peppy** [comment]
I think I agree with this change, although not sure if there will be a scenario where we ever want to override only one but not the other.

**Comment by Tom94** [comment]
I would be against this if we hadn't added automatic setters of `HandleInput` yet. However, with the automatic setters in place I believe this change is totally fine and adds only minimal overhead to framework users.

Out of curiosity, though: Did you encounter any specific case where this change provides a measurable performance improvement?

**Comment by peppy** [comment]
I'd also be interested in whether there's a perceivable performance difference. But either way, I think if anything this could help in future usage scenarios which we haven't come across yet.

**Comment by UselessToucan** [comment]
To be honest, I did not perform proper performance testing, but theoretically it can't be worse than existing approach.
btw, @smoogipoo , your review is absent :(

**Comment by smoogipoo** [comment]
Also pls PR the osu!-side changes so we can get them in ASAP after these changes

**Pull request merged**
