### PR TITLE
Converted all line endings to CRLF.

### PR DESCRIPTION
**Pull request by ZLima12**
I have converted all line endings to CRLF as requested on the issues page ([#146](https://github.com/ppy/osu-framework/issues/146)).

### CODE REVIEW

**Comment by ZLima12** [comment]
I have now also added EOLs at the end of files that didn't have one.

**Comment by peppy** [comment]
Not gonna merge EOLs unless you can also provide a method to ensure this happens automatically on commit (else it will just get undone on next merge).

**Comment by peppy** [comment]
If you rebase this PR to just CRLF fixes I will merge, though.

**Comment by ZLima12** [comment]
@peppy I have removed the EOL commit as requested.

**Comment by peppy** [comment]
what are you changing on the files which had correct CRLF definitions previously?

**Comment by ZLima12** [comment]
@peppy whatever `unix2dos` thinks should be changed, as I just ran all plaintext files through it.

**Comment by peppy** [comment]
I'm hesitant to rewrite every file's header info if it's not necessary. Won't be merging this until more information is provided.

**Pull request closed without merging**
