### PR TITLE
Replace most usages of `IsDynamicCodeCompiled` with `IsDynamicCodeSupported`

### PR DESCRIPTION
**Pull request by frenzibyte**
`IsDynamicCodeSupported` returns true in iOS when building with interpreter mode on, so it's probably better to use that instead (kind of as a way of testing dynamic code on iOS). Note that I have kept the `TransformCustom` cases as they generate CIL instructions, which I'm not sure would outperform reflection in an interpretation environment (I have tested this and I didn't see any noticeable differences, but felt safer not to change it).

### CODE REVIEW

**Comment by smoogipoo** [comment]
Have you tested that this runs too?

**Comment by peppy** [comment]
Let's save this for after the next framework release, as to not add any potential regressions.

**Comment by frenzibyte** [comment]
> Have you tested that this runs too?

Yeah I've tested this just now on iOS, not sure about other platforms like Android though.

> Let's save this for after the next framework release, as to not add any potential regressions.

Yeah for sure.

**Comment by bdach** [comment]
> not sure about other platforms like Android though

You know what, I tested and am not sure either. Especially so that the OP is so wonderfully vague about why this is being changed that it matches the [actual](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.runtimefeature.isdynamiccodecompiled?view=net-7.0) [xmldocs](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.runtimefeature.isdynamiccodesupported?view=net-7.0) of both methods in uselessness.

Anyways, in testing, this seems to change _something_ on android:

image

Is this good or bad? Who knows. Game runs, at least. Music plays, tracks loop, so maybe fine.

I'll also bring up that [this was already mentioned for whatever reason over half a year ago](https://discord.com/channels/188630481301012481/589331078574112768/1051803662315421727). Why? No idea.

**Comment by frenzibyte** [comment]
See https://discord.com/channels/188630481301012481/589331078574112768/1127777353561542676, https://github.com/ManagedBass/ManagedBass/pull/118#discussion_r1257622779, and https://github.com/dotnet/runtime/issues/25959#issue-558370042.

**Comment by frenzibyte** [comment]
What you have there shows that the game is running using interpretation.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
