### PR TITLE
Don't inject local dependencies on self

### PR DESCRIPTION
**Pull request by peppy**
I don't think this is something we should be allowing. In the case a derived class needs to override something accessed directly in the thing it is overriding, the base should probably be modified to be aware of this. Or there should be more abstraction between components.

In standard DI this is not allowed; it's only possible here due to the order of calling.

### CODE REVIEW

**Comment by smoogipoo** [comment]
If we want to go down this route then I'm against keeping them called "local" dependencies, since they're for our children now, not for us + our children.

**Comment by peppy** [comment]
Do you have a better proposed name? `CreateChildDependencies` definitely sounds more ambiguous... `CreateDependenciesForChildren`? `CreateOverrideDependencies`?

**Comment by smoogipoo** [comment]
I'd be fine with `CreateChildDependencies` actually. It'd be very easy to explain what it does.

**Comment by smoogipoo** [comment]
@Tom94 / @default0 okay with this?

Rename `CreateLocalDependencies` to `CreateChildDependencies`.

Dependencies set in `CreateChildDependencies` are not used for our own `load()`.

**Comment by Tom94** [comment]
Sounds fair to me.

**Pull request merged**
