### PR TITLE
Avoid GC overhead during game load by only doing a full blocking collect at the end of a test run

### PR DESCRIPTION
**Pull request by peppy**
Previously this would be occurring many times during game load, causing crippling test performance in scenarios where the game takes considerable time to load.

### CODE REVIEW

**Comment by peppy** [comment]
Blocking until I confirm this solves the issue fully.

**Comment by peppy** [comment]
Tentatively unblocking. This improved performance greatly, but not fully to original levels (depending on the tests runnings.

Before the original `GC`:





Current `master`:



This change (local framework as `Release`):

**Comment by peppy** [comment]
Can confirm the remaining overhead is garbage build-up over longer test runs. Likely something we can resolve osu!-side (still investigating).

**Review by bdach — APPROVED** [review]

**Comment by bdach** [comment]
Have independently confirmed the speedups locally. Fingers crossed that this will translate to CI runtime.

**Comment by peppy** [comment]
As an update, I've made some further progress towards restoring performance.

JetBrains Rider 2022-05-29 at 20 00 21@2x

I think there's still some further savings to be had, but getting there.

**Pull request merged**
