### PR TITLE
Update inspectcode and fix new issues

### PR DESCRIPTION
**Pull request by peppy**

### CODE REVIEW

**Comment by peppy** [comment]
Am I missing something? The inspections mentioned on CI look to be incorrect (for instance the `MethodInfo` one looks to still be able to return null). Is there a `NotNull` specification somewhere?

**Comment by bdach** [comment]
The errors reported do seem bogus. All of them concern null checks after calling linq's `OrDefault` methods, and I'm seeing [other](https://youtrack.jetbrains.com/issue/RSRP-478172) [people](https://youtrack.jetbrains.com/issue/RSRP-478134) complain about it in JetBrains' issue tracker.

**Comment by peppy** [comment]
I guess we wait this one out...

**Comment by bdach** [comment]
Was a bit worried this wasn't going to be resolved until 2020.1, but apparently [a bug fix is planned](https://youtrack.jetbrains.com/issue/RSRP-478172#focus=streamItem-27-3948193.0-0).

**Pull request merged**
