### PR TITLE
Support Visual Basic projects for Dynamic Compilation

### PR DESCRIPTION
**Pull request by LeNitrous**
Would be helpful for those who make use of Visual Basic.

### CODE REVIEW

**Comment by peppy** [comment]
I think it should be possible to detect at compile or runtime which language is being used rather than duplicating the logic like this.

**Comment by LeNitrous** [comment]
Thought so too. I just took your earlier suggestion (that was a while back). It'd be cool to support all .NET-supported languages as well.

**Comment by smoogipoo** [comment]
You should be able to test for whether the assemblies `Microsoft.CSharp` or `Microsoft.VisualBasic` are loaded in the startup assembly.

**Comment by LeNitrous** [comment]
Closing in favor of .NET 6 Hot Reload

**Pull request closed without merging**
