### PR TITLE
Convert expensive WebRequest properties to methods

### PR DESCRIPTION
**Pull request by UselessToucan**

### CODE REVIEW

**Comment by bdach** [comment]
This is more *caching read responses in a field* rather than *avoiding allocations*. I suppose I don't see any arguments against this, but it appears to me that if this is going to be done, then both stream seeks could be safely removed?

**Comment by bdach** [comment]
Actually, wait, I do see a potential argument against it - this'll break `WebRequest` reuse, if that ever happens. Have you made sure they aren't reused anywhere?

Even worse, since `ResponseStream` is public, if web requests are reused you now have a correct and an incorrect way of reading the second response, using two different public members.

**Comment by UselessToucan** [comment]
> Have you made sure they aren't reused anywhere?

see https://github.com/ppy/osu-framework/blob/master/osu.Framework/IO/Network/WebRequest.cs#L72


> `ResponseStream` is public

There are only two external usages in the framework.
1. https://github.com/ppy/osu-framework/blob/master/osu.Framework.Tests/IO/TestWebRequest.cs#L486
2. https://github.com/ppy/osu-framework/blob/master/osu.Framework.Tests/Visual/Sprites/TestSceneVideoSprite.cs#L36

The first one probably can be replaced with `ResponseData.Length` call.
The second usage can be replaced with `new MemoryStream(wr.ResponseData)`. I understand that this solution is a workaround, but it may be acceptable for a test code where performance is not critical.

**Comment by peppy** [comment]
Where is a usage of this where this would be beneficial. ie. what is the premise for this change?

**Comment by UselessToucan** [comment]
> Where is a usage of this where this would be beneficial. ie. what is the premise for this change?

As far as I see, `ResponseData` and `ResponseString` properties are not called multiple times. Hence, there will be no benefit. But if this changes in the future, it will reduce allocations on the heap.

**Comment by smoogipoo** [comment]
I don't think the framework shouldn't be making any caching guarantees at such a low level. Should be left on a per-implementation basis to figure out how to store the given data imo.

With that being said, I would not be opposed to making these into methods like `GetResponseData()`. We use that in other places to indicate expensive methods.

**Comment by UselessToucan** [comment]
# `WebRequest.ResponseString` and `WebRequest.ResponseData` properties were converted to methods
`GetResponseString` and `GetResponseData` methods are provided as a replacement. This change was done in order to indicate that these operations are expensive(they do memory allocations in the heap on each call).

**Comment by peppy** [comment]
Please add redirections from old methods, adding the standard obsoleting policy (search in solution for other examples),

**Pull request merged**
