### PR TITLE
Check method arguments using Guard.ArgumentNotNull

### PR DESCRIPTION
**Pull request by UselessToucan**
The [Guards](https://github.com/thomasgalliker/Guards) project is a light-weight toolbox which helps you to protect your public interfaces against invalid parameters being passed over.

The goal of this PR is to eliminate some of the boilerplate code from our codebase.

I will try to replace other boilerplate exceptions later. Need some time to learn library API which is using expressions as input. (I would prefer to create separate PR later, if it is acceptable)

### CODE REVIEW

**Comment by default0** [comment]
So, what exactly makes ``Guard.ArgumentNotNull`` so much conceptually simpler and better than ``if(arg != null) throw new ArgumentNullException(nameof(arg))``?

I mean yes, you do save a bit of typing, but it is neither more nor less readable, there is no way in hell it is at any point in the future going to get rid of the necessary check and it generally neither removes nor adds any conceptual overhead. Personally I think the good of having less dependencies outweighs the good of saving some characters per null check.

Just my 2 cents on this, curious on other takes of this approach.

**Comment by peppy** [comment]
Yeah, I'm not sure I can agree with the extra dependencies required just to save a few characters.

**Comment by UselessToucan** [comment]
I would like to note that this dependency is lightweight. It is not something like, for example, GtkSharp.
screen shot 2018-01-14 at 15 12 51

**Comment by default0** [comment]
Well another thing to note is that the author requires you to contact him if you want to use it in commercial projects (see Licensing section in the readme). "Lightweight" still requires framework users to ensure that licensing works out when they want to distribute their applications. I really do not think this dependency is worth it.

That noted, even if it was MIT-licensed, the offered functionality is so incredibly tiny you might as well just write a small OsuGuard-class and use that, but fwiw I believe seeing the ``throw`` statements directly in the method body is clearer than needing to infer that ``Guard.ArgumentNotNull`` intends to throw an ``ArgumentNullException``.

If there are any advantages to this that I am missing outside of saving a few keystrokes, that might convince me that this is worth it, but so far I am not seeing any.

**Comment by smoogipoo** [comment]
As stated, this has licensing issues (nice find @default0), and I also don't see much benefit to this in general. Let's not do this yet.

**Pull request closed without merging**
