### PR TITLE
Disable manual mipmap generation (and decrease atlas size again)

### PR DESCRIPTION
**Pull request by bdach**
- Temporarily fixes https://github.com/ppy/osu/issues/23249
- Temporarily fixes https://github.com/ppy/osu/issues/23240 (as tested by @Joehuu)
- Temporarily fixes https://github.com/ppy/osu/issues/23318 (as tested by @Joehuu)
- Could possibly end up temporarily fixing some of the following (can't tell since I can't reproduce in the first place):
  - https://github.com/ppy/osu/issues/23285

As per [today's discussion in discord](https://discord.com/channels/188630481301012481/589331078574112768/1101851147570004030), this disables the meaningful changes made in #5508 to restore operation on configurations that have been negatively affected by the change (primarily appears to be mobile).

This is not a direct revert, and the goal was to keep the mipmap generation code in the tree, just in a disabled state, to permit revisiting the issue at a later date if necessary.

https://github.com/ppy/osu-framework/pull/5757 is a possible avenue for improvement in this stage, but it is currently not ready and @frenzibyte has no throughput to address the issues therein.

### CODE REVIEW

**Comment by bdach** [comment]
Before/after screenshots from devices I own:

| | last release | this PR |
| :- | :-: | :-: |
| Samsung J7 (2016) | Screenshot_20230429-161357 | Screenshot_20230429-171122 |
| OnePlus 8T | Screenshot_2023-04-29-16-09-39-72_25a1a32208bbcdc1d450b7aa854bb161 | Screenshot_2023-04-29-17-00-10-32_25a1a32208bbcdc1d450b7aa854bb161 |

Change is most apparent on the toolbar icons.

**Comment by Joehuu** [comment]
Can confirm on my Pixel 6a that https://github.com/ppy/osu/issues/23240 and https://github.com/ppy/osu/issues/23318 are fixed.

**Review by peppy — APPROVED** [review]

**Comment by Shirou27** [comment]
That means the stuttering will come back? With high atlas size seems reduced the stuttering on my Redmi Note 9 phone.

For me, I don't mind having text weirdness in expense for performance or less stuttering.

**Comment by peppy** [comment]
That's correct. Please read the OP.

**Comment by Shirou27** [comment]
I'm sorry but I don't know what is "OP" you're referring.

But I'm not gonna install the next updates for now until it come back or something replaced it that can reduced the stuttering while playing. What important to me is performance as it affects the whole game for me.

If I just have money, I would buy a high-end android phone.

**Pull request merged**
