### PR TITLE
Add maximum size support to GridContainer dimensions

### PR DESCRIPTION
**Pull request by smoogipoo**
Prereqs:
- [x] https://github.com/ppy/osu-framework/pull/2240

Adds `MaxSize` to `Dimension`.

### CODE REVIEW

**Comment by peppy** [comment]
I can think of a scenario where this will give results which could be considered

**Comment by peppy** [comment]
I can think of a scenario where this will give results which could be considered quI can think of a scenario where this will give results which could be considered questionable, but i'm not sure it matters so much.

- On the first pass two cells have max size, but only one hits their max size
- On the second pass the second cell with max size gets distributed more than it can accept. The extra is reassigned to cells but only cells to the right of that column.

I'm fine with this the way it is, just wanted to point this out.

**Comment by smoogipoo** [comment]
Do you have a testcase showcasing this?

The excess is not left/right associative, and is calculated in order from smallest min to largest, prior to any distribution occurring.

**Comment by peppy** [comment]
The first part is, but then the final distribution is not. I don't have a test case but can probably make one. To fix you'd basically have to keep re-running the distribution step until no rows hit their maximum size, but not sure if worth.

**Comment by smoogipoo** [comment]
Again I'm fairly certain this isn't possible. At the final distribution point it's guaranteed that no MaxSizes can be exceeded.

**Comment by peppy** [comment]
In this case maybe best to change the second maxsize limiting to an assert for clarity. I'll see if I can find a fail scenario.

**Comment by peppy** [comment]
Yeah, on further thinking I believe you are correct. Can we change the [second max size clamping](https://github.com/ppy/osu-framework/pull/2241/files#diff-4f052f2d0e544bce78afd3734b5abaf9R275) to an assert?

**Comment by smoogipoo** [comment]
The limiting there is required, all the code before that ensures that the limiting happens exactly when it's required.

**Pull request merged**
