### PR TITLE
Select resolution in fullscreen mode

### PR DESCRIPTION
**Pull request by UselessToucan**
Required for https://github.com/ppy/osu/pull/2715

### CODE REVIEW

**Comment by peppy** [comment]
What happens if the available resolutions list changes? Pretty sure you’re looking for #1588

**Comment by UselessToucan** [comment]
On the `DesktopGameWindow` level it will fallback to the highest resolution available(1920x1080@60Hz in my case).
https://github.com/ppy/osu-framework/pull/1589/files#diff-414962a93a3fbd7561a3a8d19a87ffc5R181

**Comment by peppy** [comment]
I was referring to the fact you are storing an index to a list that could change at any point in time. It can’t be done this way.

**Comment by peppy** [comment]
Is this one still relevant? If so, needs conflict resolution.

**Pull request closed without merging**
