### PR TITLE
Make children life update in BDL-load

### PR DESCRIPTION
**Pull request by smoogipoo**
The issue that sparked this: https://github.com/ppy/osu/pull/2496

**Explanation**:
`DrawableMedal` binds to `medalContainer.OnLoadComplete`, to set the position of some text contained within that container (i.e. `unlocked.Position = new Vector2(0f, medalContainer.DrawSize.Y / 2 + 10);`).

This is expecting two things:
1. The children of `medalContainer` are loaded.
2. The children of `medalContainer` is alive.

(1) Is fulfilled by `LoadComplete` being called from `UpdateSubTree`, which occurs post-all-children-being-loaded.
(2) Is where the issue occurs. `CompositeDrawable.load()` called `UpdateChildrenLife`, but it would get blocked by load state check in `checkChildLife`: https://github.com/ppy/osu-framework/compare/master...smoogipoo:async-child-life?expand=1#diff-2f079688019880634dc5249946a02502L407.
The next time child life gets updated is _post_-LoadComplete. So the children of `medalContainer` were loaded, but not alive.
This results in autosize not finding alive children and giving a `DrawSize` of 0.

A similar change as proposed in this PR was submitted some ~6 months ago (https://github.com/ppy/osu-framework/pull/1072) but then reverted (https://github.com/ppy/osu-framework/pull/1083). The reasoning was that some elements were broken (https://streamable.com/6pwqf, https://github.com/ppy/osu/issues/1366). Although these elements are not broken with the same changes as in the original PR, I chose to go down a different route and maintain that "children are not alive or loaded before their parent is loaded".

There are a few significant changes here:
1. `checkChildLife` no longer does load state checking. This is now done in `UpdateChildrenLife` and `AddInternal` - the only other use-case of `checkChildLife` through publicly-acccessible methods.
2. The previous functionality of `UpdateChildrenLife` has been moved to a new private method `checkChildrenLife`. The new method, like `checkChildLife`, does not perform load state checking.
3. BDL-load now uses `checkChildLife`, bypassing the load state checking of `UpdateChildrenLife`.

Additionally, I think the following will result in some discussion:
I've moved the call to check children life to `LoadAsyncComplete`, which happens _after_ BDL-load, 
but still on the asynchronous context, and prior to the drawable being given a `Ready` load state.
This was done because the alive state of children defined in BDL-load would previously be computed on the Update thread, when UpdateChildrenLife would be normally invoked.

**Testing**

It's hard to define exactly what to test with this. Obviously I've tested that it fixes the issue that sparked this, but I've also gone through all visual tests (osu! and framework-side) and found nothing breaking.

### CODE REVIEW

**Comment by smoogipoo** [comment]
osu load sequence-5

Made a flow chart of the loading procedure after this change, probably to be used in the wiki. One thing that caught my eye is that `CompositeDrawable.load()` still does `loadChild`, which won't load children constructed in derived bdl methods. We've had this discussion before and I think we should revisit it.

**Comment by smoogipoo** [comment]
osu load sequence-4-2

Updated flow chart.

Raw for future reference:
[osu! load sequence-4-3.xml.zip](https://github.com/ppy/osu-framework/files/1983561/osu.load.sequence-4-3.xml.zip)

**Comment by smoogipoo** [comment]
osu load sequence-4-6

Raw: [osu! load sequence-4-9.xml.zip](https://github.com/ppy/osu-framework/files/1983861/osu.load.sequence-4-9.xml.zip)

**Comment by smoogipoo** [comment]
osu load sequence-4-7

Raw: [osu! load sequence-4-10.xml.zip](https://github.com/ppy/osu-framework/files/1983871/osu.load.sequence-4-10.xml.zip)

**Comment by peppy** [comment]
Simplified diagram on the wiki: https://github.com/ppy/osu-framework/wiki/Diagram:-Loading-of-a-drawable

**Pull request merged**
