### PR TITLE
Specify Rider analysis rules explicitly

### PR DESCRIPTION
**Pull request by HoLLy-HaCKeR**
Different local code style settings causes Rider/ReSharper to show warnings when it shouldn't. This PR explicitly sets some of these settings. It doesn't cover all cases where this happens, only the ones which differed from my configuration (I no longer get any warnings).

### CODE REVIEW

**Comment by swoolcock** [comment]
Needs to be copy/pasted to the other solutions' DotSettings files.

**Comment by HoLLy-HaCKeR** [comment]
Yes, I'll do so when this gets approved.

**Comment by swoolcock** [comment]
I meant the iOS and Android framework solutions.

**Comment by peppy** [comment]
Yep, please add these rules to the other two files.

**Comment by HoLLy-HaCKeR** [comment]
Added them but I haven't checked if it got rid of all warnings since I don't have iOS or Android development set up so they show errors all over the place. There are still various differences between the solutions that I also didn't copy over.

**Pull request merged**
