### PR TITLE
Allow customising `ScrollContainer`'s scrollbar mapping

### PR DESCRIPTION
**Pull request by peppy**
For use in osu!.

### CODE REVIEW

**Comment by bdach** [comment]
What's the use case?

**Comment by peppy** [comment]
https://github.com/ppy/osu/pull/30579, sorry was writing things up.

**Comment by bdach** [comment]
My primary concern with this is that allowing this sort of override makes `ScrollbarMovementExtent` (which is public) sort of misleading if it is overridden the way it is in the game-side PR, because it will still appear as if the scrollbar can move the entire length of the container if reading that property, while in actuality it cannot.

Thoughts on making that protected instead or something?

**Comment by peppy** [comment]
We can try, hopefully nothing uses that in other projects.

**Review by bdach — APPROVED** [review]

**Pull request merged**
