### PR TITLE
Extract steps-related code from the TestScene

### PR DESCRIPTION
**Pull request by UselessToucan**
Current `TestScene` implementation violates SRP (Single Responsibility Principle).

I suggest to reorganize it this way:
* `TestScene` class which contains game objects which we are testing.
* `StepsContainer` class which contains the steps-related logic. Also, we might want to extract each step to a separate class.
* `TestSuite` class which contains NUnit-related stuff and testing code.

This PR extracts steps-related code from the `TestScene`.

If this PR will be approved, I will perform subsequent refactoring:
1. Extract NUnit stuff.
2. Rework communication between these three classes.

### CODE REVIEW

**Comment by peppy** [comment]
Keep in mind you will need to restructure this so there are *zero* changes required to existing `TestScene`s (via method redirects).

What are the perceived benefits of this?

**Comment by UselessToucan** [comment]
> What are the perceived benefits of this?

1. Code quality. It is uncomfortable to read and maintain a huge class which does multiple things.

2. I would like to make a more "traditional" software test development experience. This is good in terms of engaging the community into osu! development. I mean, almost every .NET developer knows how to write NUnit tests using stuff like [TestFixture], [Test], [TestCase], [Category] and so on. I think we might want to rely on these concepts instead of forcing people to do non-standart things. In current implementation tests are mixed with the SUT(game) code which is different from the usual software test development experience where test code is separated from the app code.

For example, [`TestSceneDropdown`](https://github.com/ppy/osu-framework/blob/master/osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs) testing logic may look like this:
```
[TestFixture]
public class DropdownTestSuite
{
    [Category("basic")]
    [Test]
    public void ClickDropDown1()
    {
    }

    [Category("basic")]
    [Test]
    public void Dropdown1IsOpen()
    {
    }

    [Category("SelectNull")]
    [Test]
    public void SelectItem1()
    {
    }
}
```

By the way, we will have more detailed NUnit output. I mean, each test will present in the runner UI(not just `Basic` and `SelectNull`).

**Comment by UselessToucan** [comment]
> so there are _zero_ changes required to existing `TestScene`s (via method redirects).

What is wrong with changing existing test scenes? Since I am ready to do it myself I don't see any problems.

**Comment by peppy** [comment]
We guarantee backwards compatibility for 6 months minimum, via `[Obsolete]` or otherwise. osu! is not the only consumer of the framework.

**Comment by UselessToucan** [comment]
Ok, I will add redirects and revert changes made to concrete test scenes.

**Comment by smoogipoo** [comment]
Let's come back to this one, not super necessary for now and the testing framework needs a bit of work...

**Pull request closed without merging**
