### PR TITLE
Overhaul transform logic to fix many failing rewind/seek cases

### PR DESCRIPTION
**Pull request by peppy**
- Fixes jumping forward to the middle of active transforms
- Fixes rewinding in general.
- Fixes rewinding over infinite loops.
- Adds visually understandable tests. Asserts can/should be added in the future.

### CODE REVIEW

**Comment by Tom94** [comment]
Did you verify that this doesn't break any aborting behavior in `TestCaseTransformSequence`?

**Comment by peppy** [comment]
Yeah, specifically tested that and added automated testing for it.

I think there may still be cases which break, but this requires further tests (ie. if a transform is aborted which isn't the last transform in a sequence, what should happen?).

**Comment by Tom94** [comment]
The rest of the sequence should also get aborted (i.e. everything that was `Then()`'d) and `OnAbort` of all of such transforms should get called. At least, that was how it worked when I implemented the sequences.

**Comment by peppy** [comment]
I changed this intentionally, as that behaviour was working badly with rewinding (abort would be called when a new transform interrupted an existing one).

we have usages in osu! where this is unexpected behaviour:

if you do `FadeTo(1, 1000).Then().ScaleTo(2, 1000)` and then 50ms later do `FadeOut(1000)`, would you expect the scale to still perform? If the answer is "no" then I'll have to re-think a portion of this change and make changes to osu! where `Then()` is used for mixed transform types where such behaviour is unexpected.

**Comment by peppy** [comment]
Also marking this as blocked for now, as I want to add some more automation to the testing.

**Comment by Tom94** [comment]
My answer is indeed, no. I think in such cases `Then` should not be used, but rather the second transform should be delayed via `Delay`. The semantic meaning of `Then` should be "happens after the previous form _completed_", whereas `Delay` is for "happens at specific time".

**Comment by peppy** [comment]
Okay, will change that back.

**Comment by smoogipoo** [comment]
So as for the general logic, the basic forward/rewind playback, I've convinced myself through a series of hand written tests that the logic follows through correctly.

I haven't yet looked through the loop logic, but I believe they'll be completely broken due to the mangling of StartTime as soon as a loop is triggered.

**Comment by smoogipoo** [comment]
@Tom94 Would you like some time to go through this, or shall I merge?

**Pull request merged**
