### PR TITLE
Deferred sprite

### PR DESCRIPTION
**Pull request by SirCmpwn**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
The other changes allow us to load textures from non-seekable streams.

**Comment by peppy** [comment]
Want to update `TestCaseOnlineTexture` to use this? Note that you may need to increase the delay in that testcase to something higher as we are currently experiencing a threadpool saturation bug.

Also thoughts about not requiring a second class for this and having it in Sprite itself?

**Comment by SirCmpwn** [comment]
>Want to update TestCaseOnlineTexture to use this? Note that you may need to increase the delay in that testcase to something higher as we are currently experiencing a threadpool saturation bug.

+1

>Also thoughts about not requiring a second class for this and having it in Sprite itself?

-1

**Comment by peppy** [comment]
Will leave this PR open for now following further discussion in discord.

**Pull request closed without merging**
