### PR TITLE
Fix CircularContainer using DrawSize too early

### PR DESCRIPTION
**Pull request by peppy**
Could be potentially caching an incorrect value.

Fixes https://github.com/ppy/osu/issues/1416

### CODE REVIEW

**Comment by Tom94** [comment]
While this looks like a good fix I am a bit concerned about how complicated it is to correctly implement such simple functionality within the framework. Gotta think some more about how this could be done better.

**Comment by peppy** [comment]
I think the major take-away is that we shouldn't be doing anything in the Invalidate override that *queries* properties.

Another alternative approach here is to just use `Schedule` instead of a `Cached`, wasn't sure which looks better...

**Comment by smoogipoo** [comment]
I prefer the Cached approach myself since Schedule would need to be cancelled.

**Comment by peppy** [comment]
good point..

**Pull request merged**
