### PR TITLE
Replace SQLite dependency with newer .net standard compatible one

### PR DESCRIPTION
**Pull request by Tom94**
Re-submission of the pull request.

We need to ensure
- works with 32 and 64 bit
- works on linux and macos (at least test one of these)
- works with old and fresh databases

### CODE REVIEW

**Comment by smoogipooo** [comment]
Just gonna add something here:

1.5.xxx beta versions are used because they're the only ones that contain the migration fixes allowing us to remove the explicit `MigrateTable` calls present in the osu! database.

Further information can be found in this issue thread https://github.com/praeclarum/sqlite-net/issues/461

**Comment by UselessToucan** [comment]
@peppy Do you have any interest in using EF Core instead of SQLite.Net? I looked at the DB related code and it does not look like a huge problem.

**Comment by peppy** [comment]
I'm open to other options, sure. If you're willing to give it a shot I see no harm in trying.

Would be interested to see if we still have Foreign Key support as we do with the SQLite.extensions package (along with cascade insert/delete/etc)

**Comment by Tom94** [comment]
Could somebody post a comment here specifying why the PR is currently blocked? I forgot the reason (likely has to do with migration requiring a beta version of sqlite-net-pcl), and I think it would be good just for having a record.

**Comment by peppy** [comment]
See my last comment in https://github.com/ppy/osu-framework/pull/1043. There's a low-level exception being thrown during disposal which seems to be affecting more people than just us.

There's no activity on the library itself, so it may be up to us to track down and fix this (at which point it may be worthwhile considering other libraries such as the EF version).

**Comment by UselessToucan** [comment]
I will submit pull request with EF Core usage in 2-4 hours. I need some time for resolving merge conflicts and maybe for some refactoring.

**Comment by peppy** [comment]
Closing in favour of #1085.

**Pull request closed without merging**
