### PR TITLE
Kill process when game goes out of focus on android

### LINKED ISSUE #2385: Android: Window focus does not update during app life cycles
Android Game Window `isActive` is never updated when the app moves between its relevant view cycles, and is stuck as `false`

Fixed in PR: #2384

### PR DESCRIPTION
**Pull request by SilkyPantsDan**
Fixes #2385 by ensuring the OpenTK UpdateFrame event is called when required (https://github.com/ppy/osuTK/pull/50). Initial testing with this looks fine on device, though as noted in the other PR there is an odd bass exception only on emulator that I would like to dig into more first.

In regards to the Android BG context losses - as mentioned in Discord, this PR will kill the process when background is detected and the app will restart once it is brought back into the foreground. Want to test this with the main game before final merge too.

### CODE REVIEW

**Comment by peppy** [comment]
Is this one still WIP? Does it depend on https://github.com/ppy/osuTK/pull/50 being merged?

**Comment by SilkyPantsDan** [comment]
Yes and yes - just haven't had a chance to test with the main osu game code yet. Debugging in the Sample game does set the `isActive` binding though, as well as killing the app when moving into the background.

**Comment by SilkyPantsDan** [comment]
OK - after learning the hard way that NuGet packages do not work the same as Cocoapods, I finally got it all into the main osu! Android branch and it seems to play quite nicely. Will give it a good run on the train morning though :)

* Application no longer garbles audio when put into background, and looks to restart fine from cold boot
* Game is no longer in pause loop once playing

Testing was all done with local packages - I am assuming I should update this PR with the osuTK package update as well @peppy? Looking at the moment the latest I see is 1.0.66 which I think was the last version?

**Comment by peppy** [comment]
Will be doing a build of osuTK within the next hour.

**Comment by SilkyPantsDan** [comment]
Cool, will update as soon as I can.

**Pull request merged**
