### PR TITLE
returning Push function when screen hasExited.

### PR DESCRIPTION
**Pull request by DevSDK**
The reason is that push function work with async.
So, That can be wrong work. Because Exit function can be called before async push function done.

I inserted function escape code when this scene exited.

### CODE REVIEW

**Comment by peppy** [comment]
What's the scenario here? You shouldn't be calling Push from a non-update thread, if that's what you're attempting.

**Comment by DevSDK** [comment]
Well, You can try to Press enter or click to Song Select And Press ESC and select again faster (Iterate)
OSU died.
I found that the push function work with hasExit value is true

**Comment by peppy** [comment]
I see. Not sure this is the correct path forward though. This may be best off throwing an exception, along with blocking off the paths which are causing these issues in the first place (maybe something like overriding HandleInput to not handle input after we have been exited).

Needs a bit more investigation.

**Comment by DevSDK** [comment]
You mean better push function to work with sync?
Or I need find other way?

**Comment by DevSDK** [comment]
How Do you think separate that exceptions hasExit == true and player ==null

**Comment by peppy** [comment]
this should definitely be an exception, not just a `return false`

**Comment by DevSDK** [comment]
Ummm, Your mean implement exception handler batter then return false?
Well, can i try this?

**Comment by smoogipoo** [comment]
1. Make that throw an exception rather than silently returning.
2. Figure out the case where this happens and make it not push while it's not the current screen.

**Pull request merged**
