### PR TITLE
Update c# language version to 9

### PR DESCRIPTION
**Pull request by peppy**
Mainly to fix the regression in `IHasCustomTooltip` disallowing struct usage (d90d27acb).

### CODE REVIEW

**Comment by peppy** [comment]
Blocked from 10 by iOS, 9 works and covers the requirements we have for now.

**Review by frenzibyte — APPROVED** [review]
Looks all good for me, have confirmed iOS working with both simulator and deploy to physical device.

**Comment by smoogipoo** [comment]
There's a lot of suggestions in the CI output (we need to upgrade the NVika package so these show up on GitHub). Probably worth adding `DotSettings` rules for them (it's the `new XType(...)` => `new(...)` stuff which I think we all don't like?).

**Comment by peppy** [comment]
I'll fix those.

**Comment by peppy** [comment]
NVika looks happy now. I'll apply similar changes to osu-side once this is merged.

**Review by bdach — APPROVED** [review]

**Pull request merged**
