### PR TITLE
Update tasks.json

### PR DESCRIPTION
**Pull request by loverthehater**
Cleaned up tasks.json, updated to 2.0.0 format, switched to .NET Core
compiler (extends functionality of MSBuild).

### CODE REVIEW

**Comment by peppy** [comment]
Have you checked the [netstandard](https://github.com/ppy/osu-framework/tree/netstandard) branch? I think this may already be done there.

**Comment by Bobo1239** [comment]
The netstandard branch is at least still using `msbuild` instead of `dotnet`.

**Comment by peppy** [comment]
aha, right. do you know if using dotnet adds the ability to use multiple processors?

**Comment by Bobo1239** [comment]
Sorry I'm not really a C# dev but a quick google search didn't suggest so though I'm not sure.

**Comment by loverthehater** [comment]
If this is what you're asking, `dotnet build` actually uses MSBuild (as it says [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build?tabs=netcore2x#description) right underneath the note) to compile, but I just thought that using the .NET Core SDK 2.0 was just more convenient as it's set up with features like [`dotnet add package`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package), [`dotnet test`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore2x), etc. It wouldn't be hard to switch the task back to MSBuild if that's preferable in this scenario. Could always go back to `msbuild` or even `dotnet msbuild`. I just really wanted to update the file to the 2.0.0 format, as every time I go to look at it, it tells me a lot of it's deprecated and this is just a small thing that I wouldn't think would hurt to add.

Also I think it's worth noting I decided on using `dotnet build /target:Clean` instead of `dotnet clean` because the former builds *and* cleans, while the latter just cleans, and I wasn't sure about the intent behind those tasks, but I think it's worth letting you know.

**Comment by smoogipoo** [comment]
To answer the parallel processing question: yes this does add parallel processing since it doesn't rely on mono's msbuild.

With that being said I want to test this myself later today because I didn't have much luck compiling net461 with dotnet previously.

**Comment by smoogipoo** [comment]
```
/usr/local/share/dotnet/sdk/2.0.3/Microsoft.Common.CurrentVersion.targets(1122,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/smoogipoo/Repos/Temp/temp-osu/osu-framework/osu.Framework/osu.Framework.csproj]

/usr/local/share/dotnet/sdk/2.0.3/Microsoft.Common.CurrentVersion.targets(1122,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/smoogipoo/Repos/Temp/temp-osu/osu-framework/SampleGame/SampleGame.csproj]

/usr/local/share/dotnet/sdk/2.0.3/Microsoft.Common.CurrentVersion.targets(1122,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/smoogipoo/Repos/Temp/temp-osu/osu-framework/osu.Framework.Tests/osu.Framework.Tests.csproj]
```

Yup, as I expected, dotnet build doesn't target .NET Framework projects on Unix systems. This issue is tracked here: https://github.com/dotnet/sdk/issues/335 but it still seems to be an ongoing issue. This may be resolvable with the new project sdk that's currently active in the `netstandard` branch. If you can port this over to that branch and we find it works, I will discuss with @peppy .

**Comment by loverthehater** [comment]
Alrighty doin that now

**Pull request closed without merging**
