### PR TITLE
Fallback to no sound device if no output device is available

### PR DESCRIPTION
**Pull request by MattiaPette**
The game shouldn't crash when no audio devices are enabled on the system.

Resolves https://github.com/ppy/osu/issues/1302

### CODE REVIEW

**Comment by peppy** [comment]
It doesn't look like this was actually tested.

Crash on losing last device:
untitled

Doesn't handle actual usage correctly: https://streamable.com/z1fkd

**Comment by MattiaPette** [comment]
Ok so, never seen that crash before, in order to replicate i think i have to open the game with no sound device enabled, enable it and disable again? correct me if i'm wrong.
The music player going like crazy i've never experienced that before, let me investigate more.

**Comment by MattiaPette** [comment]
Know issues:
- [ ] when starting with no audio the game loads a disabled audio output device (video link below)
- [ ] in the option menu the default option is not working
- [ ] the device list in the settings is not refreshing correctly (or not refreshing at all)

Now the game loads with no sound device and throws an exception if the user tries to play a beatmap.
The track player starts stopped. if you try to change track or play sound it goes like crazy.

Video reference: https://www.youtube.com/edit?o=U&video_id=WGJTuW8iX20

**Comment by peppy** [comment]
What's the status on this one?

**Comment by MattiaPette** [comment]
So i was practically redoing all the audio manager class because of a stupid driver issue of my external audio card that basically makes any other audio output/input device unusable.
The code still produces some bugs (non related to this issue) but i think there is a general improvement of the audio handling (like this methods don't stop the current playing audio track when switching device)
Just have a look at the code and decide if is worth continuing with this or not. I really don't mind if this code gets discarded

**Comment by peppy** [comment]
THe only reason I ask is that all tests are currently failing (see appveyor logs), which is a bare minimum for reviewing the code.

**Comment by MattiaPette** [comment]
Ok, so later I'll try to fix that and push a commit (in my local environment i'm pretty sure it works)

**Comment by MattiaPette** [comment]
Of course it triggers appVeyor -.-" oh well, sorry about that

**Comment by MattiaPette** [comment]
Don't mind me, a simple tasklist
- [ ] The frekkkkkkeing song player goes crazy, needToInvestigate.cs
- [ ] Why the settings dropdown of the audio device still remembers a device that is not enabled at all?
- [ ] Test all the things.

**Comment by MattiaPette** [comment]
Known problems:
- [ ] When no audio device is selected (aka no sound device available) the song player starts to playback all the songs causing ram usage and bg redraws like crazy.

**Comment by peppy** [comment]
Is it safe to say this is abandoned for now?

**Comment by peppy** [comment]
Thanks for the initial work on this fix. Closing in favour of #3025, which is in a more mature state.

**Pull request closed without merging**
