### PR TITLE
Make ScrollContainer more subclass friendly and add basic implementation

### PR DESCRIPTION
**Pull request by jorolf**
- the constructor of ``ScrollContainer`` (not ``ScrollContainer<T>``) is marked as obsolete
- all visual elements of the old ``ScrollbarContainer`` have been moved out to ``LegacyScrollbarContainer``

# vNext

## `ScrollContainer<T>` is now abstract (and `ScrollContainer` no longer exists)

In a push to make the provided framework components design agnostic, `ScrollContainer` is no longer provided. As a framework consumer you have a few options to resolve this:

- Use `BasicScrollContainer`

The framework now provides `BasicScrollContainer` and `BasicScrollContainer<T>`. These are drop-in replacements but come with the framework design language, so it is only recommended as a temporary solution.

- Implement your own local `ScrollContainer`

Here is consumable code to provide a local implementation that matches the removed one. Rename to suit your project and update your references:

```csharp
public class MyScrollContainer : ScrollContainer<Drawable>
{
    public MyScrollContainer(Direction scrollDirection = Direction.Vertical)
        : base(scrollDirection)
    {
    }

    protected override ScrollbarContainer CreateScrollbar(Direction direction) => new MyScrollbar(direction);

    protected class MyScrollbar : ScrollbarContainer
    {
        private const float dim_size = 10;

        private readonly Color4 hoverColour = Color4.White;
        private readonly Color4 defaultColour = Color4.Gray;
        private readonly Color4 highlightColour = Color4.Black;

        private readonly Box box;

        public MyScrollbar(Direction scrollDir)
            : base(scrollDir)
        {
            Colour = defaultColour;

            Blending = BlendingMode.Additive;

            CornerRadius = 5;

            const float margin = 3;

            Margin = new MarginPadding
            {
                Left = scrollDir == Direction.Vertical ? margin : 0,
                Right = scrollDir == Direction.Vertical ? margin : 0,
                Top = scrollDir == Direction.Horizontal ? margin : 0,
                Bottom = scrollDir == Direction.Horizontal ? margin : 0,
            };

            Masking = true;
            Child = box = new Box { RelativeSizeAxes = Axes.Both };

            ResizeTo(1);
        }

        public override void ResizeTo(float val, int duration = 0, Easing easing = Easing.None)
        {
            Vector2 size = new Vector2(dim_size)
            {
                [(int)ScrollDirection] = val
            };
            this.ResizeTo(size, duration, easing);
        }

        protected override bool OnHover(HoverEvent e)
        {
            this.FadeColour(hoverColour, 100);
            return true;
        }

        protected override void OnHoverLost(HoverLostEvent e)
        {
            this.FadeColour(defaultColour, 100);
        }

        protected override bool OnMouseDown(MouseDownEvent e)
        {
            if (!base.OnMouseDown(e)) return false;

            //note that we are changing the colour of the box here as to not interfere with the hover effect.
            box.FadeColour(highlightColour, 100);
            return true;
        }

        protected override bool OnMouseUp(MouseUpEvent e)
        {
            if (e.Button != MouseButton.Left) return false;

            box.FadeColour(Color4.White, 100);

            return base.OnMouseUp(e);
        }
    }
}
```

### CODE REVIEW

**Comment by peppy** [comment]
Any reason the base classes are non-abstract (and still constructed as-is)? All the other classes where we have "basic" implementation result in abstract underlying classes.

**Comment by jorolf** [comment]
Mostly because I didn't want this to be a breaking change. I can make them abstract if wanted

**Comment by peppy** [comment]
In that case, why mark the `ScrollContainer` ctor as obsolete? Seems halfway there to a breaking change. We should probably decide which direction we want to go. @smoogipoo thoughts on this?

**Comment by smoogipoo** [comment]
I think it's fine to make a breaking change here since the implementation overhead is minor. Extract the legacy scrollbar stuff into a gist and post it along with the breaking change for others to use.

**Comment by peppy** [comment]
Conclusion: Remove `ScrollContainer` and make this a breaking change.

**Pull request merged**
