### PR TITLE
Add AlwaysPresent for AudioContainer and fix AlwaysPresent not being taken into consideration when computing isMaskedAway or ShouldBeAlive

### PR DESCRIPTION
**Pull request by Drison64**
used for ppy/osu#29215

### CODE REVIEW

**Comment by smoogipoo** [comment]
Presence has nothing to do with being masked away or being alive. I'm fine with the property, if that's all that you need to get things working.

**Comment by Drison64** [comment]
I did not notice i pushed the ShouldBeAlive, i removed it and it still works.

**Comment by smoogipoo** [comment]
Yeah, that check is supposed to not pass. It has caused problems in the past but I don't think presence is the way to fix this, or at least I'm not ready to do it yet.

There are two solutions I can mention without having looked at the osu!-side code:
1. Make the container not be masked away in general.
2. Override `UpdateSubTreeMasking()` and return `false`.

**Comment by peppy** [comment]
Also agree here.

If anything, rather than exposing this as a setting it should be implicitly applied to `AudioContainer` without the user having control.

**Comment by smoogipoo** [comment]
I'm not sure about that... Means if at some point the entire game is wrapped in an `AudioContainer` no masking calcs would ever take place. Would prefer it to be applied to a local container where the intent is explicit, for now.

**Pull request closed without merging**
