### PR TITLE
Update TextBox design

### PR DESCRIPTION
**Pull request by jorolf**

### CODE REVIEW

**Comment by peppy** [comment]
Have you tested how this interacts with osu!? It may be that we need to refactor `TextBox `a bit as there's no `Basic `version of it (which means changes like this may affect other consumers of the framework).

**Comment by jorolf** [comment]
Most changes of ``TextBox`` are related to colour or font which should've been overriden by framework consumer anyway. The only thing we need to change for lazer would be the selection colour. (probably)

**Comment by peppy** [comment]
For the time being, to avoid breaking other projects using the framework let's put the new style inside a `BasicTextBox : TextBox` and revert the `TextBox` style back to how it was.

I made a start on this and adjusted the caret width (and placeholder positioning) to better suit, but the other changes needs to be reverted and moved too.

**Comment by jorolf** [comment]
I moved mostly everything over to ``BasicTextBox`` however I'm unsure wether I should do more than that (e.g. make ``TextBox`` abstract, somehow mark it as obsolete)

**Comment by peppy** [comment]
I think this is fine for now.

**Pull request merged**
