### PR TITLE
Interpolation<T> searches for interpolation method inside the generic class

### LINKED ISSUE #2284: Interpolation class throws an exception when trying to interpolate custom classes or structs
The line in question:
https://github.com/ppy/osu-framework/blob/39efa13cb4c00adff6b65842f8f57113c5bca9d5/osu.Framework/MathUtils/Interpolation.cs#L378

This means that you can't use the custom ``TransformTo`` extension method to interpolate properties with custom types. Examples: ``Padding`` or ``Margin`` which have the ``MarginPadding`` struct.

### PR DESCRIPTION
**Pull request by jorolf**
Fixes #2284

The method has to be called `ValueAt`, must be static and have the same parameters as `InterpolationFunc<TValue>`

Already existing ``ValueAt`` methods inside ``Interpolation`` can also be moved to their own classes (e.g. ``ColourInfo``)

### CODE REVIEW

**Comment by swoolcock** [comment]
Have you tested this on iOS?  We've previously had issues with the interpolation stuff with older versions of Xamarin.  Need to make sure it can safely handle any changes to reflection-based code, especially when dynamically creating delegates that may potentially cause problems with AoT compilation.

**Comment by jorolf** [comment]
I haven't because I don't have a working iOS dev environment. It would be nice if somebody else could test that.

**Comment by swoolcock** [comment]
I’ll test it for you tonight.

**Comment by swoolcock** [comment]
No problem running that test on iPhone X / iOS 12.2, other visual tests seem fine too.

**Pull request merged**
