### PR TITLE
Use STBI backend to load images on Desktop

### PR DESCRIPTION
**Pull request by Tom94**
STBI is roughly 2-3x faster than ImageSharp at loading PNG and JPG files. This is why we switch to it. We use the third-party library StbiSharp ( https://github.com/tom94/stbi-sharp ) to interface with native STBI.

Pending tests on the following platforms:
- [x] macOS
- [x] Windows
- [x] Linux

- [x] Depends on https://github.com/Tom94/stbi-sharp/pull/1

Also pending a test to make sure lazer still works
- [x] lazer still works

### CODE REVIEW

**Comment by bdach** [comment]
As nice as performance improvements are, what about the maintainability costs associated with this migration? The original C lib seem to have quite a few contributors, but due to the public-domain nature I can't tell how many actual end-users it has. The C# binding you've written looks simple enough (a couple of P/Invokes and a few bits of unsafe code), but we'd be the only significant user at this point.

**Comment by swoolcock** [comment]
@bdach this is exactly the kind of performance improvement we need.  Image loading is currently a huge portion of startup time, and it will also help with beatmap panels (since they are large images loaded in quick succession).

That said, some statistics would be great too.

**Comment by bdach** [comment]
I'm not doubting that image performance is important and I'm all for improving it. I'm just not sure how battle-tested STBI is and how much time/effort would be required to use it in comparison to ImageSharp.

If it's a drop-in replacement with no effort required, then sure, I have zero qualms! But I'm sure there's a lot of weird corner cases, and if STBI doesn't handle them as well as ImageSharp, the migration cost increases (and non-trivially too, since image reading will henceforth be in C, which is harder to write correctly).

**Comment by Tom94** [comment]
Given that STB has over 10k stars, I believe there have been quite a lot of eyes on it (as well as users). I also have a little bit of anecdotal evidence via my own image viewer (https://github.com/Tom94/tev), which is used by quite a few people in my field. Since its inception, I've never encountered a single user problem (and they open _all_ kinds of images) that was caused by STBI.

All that said, the code in this PR already falls back to ImageSharp whenever STBI (gracefully) fails to load an image, so all we need to trust is that STBI is correctly aware of which images it can't open. If even that ends up proving problematic---given osu!'s community focus, I am sure we will notice this quickly---switching back to ImageSharp is a matter of minutes.

**Comment by peppy** [comment]
In addition, i# has changed their licensing to be more commercial than before, so switching to a public domain library is a change in the right direction.

**Comment by huoyaoyuan** [comment]
@Tom94 just an implementation hint for you in StbiSharp: all the `byte[] data` can be replaced with spans. Spans and memories can be pinned, and can be implicitly casted from array.

**Comment by Tom94** [comment]
Thanks for the tip; done!

**Comment by peppy** [comment]
Make sure to bump the package reference in this PR.

**Comment by Tom94** [comment]
Don't think it actually matters for our use-case.

**Comment by peppy** [comment]
Confirmed working on linux, but CI isn't happy to compile with the Stbi library.

**Pull request merged**
