### PR TITLE
Remove DLW's special lifetime handling

### PR DESCRIPTION
**Pull request by smoogipoo**
Based on the findings found in https://github.com/ppy/osu-framework/issues/4440 - there are no cases where this passing of lifetime is used in any meaningful fashion.

### CODE REVIEW

**Comment by bdach** [comment]
I guess this is an alternative to #4439, as in if this one is merged, might as well not bother with that one.

This would be a pretty major breaking change but I'm not necessarily opposed to it in principle. I guess if the lifetimes are decoupled entirely, the worst case scenario is having a DLW with a content that becomes immediately dead. But that sorta makes sense too. Neither way is 100% good in all use cases, lifetime is one of the trickier parts of framework to grasp anyways.

All things aside I would definitely want to at least run this past game-side tests with a framework checkout before approving, though, if you haven't already - just to be extra sure I guess.

**Comment by smoogipoo** [comment]
> All things aside I would definitely want to at least run this past game-side tests with a framework checkout before approving, though, if you haven't already - just to be extra sure I guess.

Haven't done this yet.

> the worst case scenario is having a DLW with a content that becomes immediately dead

When do you foresee this happening? Is this a case where you'd `.Expire()` the content somehow, which we haven't done yet?

**Comment by bdach** [comment]
> Is this the case where you'd `.Expire()` the content somehow, which we haven't done yet?

That one might not be as much of a problem, because usually an expire usually means that the caller is done with the drawable anyways. I'm more worried about cases like pooling/drawable reuse and somebody forgetting to reset the lifetime somehow. But then again there's no real sane way out of that, either, other than just the programmer making sure everything is set correctly...

**Comment by smoogipoo** [comment]
The thing is, the current code means that the DLW itself could take on that bad lifetime and prevent the pooled drawable/whatnot from finishing the load process. The way around that is to consider `DelayedLoadComplete` in the getters as I mentioned in the issue, but then you start to introduce more special cases which become even more confusing for a user of the framework.

Imo there's something to be said for keeping things simple and consistent - in this case it's generally understood that when you touch lifetime, you only affect the drawable itself and don't cause side-effects in parents.

**Review by peppy — APPROVED** [review]
I think this is fine. Have run against osu!-side tests and it looks to behave okay.

**Pull request merged**
