### PR TITLE
Let coreclr automatically discover bass libraries on linux

### LINKED ISSUE #1638: Packaging improvement
Can someone create separate repo for native deps in ppy/ root? Then all .dll/.so/.dylibs can be moved in there and packed/deployed to nuget. With correct structure it will solve "missing bass" problem on linux while bulding.

### PR DESCRIPTION
**Pull request by morguldir**
This lets coreclr find the libraries inside the nuget package, see https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#architecture-specific-folders 

Adds libbass for armv6+ and aarch64 on linux. From https://www.un4seen.com/forum/?topic=13804

- Closes #1638

---

Fix crash on linux when not setting LD_LIBRARY_PATH. 
Add libraries required for linux arm support

### CODE REVIEW

**Comment by peppy** [comment]
As per CI, this seems to be failing in some cases.

**Comment by jorolf** [comment]
About those arm libraries.... the 32-bit ones don't work on (my) raspberry pi. Using the hardfp libraries instead of the softfp ones fixes that issue.
https://www.raspberrypi.org/forums/viewtopic.php?t=176144#p1123717

**Comment by VPeruS** [comment]
Look like it fix for "publish", "build" and "run" don't care about it

**Comment by peppy** [comment]
This is still failing CI and cannot progress beyond this point unless that is fixed.

**Comment by peppy** [comment]
This PR will need to be re-visited now that dependencies are in `NativeLibs` (see #2068).

**Comment by smoogipoo** [comment]
Closing as this is out of date and there have since been significant improvements to native lib packaging.

**Pull request closed without merging**
