### PR TITLE
Reduce size of texture atlases and allow automatic fallback

### PR DESCRIPTION
**Pull request by peppy**

### CODE REVIEW

**Comment by naoei** [comment]
Was there any reasoning for this change? I'm only curious as I have a project that utilizes a large texture atlas. However, due to this change, there's been a drastic increase in draw calls.

<table>
<tr>
	<td>
	<td>
</table>

**Comment by peppy** [comment]
The change was made to reduce stutter frames caused by allocating atlases at runtime.

You can use different texture stores to better group your textures, or wait until we offer better batching options.

The number of draw calls you show there should not be a huge cause for concern either.

**Comment by peppy** [comment]
@naoei how did you end up working around this, if at all? we're looking to address this in the near future and it would be good to get insight on your use case. i said above that the number of draw calls there should not be a cause for concern, but that was an incorrect statement based on the screenshots you provided (it's a pretty large concern).

**Comment by naoei** [comment]
I've ended up doing what you said and create [my own texture store](https://gitlab.com/Altenhh/gd.renderer/-/blob/master/gd.render.two/Textures/SpritesheetTextureStore.cs) which allowed me to use the max texture size the renderer could provide.

Can't say increasing `max_atlas_size` gave me any notable performance increase, but it definitely gave the GPU a lot of breathing room.


<table>
<tr>
	<td>
	<td>
<tr>
<tr>
	<td>
	<td>
<tr>
	<td> master
	<td> #5508
</table>

**Pull request merged**
