### PR TITLE
Remove platfrom dependent drag and drop

### PR DESCRIPTION
**Pull request by VPeruS**
Remove Windows specific drag and drop code from framework. File drop handling currently provided by OpenTK(see `NativeWindow.cs` -> `FileDrop` event) in platform agnostic manner.

### CODE REVIEW

**Comment by swoolcock** [comment]
I was actually going to work on this tonight...
Are you going to do the macOS implementation or would you like me to (since I already started)?

**Comment by VPeruS** [comment]
It will be for all platforms.

**Comment by swoolcock** [comment]
Because I already did most of the work in #945 
I just need to cherry pick stuff out of it.

**Comment by peppy** [comment]
i presume this is a WIP right?

**Comment by smoogipoo** [comment]
I want to see this re-implemented before merging this. No point just removing functionality.

**Comment by peppy** [comment]
Gonna close this for now since it's kinda pointless on its own.

**Comment by swoolcock** [comment]
Once https://github.com/ppy/osu/pull/1395 is in, this PR can be reopened and merged.
The removed `Drag` events should be reimplemented in OpenTK instead of osu!framework.

**Pull request merged**
