### PR TITLE
Improvements for AsyncDisposalQueue

### PR DESCRIPTION
**Pull request by huoyaoyuan**
Support `IAsyncDisposal`. We haven't started to use it, but some libraries has started, for example efcore.
The class is totally thread safe now. `Enqueue` can't be called from multiple threads before.
`ConcurrentQueue` is performant, especially when there's 1 producer and 1 consumer. And it nulls out taken elements.
The class is totally lock-free now, although locks are taken internally in framework types. We will get free benifits if their performance get improved.

Open question:
Should `Enqueue` method overloads for the same name? Some type may implement them both, then there will be an ambiguous call.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Afaik ConcurrentQueue is not guaranteed to release references on a deque, which is why it isn't used.

**Comment by peppy** [comment]
Reference: https://devblogs.microsoft.com/pfxteam/concurrentqueuet-holding-on-to-a-few-dequeued-elements/

https://github.com/ppy/osu-framework/pull/2410/commits/81746d7d3d1641a5bfd17fe67f9bc72579c3daae

**Comment by huoyaoyuan** [comment]
> For .NET 4.5, we’ve changed the design to strike what we believe to be a good balance.  Dequeued elements are now nulled out as they’re dequeued, unless there’s a concurrent enumeration happening, in which case the element isn’t nulled out and the same behavior as in .NET 4 is exhibited.  

https://source.dot.net/#System.Private.CoreLib/shared/System/Collections/Concurrent/ConcurrentQueueSegment.cs,13c2e10d2078f951,references
The flag will only be set when `GetEnumerator()` is called.

**Comment by peppy** [comment]
I know that we ran into this situation *in practice* in another location. I guess here we can guarantee enumeration is not occurring.

Also it would be worth testing the memory usage and performance of this change, since that disposal queue is a *very* hot path.

**Comment by huoyaoyuan** [comment]
> since that disposal queue is a *very* hot path

I've imagined several designs:
- Use `ConcurrentQueue`, exit the task when getting empty.
  Though creating tasks is not as heavy as creating threads, it's still heavy to guarantee it's **definitely create once** when object arrives.
  The old code operates them in batch. New batch only triggered when new object arrives, meaning there may be dead object lying in the list.
- Use `BlockingCollection`
  Will block a worker thread if the queue is starving.
  `Semaphore.Wait()` actually calls to `WaitAsync`, no allocation saved.
- Use `ConcurrentQueue`, spin when empty
  Wastes CPU if spins too fast; adds latency if spins too slow; but if the time is just-ok, will save overhead of semaphore.

Will the additional type check impact performance?
As blogs of guarded devirtualization shows, type check towards a concrete type has better performance than a vcall. I remembered type check towards **convariant generic interface** is slow. The disposal interfaces are non-generic.

**Comment by peppy** [comment]
First step is making a benchmark and testing!

**Comment by huoyaoyuan** [comment]
Closing for now. If we start to use `IAsyncDisposal` we can re-investigate this.

**Pull request closed without merging**
