### PR TITLE
Replace public delegates with events in DynamicClassCompiler

### PR DESCRIPTION
**Pull request by UselessToucan**

### CODE REVIEW

**Comment by peppy** [comment]
Not sure this is worth doing at this scale. Any particular reason for this that isn't obvious?

Last time this came up, we decided to wait until the "experimental" object-initializer support is added to final c# spec because it would make the migration of these a lot cleaner.

**Comment by smoogipoo** [comment]
We should not be relying on experimental changes/proposals to determine whether changes should be made, rather if they're made with good intentions.

I'm all for this change.

**Comment by peppy** [comment]
More what I was getting at is: why are we applying this to this one specific class (which is used internally at an application scale which isn't even being unbound)?

I'd argue we should also make `DynamicClassCompiler` internal (as it probably should be in its current state) or make it IDisposable with event cleanup logic etc.

I'd be interested to know how this came up @UselessToucan. Are you using this class in your own project or in a way where you need to bind more than one event?

**Comment by UselessToucan** [comment]
The reason I made this PR is that public delegates looks unreliable to me. The value of the public delegate can be easily rewritten by anybody.

> More what I was getting at is: why are we applying this to this one specific class

Because I wanted to see the feedback for this kind of changes without making breaking changes. I am ready to apply this everywhere in the game/framework if you are not against it.

**Comment by peppy** [comment]
Fair. But we probably want to add disposal logic (and `IDisposable`) in these cases, right? @smoogipoo

**Comment by smoogipoo** [comment]
I'd say yes in every case, but I'm also tempted to say only if the lifetime of the child object exceeds our own (which is not the case here).

**Comment by peppy** [comment]
I'm fine with that *if* this class is made internal.

**Pull request merged**
