### PR TITLE
Update SDL

### PR DESCRIPTION
**Pull request by peppy**

### CODE REVIEW

**Comment by peppy** [comment]
Blocking until we understand whether this will regress relative mouse support (see https://github.com/libsdl-org/SDL/issues/5271).

Will need to check github action build logs for which commit the last SDL2-CS package was built against.

**Comment by peppy** [comment]
Was already discovered that this has regressed in live builds, so I think we may as well push this one out.

**Comment by peppy** [comment]
@smoogipoo can you give this a quick run on linux and make sure nothing serious has exploded?

**Comment by smoogipoo** [comment]
Seems fine to me.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
