### PR TITLE
Add Transform loop support.

### PR DESCRIPTION
**Pull request by peppy**

### CODE REVIEW

**Comment by smoogipooo** [comment]
How do you feel about required calls to base.*? I've started to not like them in general and functionality which serves a "required" purpose should be encapsulated better. Would you have anything against having a separate method to update loops, and calling Apply after? Something like:
```
foreach (ITransform transform in Transformations) {
    transform.UpdateLoops();
    transform.Apply();
```

**Comment by peppy** [comment]
actually i wanted to bring this up with you yesterday. i tend to agree, and think that `base` calls are clumsy and prone to user error. this is being used in other places, so we should probably create an issue remind us to go through and fix them all up.

**Comment by smoogipooo** [comment]
So it looks like derived members will use the base member's default parameters, which is the reason the menu transforms aren't working. https://github.com/peppy/osu-framework/blob/loop-support/osu.Framework/Graphics/Transformations/ITransform.cs#L22 Should have loopCount = -1.

**Comment by peppy** [comment]
Oops, completely missed that!

**Pull request merged**
