### PR TITLE
Add IsNull()/IsNotNull() helper extensions

### PR DESCRIPTION
**Pull request by smoogipoo**
The following is a typical usage of binding to events of DI'd members:
```csharp
#nullable enable

public class MyDrawable : Drawable
{
    [Resolved]
    private SomeObject SomeDependency { get; set; } = null!;

    protected override void LoadComplete()
    {
        base.LoadComplete();
        SomeDependency.SomeEvent += someMethod;
    }

    private void someMethod()
    {
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (SomeDependency != null) // WARNING: Expression is always true according to NRT rules.
            SomeDependency.SomeEvent -= someMethod;
    }
}
```
I propose the `IsNull()`/`IsNotNull()` extension methods in order to bypass the warning inside `Dispose()` and increase our coverage of NRT. The resultant code becomes:
```csharp
protected override void Dispose(bool disposing)
{
    base.Dispose(disposing);

    if (SomeDependency.IsNotNull())
        SomeDependency.SomeEvent -= someMethod;
}
```

### CODE REVIEW

**Review by peppy — APPROVED** [review]

**Comment by huoyaoyuan** [comment]
In #5099, I found such always non-null warning was too aggressive, especially when the nullability can't be fully expressed.
The practice of .NET Runtime is that extra null check won't harm except extremely hot path.
How do you think about turning off the Resharper warning instead?

**Comment by smoogipoo** [comment]
Ah, I didn't notice this was only a resharper warning. That's a good point.

**Comment by smoogipoo** [comment]
The only disable ReSharper offers is a global disable, which we definitely don't want and removes half the purpose of NRT (to simplify and remove null checks).

This is a very extreme edge case for us, because we can usually assume the dependency is present in practically all user cases _except_ `Dispose()`. Any other cases are very unlikely to be hit - e.g. we can't assume dependencies are present in `CreateChildDependencies()` either but we haven't hit this case yet across the entire osu! game.

The only alternative I can provide is to use `!` everywhere, but that doesn't seem to be getting much traction within the team/contributors.

**Comment by frenzibyte** [comment]
> The only alternative I can provide is to use ! everywhere, but that doesn't seem to be getting much traction within the team/contributors.

Assuming this means marking dependencies as nullable and using `!` everywhere, and yeah I'm not sure about that approach, since a non-null dependency can only ever be null when accessed either before load or on disposal.

But I guess that can also become a major problem because it's easy to miss such cases during review... 

I don't have a strong opinion on this to be honest, and having `IsNull`/`IsNotNull` that should only ever be used when not able to do `!= null` feels off... I guess I could live with it if it's explicitly documented that the method is only meant to be used for such places, and never used anywhere else.

**Comment by frenzibyte** [comment]
> The only alternative I can provide is to use ! everywhere, but that doesn't seem to be getting much traction within the team/contributors.

Assuming this means marking dependencies as nullable and using `!` everywhere, and yeah I'm not sure about that approach, since a non-null dependency can only ever be null when accessed either before load or on disposal.

But I guess that can also become a major problem because it's easy to miss such cases during review... 

I don't have a strong opinion on this to be honest, and having `IsNull`/`IsNotNull` that should only ever be used when not able to do `!= null` feels off... I guess I could live with it if it's explicitly documented that the method is only meant to be used for such places, and never used anywhere else.

**Comment by bdach** [comment]
My two cents:

* Agree that disabling "redundant non-null" checks everywhere defeats most of the point of nullability annotations. Yes it is awkward in some cases, but it's better than the alternative of allowing anything and everything to be null-checked even if there is no conceivable way that it can ever be null. It's a code quality concern for me.
* I personally find the `!` operator to be sloppy - a "shut the compiler up" measure at best. Therefore, while it's unavoidable in some cases, I argue that its scope of use should be as narrow as possible. I would detest needing to sprinkle an exclamation point upon every single access to a DI'd component.

In light of both views I'm more than fine with these existing, except maybe I'd add a note in the xmldoc (probably in a remarks section) as to why they exist and what the intended usage is.

**Review by bdach — APPROVED** [review]

**Pull request merged**
