### PR TITLE
Fix broken texture coordinates in PathDrawNode/CircularProgressDrawNode

### PR DESCRIPTION
**Pull request by marcan**
Fix broken texture coordinates in PathDrawNode/CircularProgressDrawNode

This wound up being a recursive spiral of fail. The pattern `1 / Texture.{Width,Height}` is broken because those properties are integers, and  everything rounds to zero. Except for 1x1 textures where it doesn't round. But this whole code was broken for texture atlases because it was computing coordinates without taking the atlas into account, assuming it was a single texture. But it happened to work for WhitePixel because 1 - 1 = 0 and so the bottom right coord moved (by what the code thought was one pixel, but in reality was the whole atlas) to the top left corner, which is where the white pixel is.

Blergh.

* closes (potentially) ppy/osu#3215

#### original PR

> The pattern `1 / Texture.{Width,Height}` is broken because those
> properties are integers, and thus the division truncates to zero.
> 
> * closes (potentially) ppy/osu#3215

### CODE REVIEW

**Comment by marcan** [comment]
Note: this makes the code do what it was *intended* to do, but that doesn't mean it's actually *correct* (maybe the version without this adjustment was right), so whoever wrote the original code should probably chip in.

**Comment by peppy** [comment]
Nice find. It's really weird resharper doesn't pick up on this.

It can identify most incorrect usages:

image

**Comment by Tom94** [comment]
As the person who wrote the code: yes, that's definitely a bug, nice find. :)

**Comment by marcan** [comment]
So it turned out to be more broken than expected; see updated PR/commit message. Hopefully the new code makes sense and is more readable.

**Comment by marcan** [comment]
Also while I'm here I simplified the CircularProgressDrawNode logic a bit. There was a bunch of needless complexity there.

**Comment by marcan** [comment]
Oh derp, I totally forgot about that feature. I need to think about how the texture map interacts with that. You're right, this change would obviously break that use case. I'll look at it when I get home.

**Comment by marcan** [comment]
Can you test without the second commit? If that works as intended then I have a good reference to go by, and might just drop the second commit if I can't find a better way to simplify the code.

**Comment by Tom94** [comment]
Looks good without the second commit. 👍

**Comment by marcan** [comment]
Dropped the second commit from this PR. I'll give it a rethink and maybe add another test case to make the texture mapping more obvious. I think I might want to subtly change the behavior but that's a story for another PR.

**Comment by Tom94** [comment]
If you plan to change the behaviour of circular progress you might want to look into what currently happens when activating both "Horizontal Gradient Texture" and "Transition Focus [2]" at the same time in its visual test. The boundary behaviour as currently implemented seems buggy to me there.

I'll get this PR merged for now.

**Comment by Tom94** [comment]
Thanks for the fix!

**Pull request merged**
