### PR TITLE
Fix crash on startup on iOS due to host being null?

### PR DESCRIPTION
**Pull request by peppy**
I'm not sure I understand how this is happening, but this does fix the hard crash on osu! startup when running under iOS/Release (with debugger mode disabled). 

This is the only change required to make iOS work again. That said, I still think we want to get the `ConfigureAwait` changes in (#4261) because it's only a matter of time before we cause a deadlock like that.

This would explain why the await specific cases in `osu.Framework.Tests` where reproducible in the simulator while the osu! side crash was not.

A few things:

- The exception is silently eaten, causing the game to startup (and the draw thread to be waiting to draw). Not sure if this is an iOS specific issue, or if we are handling exceptions incorrectly across all platforms in some code path. We definitely need to investigate and fix this either way.
- This looks to somehow be caused by a race condition (or specific timing). Turning on Xamarin debugging support causes it to no longer fail. Also, testing on desktop platforms shows that the dependency is always available.

20210308 161954 (Xcode)

If any further debug information is required, I can run anything `lldb` from this point.

Note that this is probably not to be considered a final fix for the issue, without understanding how/why/what is going wrong.

### CODE REVIEW

**Comment by smoogipoo** [comment]
There's no way this fixes anything. I can't believe it. It would mean that the Drawable load sequence is _completely_ broken and would be a failure of catastrophic proportions.
1. The failing path is coming from `LoadComplete`, well after dependencies have been injected. There's 0% change that host is null.
2. The "exception" is EXC_BAD_ACCESS. This is a native exception.
3. This hasn't failed for us in the past year of iOS releases.

This is 101% a mono/xamarin.ios issue and needs isolation. At the absolute, bare minimum, this needs in-code documentation, even as a temporary fix, because this is so silly.

Does it always repro?

**Comment by peppy** [comment]
It's bad access on address `0x0`, which would imply null. But yeah, it's most likely some kind of monotouch/mono optimisation kicking in. I can't understand how it would be something our end and only fail in this one scenario.

As already mentioned in the opening post, I don't consider this an actual fix.

It's 100% repro. I've gone back and forth to `master` and confirmed multiple times.

**Comment by smoogipoo** [comment]
It's a mono-level native exception. Managed NREs don't terminate with kernel exceptions.

Make a Xamarin issue in that case (and are you updated to the latest Xamarin.iOS SDK?)

**Comment by peppy** [comment]
This is the same issue that has stopped iOS from running for several months. It's persisted across every SDK version, including going back to releases where it was working correctly. So it's likely something else in our codebase in conjunction that has triggered the issue. The code around this failure hasn't changed in recent times.

**Comment by smoogipoo** [comment]
Are you trying to say it's an issue with our codebase/our problem to fix? Because it's not. This is a GC or AOT issue (likely the latter) which our code hit a snag in. The reason it doesn't fail with debug is likely just due to lack of optimisations in the AOT.

**Comment by peppy** [comment]
No. I am not. I'm not sure where you are getting that idea.

Also to clarify, it fails on Release builds with optimisations, just with the debugger startup overhead (attaching a remote debugging via the xamarin tcp endpoint). Which is why I think it may be timing related.

**Comment by peppy** [comment]
To clarify: it started failing not on an SDK version change, but something our end (as far as I recall). So something we are doing broke something mono side, but changing SDK versions (as you suggested) doesn't have any effect.

**Comment by smoogipoo** [comment]
The op mentions:

> but this does fix the hard crash on osu! startup when running under iOS/Release (with debugger mode disabled).

Your comment mentions:

> it fails on Release builds with optimisations, just with the debugger startup overhead (attaching a remote debugging via the xamarin tcp endpoint)

Which one is correct?

**Comment by peppy** [comment]
Setting this to enabled:

20210308 173435 (Visual Studio)

and possibly turning on full debug information, can confirm this if it's important:

20210308 173506 (Visual Studio)

Other than that, the configuration is set to release.

**Comment by smoogipoo** [comment]
Can you provide a native stack trace? Like the one you get in console.log.

**Comment by peppy** [comment]
As mentioned in the opening post, there is none. It's hanging up via watchdog (10 seconds of frozen UI thread).

Here's the crash log.. doesn't show much helpful:

https://gist.github.com/peppy/9fe8f1d2b21528aaf8b5655191de53b6

It's also same as the original one posted in the issue thread (#4214).

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
