### PR TITLE
Implement Veldrid renderer

### LINKED ISSUE #4909: Add Veldrid renderer support (aka "compatibility mode")
We don't yet have good backwards compatibility support for older hardware, where the hardware (or drivers) don't support the OpenGL standards we rely on.

This covers adding the same level of compatibility that we have in osu-stable. It should preferably be an automatic fallback whenever opengl fails to initialise. 

---

Support progress:

- [x] Bare-minimum `IRenderer` implementation (https://github.com/ppy/osu-framework/pull/5483)
- [x] Vertex buffers support (https://github.com/ppy/osu-framework/pull/5595)
- [ ] Shaders support (https://github.com/ppy/osu-framework/pull/5647)
- [ ] Textures support (https://github.com/ppy/osu-framework/pull/5647)
- [ ] Framebuffers support (https://github.com/ppy/osu-framework/pull/5647)
- [ ] Video textures support (https://github.com/ppy/osu-framework/pull/5647)
- [ ] Handle backend-specific differences (https://github.com/ppy/osu-framework/pull/5647)
- [ ] Screenshot rendering support (https://github.com/ppy/osu-framework/commit/8ad7ed6761943519501e8179edbc8f68d4d6c1bb, wip, doesn't fully work)
- [ ] Clean-up remaining GL calls (e.g. translation functions in `BlendingParameters`)

### PR DESCRIPTION
**Pull request by smoogipoo**
- Closes #4909 

Prereqs:
- [x] https://github.com/ppy/osu-framework/pull/5655

Extracted / improved upon from https://github.com/ppy/osu-framework/pull/5647 with much thanks to @frenzibyte for a large chunk of implementation that I've refactored since.

## Abstract

This implements the Veldrid renderer, which is accessible via the argument `--renderer veldrid`. It's not the default yet, pending testing/fixing on more platforms.

## Coordinate spaces

A big change in this PR is the introduction of workarounds for clip-space differences between renderers. The best documentation I've seen on the matter is https://matthewwellings.com/blog/the-new-vulkan-coordinate-system/, and I've chosen to follow the same path of adding a shader-level workaround for it.  

I propose we break this in the future and invert our Z-coordinates - right now -1 is into the screen and 1 is the camera, and inverting it would make 0 the camera position and 1 into the screen.

## Testing

osu!-side testing can be done with the following changesets:
- osu-framework: https://github.com/smoogipoo/osu/tree/veldrid-renderer-2 ([#5661](https://github.com/ppy/osu-framework/pull/5661))
- osu: https://github.com/smoogipoo/osu/tree/veldrid-renderer ([#22750](https://github.com/ppy/osu/pull/22750))
- osu-resources: https://github.com/smoogipoo/osu-resources/tree/opengl-core-renderer ([#247](https://github.com/ppy/osu-resources/pull/247))

Renderer/surface combinations can be tested with the following environment variables:
```
OSU_GRAPHICS_RENDERER=veldrid/gl
OSU_GRAPHICS_SURFACE=opengl/metal/vulkan/direct3d11
```

The below tests are only for the **Veldrid** renderer.

- [x] Linux (AMD) (OpenGL)
    - intro animation is broken
- [x] Linux (AMD) (Vulkan)
    - vsync broken ([#5649](https://github.com/ppy/osu-framework/issues/5649))
    - graphics broken (likely driver issue)
- [x] Linux + VMWare (OpenGL)
- [x] Linux + VMWare (D3D)
    - effects broken
- [x] Windows (OpenGL)
- [x] Windows (D3D)
    - effects broken
- [x] Windows (Vulkan)
    - videos crash
- [x] macOS (M1, OpenGL)
    - crashes, known issue (unknown cause)
- [x] macOS (M1, Metal)
- [x] macOS (x86, OpenGL) 
    - crashes, known issue (unknown cause)
- [x] macOS (x86, Metal)
- [x] iOS (OpenGL)
    - not supported
- [x] iOS (Metal)
    - tested with [SDL branch](https://github.com/ppy/osu-framework/compare/master..frenzibyte:osu-framework:veldrid-ios-rebased)
    - requires https://github.com/mellinoe/veldrid/pull/482
- [x] Android (OpenGL)
    - requires SDL migration
- [x] Android (Vulkan)
    - requires SDL migration
- [x] llvmpipe (OpenGL)

Keep in mind that the renderer is not default yet so testing is optional as we work towards that.

### CODE REVIEW

**Comment by integerrr** [comment]
### M1 macos
#### `--renderer veldrid --surface metal` and `--surface opengl`
```
[runtime] 2023-02-27 19:49:05 [error]: An unhandled error has occurred.
[runtime] 2023-02-27 19:49:05 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
[runtime] 2023-02-27 19:49:05 [error]: at Veldrid.OpenGL.OpenGLGraphicsDevice.Init(GraphicsDeviceOptions options, OpenGLPlatformInfo platformInfo, UInt32 width, UInt32 height, Boolean loadFunctions)
[runtime] 2023-02-27 19:49:05 [error]: at Veldrid.OpenGL.OpenGLGraphicsDevice..ctor(GraphicsDeviceOptions options, OpenGLPlatformInfo platformInfo, UInt32 width, UInt32 height)
[runtime] 2023-02-27 19:49:05 [error]: at Veldrid.GraphicsDevice.CreateOpenGL(GraphicsDeviceOptions options, OpenGLPlatformInfo platformInfo, UInt32 width, UInt32 height)
[runtime] 2023-02-27 19:49:05 [error]: at osu.Framework.Graphics.Veldrid.VeldridRenderer.Initialise(IGraphicsSurface graphicsSurface) in /Users/integer/code/osu-framework/osu.Framework/Graphics/Veldrid/VeldridRenderer.cs:line 126
[runtime] 2023-02-27 19:49:05 [error]: at osu.Framework.Graphics.Rendering.Renderer.osu.Framework.Graphics.Rendering.IRenderer.Initialise(IGraphicsSurface graphicsSurface) in /Users/integer/code/osu-framework/osu.Framework/Graphics/Rendering/Renderer.cs:line 172
[runtime] 2023-02-27 19:49:05 [error]: at osu.Framework.Platform.GameHost.Run(Game game) in /Users/integer/code/osu-framework/osu.Framework/Platform/GameHost.cs:line 744
[runtime] 2023-02-27 19:49:05 [error]: at osu.Desktop.Program.Main(String[] args) in /Users/integer/code/osu/osu.Desktop/Program.cs:line 131
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Veldrid.OpenGL.OpenGLGraphicsDevice.Init(GraphicsDeviceOptions options, OpenGLPlatformInfo platformInfo, UInt32 width, UInt32 height, Boolean loadFunctions)
   at Veldrid.OpenGL.OpenGLGraphicsDevice..ctor(GraphicsDeviceOptions options, OpenGLPlatformInfo platformInfo, UInt32 width, UInt32 height)
   at Veldrid.GraphicsDevice.CreateOpenGL(GraphicsDeviceOptions options, OpenGLPlatformInfo platformInfo, UInt32 width, UInt32 height)
   at osu.Framework.Graphics.Veldrid.VeldridRenderer.Initialise(IGraphicsSurface graphicsSurface) in /Users/integer/code/osu-framework/osu.Framework/Graphics/Veldrid/VeldridRenderer.cs:line 126
   at osu.Framework.Graphics.Rendering.Renderer.osu.Framework.Graphics.Rendering.IRenderer.Initialise(IGraphicsSurface graphicsSurface) in /Users/integer/code/osu-framework/osu.Framework/Graphics/Rendering/Renderer.cs:line 172
   at osu.Framework.Platform.GameHost.Run(Game game) in /Users/integer/code/osu-framework/osu.Framework/Platform/GameHost.cs:line 744
   at osu.Desktop.Program.Main(String[] args) in /Users/integer/code/osu/osu.Desktop/Program.cs:line 131
```
#### `--renderer glrenderer --surface opengl`
(and `--renderer glrenderer --surface metal` but i believe the --surface arg here does nothing?)
- video broken - same as in #5655

**Comment by frenzibyte** [comment]
Testing `GLRenderer` is out-of-scope here, as noted in OP right above the tasks list.

**Comment by Natelytle** [comment]
On a gtx 1060 3gb with linux:
OpenGL: Runs fine, intro bugged.
Vulkan: Looks fine visually and high FPS doesn't break it, but the graphics freeze when trying to do nearly anything, while input and audio remain normal. As well, my PC freezes for a short while closing the game.

**Comment by peppy** [comment]
@Natelytle thanks for the testing, but you haven't provided much we can work with.

Vulkan: unless you can provide logs or any kind of useful system log output, we can't say more than "this is likely a problem with your system or drivers"
Intro being bugged: provide video, screenshots, phone camera footage, description. anything a developer can work with. "intro bugged" is as good as saying nothing at all.

**Comment by Natelytle** [comment]
I will provide proper logs tomorrow then, sorry about that

**Comment by smoogipoo** [comment]
That's probably referring to what I wrote in the PR description that served as a reminder for me to look into it. Basically the intro looks like this:

image

And doesn't show when exiting the game. I'm already investigating it.

**Comment by Loreos7** [comment]
Id like to give a feedback on this. I couldnt spot the difference with all of combinations (maybe I did something wrong) but all I got is the fps reduce. Here are some videos for comparison:

Current master:

https://user-images.githubusercontent.com/86934170/222306219-8f15bac5-58e5-4c3d-a317-43563d5c6799.mp4

https://user-images.githubusercontent.com/86934170/222306453-9be6a24a-484e-44e7-9abf-14fdb82bcc1f.mp4

Proposed branch (without any launch parameters)(any of combinations is kinda the same):


https://user-images.githubusercontent.com/86934170/222306543-963aca38-cd6c-476d-90bc-6993117bc111.mp4

https://user-images.githubusercontent.com/86934170/222306721-8af0c21f-b36f-449d-8247-6c14c913b501.mp4

**Comment by peppy** [comment]
Metal will not work on windows.

Performance is expected to be lower when using veldrid, we are aware of this.

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
I've done a pass over this (mostly focused on changes to the existing code, not new veldrid classes). I think it's fine as an initial push, and we can work forward from here.

**Comment by smoogipoo** [comment]
Probably the most concerning thing is/should be the blur shader, which I’m not entirely sure how to explain and/or make validation for at the moment other than “ensure either all your VS outputs are aligned to vec4s or you have no unused VS outputs in the FS”.

And I’m not even sure if the first of those even works, the second definitely does.

**Review by frenzibyte — APPROVED** [review]

**Comment by piee-kun** [comment]
might be an issue on my end but when using ``--renderer veldrid --surface vulkan`` on arch, osu fails to find libdl despite having latest glibc and libdl being in both  ``/usr/lib`` and ``/usr/lib32`` 
image

**Pull request merged**
