### PR TITLE
Make Resharper inspections fail the CI job

### PR DESCRIPTION
**Pull request by smoogipoo**
Fixes https://github.com/ppy/osu-framework/issues/4502

For the time being, I've published my own nuget package (smoogipoo.nvika) which has a GitHub build server built in. I've PR'd the change (https://github.com/laedit/vika/pull/290) and intend to use the official package once that's merged in. And if it isn't merged, I'll adopt it into the ppy org.

It can be seen working here: https://github.com/smoogipoo/osu-framework/pull/28/checks
- CI job fails
- Annotations in the `Files changed` view.

### CODE REVIEW

**Comment by smoogipoo** [comment]
I'm going to be force-pushing this one twice just for display purposes (draft PR). Ignore.

**Comment by bdach** [comment]
So I was doing some recon on doing the same thing as this PR does, and I found [this community answer](https://github.community/t/maximum-number-of-annotations-that-can-be-created-using-github-actions-logging-commands/16991/2) that outlines yet another baffling actions limitation, which is why I haven't PR'd something this yet:

> Currently, GitHub Actions does not support so much annotations in a workflow run, the below is a summary of the limitation:
>
> * 10 warning annotations and 10 error annotations per step
> * 50 annotations per job (sum of annotations from all the steps)
> * 50 annotations per run (separate from the job annotations, these annotations aren’t created by users

We may get 50 instead of 10 if the nvika fork is adjusted to use API instead of those workflow commands (and it'll probably need to be in the other workflow to get tokens, same as the test report thing). But the best interim solution may be to upload the inspectcode XML report as a build artifact...

**Comment by smoogipoo** [comment]
Oh god why...

**Comment by bdach** [comment]
I guess if we go down the API/separate workflow run route then we can do the same thing that the test plugin does and have a full summary in the check description even if we run out of the annotation limit (see [here](https://github.com/ppy/osu-framework/runs/2829477019) for example)...

**Comment by bdach** [comment]
Also going to note that github have their own strongly-typed http client for their API at https://github.com/octokit/octokit.net. May be easier to use than raw requests if you decide on revisiting that path.

**Comment by smoogipoo** [comment]
I think this can be merged as is in any case - at least it will fail CI even if it doesn't give the full scope of issues. Code inspection can always be run locally via `build.sh` or `InspectCode.sh` (after https://github.com/ppy/osu-framework/pull/4517).

**Review by peppy — APPROVED** [review]

**Pull request merged**
