### PR TITLE
Change CornerExponent to default to 2

### PR DESCRIPTION
**Pull request by smoogipoo**
Prevents regressions. See: https://github.com/ppy/osu-framework/pull/3020, https://github.com/ppy/osu-framework/issues/3047

### CODE REVIEW

**Comment by Tom94** [comment]
I _really_ wouldn't call the bounds thing a regression for `CornerExponent = 2.5`. The inaccuracy is pretty much imperceptible.

**Comment by smoogipoo** [comment]
If it's not mathematically accurate, I don't believe in it being the default.

**Comment by Tom94** [comment]
I disagree with that statement on so many levels.

Our bezier approximations of sliders are inaccurate in the same bounded way as these corner exponents of 2.5 are. The point is for corners to look accurate and for the worst-case behavior to be bounded to be imperceptible.

**Comment by Tom94** [comment]
I'm much in favor of a solution similar to @swoolcock 's PR: https://github.com/ppy/osu-framework/pull/3020

Only that instead of a hard-decision to use 2.0 for circles and 2.5 for everthing else, I'd make it a smooth transition.

**Comment by smoogipoo** [comment]
It is actually _very_ on retina. Put it this way, I didn't just make these changes after carefully examining the pixels, I noticed it while going through test cases.

Here's how it looks on retina:

image

I assume it looks _even worse_ at higher resolutions.

**Comment by Tom94** [comment]
You only run into that situation for near-circular things, where I agree a CornerExponent of 2 is more appropriate. See my reference of Samah's PR above.

**Comment by smoogipoo** [comment]
Want to explain to me what "near-circular" means to you?

image

image

**Comment by smoogipoo** [comment]
Also

> Our bezier approximations of sliders are inaccurate in the same bounded way

As far as I'm aware, they are not. Maybe the actual tracing of the path around the bezier curve is not accurate, but the bounding box _is_. Also, sliders are not a UI component so far as boxes.

**Comment by Tom94** [comment]
Without zooming in, I don't actually see the gaps on my retina screen. I honestly couldn't tell the difference between the perfectly-touching 2.0 exponent and the 2.5 exponent in this case.

Regarding the Bezier: pretty sure the bounding box is based on the path and not on the actual bezier equation. If we used the bezier equation directly, we'd run into numerical problems due to all the exponentials with paths longer than 10-20 vertices.

My point is that we use approximations everywhere. The goal should be visual accuracy, not numerical accuracy. Whether that invalidates your concerns here, I do not claim, but I object the hard requirement of mathematical correctness. (And I am saying this as the guy who loves to make things mathematically accurate.)

**Comment by Tom94** [comment]
... and the whole discussion completely disregards the question of whether the desire for pretty continuous corners happens more often in the wild than the desire for 100% accurate bounds of rotated containers with rounded corners. Do we have any such use case in osu!? I can't think of one of the top of my hat.

Imho, when there is a tradeoff, the default should cater to the more frequent use case.

**Comment by peppy** [comment]
Ignoring mathematics or anything, let's consider a user approaching the framework:

They want to make a rounded corner button and discover `CornerExponent`. As they set it higher, it starts to look awesome and they choose to leave it at `14` because of this.

Then later in development they start to get reports that users can click outside the button, due to the (easily visible) inaccuracies at the higher exponent.

I don't think this is a great thing to expose if we can't guarantee at least <1px input accuracy. At 2.5 it seems to be roughly within expectation (around 1-1.5 retina pixels of inaccuracy) so I am indifferent there, but going higher seems to be an issue.

**Comment by Tom94** [comment]
Users won't be able to click into the button. Hover is 100% accurate. Only the autosize bounds aren't.

**Comment by peppy** [comment]
In that case, adding a remark in xmldoc mentioning the inaccuracy is likely enough.

**Comment by peppy** [comment]
I'm going to make a call here and revert this one as a first step forward (to avoid the current status-quo which is causing weird behaviour in framework consumers that aren't using `CircularContainer`). I'd rather have things in a "working as before" state while we hone the behaviour into something we can all agree on.

A next step would be making (or updating @swoolcock's [PR](https://github.com/ppy/osu-framework/pull/3020)) to add the mentioned changes to make it ease from 2.5 to 2 rather than make a sudden jump.

**Pull request merged**
