### PR TITLE
Use EF for SQLite interfacing

### PR DESCRIPTION
**Pull request by UselessToucan**
Use EF Core for database interaction.
This change is required for [this](https://github.com/ppy/osu/pull/1350) game PR

### CODE REVIEW

**Comment by peppy** [comment]
As we are working with two projects here, how about we don't remove the SQLite stuff yet, so we can get this merged? I propose we split the removal into a future PR so we can get this merged ASAP rather than it being time critical on the `osu.Game` side merge (to make it build correctly).

**Comment by UselessToucan** [comment]
Do you suggest to keep both `GetDatabase` and `GetDatabaseConnectionString` in the `Storage` class for now?

**Comment by peppy** [comment]
Yeah, I'd say so. Keeps compatibility with both engines.

**Comment by peppy** [comment]
Closing in favour of #1085.

**Pull request closed without merging**
