### PR TITLE
Fix Color4 interpolation crashing on iOS

### PR DESCRIPTION
**Pull request by swoolcock**
Xamarin.iOS cannot AoT the calls to `Interpolation<Color4>.ValueAt` when created via reflection.
This PR calls it manually with explicit casts if JIT is not supported on the platform.

Spinners and drum rolls in osu! use `FadeAccent`, which is the only transform we currently use on a `Color4`.

---

Workaround for Color4 interpolation on Xamarin.iOS.  Fixes spinners/drum rolls crashing on osu! iOS.

### CODE REVIEW

**Comment by peppy** [comment]
Did you happen to figure out the reason for this? Is it something we should report as a bug? I'd rather have this as a temporary work around while waiting for a proper solution if possible..

**Comment by swoolcock** [comment]
I'm really not sure what's so bad about `Color4` that it can't handle it.  The crash occurs when it tries to execute the reflected delegate created from `CreateDelegate` in `Interpolation<TValue>`, and it's something deep in native code.

If we have a similar issue with something else in the future it may point us in the right direction.

**Comment by smoogipoo** [comment]
Would be good to isolate it and report it to them.

**Comment by swoolcock** [comment]
Yeah I'll try to get it down to a minimal reproducible case.

**Comment by peppy** [comment]
We'd rather not merge this until an isolated reproduction is filed as a bug (can then reference it in the comment).

**Comment by swoolcock** [comment]
Confirmed Xamarin master fixes the crash. Tested with CI build 12.7.0.74

https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/master/645eef16f753311eb348bd0ab840566f61d93c10/352/package/xamarin.ios-12.7.0.74.pkg

**Pull request closed without merging**
