### PR TITLE
Add basic shapes

### LINKED ISSUE #831: Add Circle Helper Class
Add a wrapper for the CircularCountainer with Masking = true and an option if it should be filled or not.

### PR DESCRIPTION
**Pull request by paparony03**
Fixes #831

### CODE REVIEW

**Comment by peppy** [comment]
It should be called `FilledCircle` or just `Circle` with FIllColour defaulting to transparentblack.

**Comment by smoogipooo** [comment]
I don't think FillColour/FillColourInfo is needed - Ccan just use the `FillCircularContainer`'s Colour/ColourInfo properties for that. If colour blending is needed, I'd rather the user wraps `FillCircularContainer` inside another container to do so.

**Comment by paparony03** [comment]
If it changes to FillCircle, should it be in osu.Framework.Graphics.Sprites?
Not very sure because it's probably going to be used like a sprite but it's also a Container.

**Comment by peppy** [comment]
I'd honestly make a new namespace called `Shapes` and move `Box` and `Circle` to it

**Comment by paparony03** [comment]
Should Triangle and EquilateralTriangle be moved to `Shapes` namespace together with this PR?

**Comment by peppy** [comment]
if they draw stuff sure

**Comment by peppy** [comment]
Please write PR titles better

"Move basic drawable shapes to their own namespace"

**Pull request merged**
