### PR TITLE
Dictionary.GetOrCreate extension method

### PR DESCRIPTION
**Pull request by AtomCrafty**
Needed this for something in the main repository and thought it may be useful to other framework users as well. Allows you to pass a method to generate a fallback value in case the lookup key was not present in the dictionary before. The generated value will be added to the dictionary.

### CODE REVIEW

**Comment by peppy** [comment]
One thing to note is that this should not be used in any high performance scenarios due to delegate allocations.

Not sure I see the need for this, especially as an extension method (it’s almost impossible for a consumer to find that this exists). Am neutral on it being merged.

**Comment by AtomCrafty** [comment]
If you don't think it is necessary, feel free to close the PR. I'm using a variant of this method in many of my projects, but I agree that most users probably wouldn't be aware of its existence.

**Comment by miterosan** [comment]
Please rename the method to ensuredirectory, because that name is acommenly used one for the functionality

**Comment by AtomCrafty** [comment]
Closing as unneeded

**Pull request closed without merging**
