### PR TITLE
Corrected minor typo in documentation

### PR DESCRIPTION
**Pull request by Elabar**
As the title said

image

### CODE REVIEW

**Comment by peppy** [comment]
Please create a branch with a name that isn't `master` for future PR contributions.

**Comment by Elabar** [comment]
Is it necessary?
I'm relatively new to this platform and not sure how to do it

**Comment by peppy** [comment]
If you're looking to get into software development, git is the first thing you should be learning. So yes, I'd say it is necessary. There are plenty of tutorials online.

**Comment by Elabar** [comment]
Something like this?
https://github.com/Elabar/osu-framework/tree/documentation-improvement
image

**Comment by smoogipoo** [comment]
Yes

**Comment by Elabar** [comment]
Ok, 
thanks for all the helps.

**Pull request merged**
