### PR TITLE
Add CurrentTimeMicro to AudioTrack

### PR DESCRIPTION
**Pull request by nashiora**
Add CurrentTimeMicro to AudioTrack, I needed it so why not.

Please ignore the two extra commits, was again having trouble with git and branches and yeah I don't do this often.

### CODE REVIEW

**Comment by peppy** [comment]
What is the use case for this? I'd consider writing an extension method in your local codebase as it doesn't seem like something which should be necessary at this level.

**Comment by SirCmpwn** [comment]
It's also misleading because this value isn't in microseconds.

**Comment by nashiora** [comment]
Shows how good I am with git outside of personal commits, I changed the * to / locally and didn't actually commit it after all my fuss.

I'll consider using an extension method, tho I may just keep my local changes because I prefer the simpler property syntax.

**Comment by SirCmpwn** [comment]
No, you're just pretending it is. You're adding resolution that doesn't exist, the trailing digits will always be 0. The sigfigs remain the same.

**Pull request closed without merging**
