### PR TITLE
Poll joystick events at each input thread iteration

### PR DESCRIPTION
**Pull request by abbradar**
Fixes https://github.com/ppy/osu-framework/issues/2752

### CODE REVIEW

**Comment by peppy** [comment]
This looks more correct, but we need to double-check allocations by doing this (I seem to recall it was scheduled to run less-often due to high allocations).

**Comment by abbradar** [comment]
Sure, any advice how to measure? I have some ideas for more optimized implementation but want to have numbers first. 

On August 12, 2019 5:46:13 PM GMT+03:00, Dean Herbert <notifications@github.com> wrote:
>This looks more correct, but we need to double-check allocations by
>doing this (I seem to recall it was scheduled to run less-often due to
>high allocations).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ppy/osu-framework/pull/2753#issuecomment-520455657

-- 
Nikolay.

**Comment by jai-x** [comment]
@abbradar BenchmarkDotNet is a good tool for this: https://benchmarkdotnet.org/

**Comment by abbradar** [comment]
@jai-x From a quick look it'll be fairly difficult to factor out `OsuTKJoystickHandler` into a separate benchmark suitable for BenchmarkDotNet; I hoped that there is an existing benchmark infrastructure so that I can add a test but I didn't find anything related in osu-framework; maybe I missed something?

I also tried using [GC.GetAllocatedBytesForCurrentThread](https://docs.microsoft.com/en-us/dotnet/api/system.gc.getallocatedbytesforcurrentthread?view=netframework-4.8) but alas it returns nonsensical value of zero new allocations for `refreshDevices`. My (hacked together) code for reference:

```
                    long times = 0;
                    long total = 0;
                    host.InputThread.Scheduler.Add(scheduled = new ScheduledDelegate(delegate
                    {
                        long before = GC.GetAllocatedBytesForCurrentThread();
                        refreshDevices();
                        long after = GC.GetAllocatedBytesForCurrentThread();
                        total += after - before;
                        times += 1;
                        if (times % 1000 == 0) {
                            Console.WriteLine($"Allocated bytes for refreshing devices: {total / times}, total for {times}: {total}, last {after}");
                            times = 0;
                            total = 0;
                        }

                        foreach (var device in devices)
                        {
                            if ((device.LastRawState.HasValue && device.RawState.Equals(device.LastRawState.Value))
                                || !device.RawState.IsConnected)
                                continue;

                            handleState(device, new OsuTKJoystickState(device));
                            FrameStatistics.Increment(StatisticsCounterType.JoystickEvents);
                        }
                    }, 0, 0));
```

**Comment by peppy** [comment]
I'll take a look at this tomorrow. I already know what to look for (easy to see via visual studio memory profiling or dotMemory).

**Comment by abbradar** [comment]
Thanks!

My current improvement idea is to avoid clearing and re-populating `rawStates` each frame and instead to check if devices count didn't change and if it didn't just update individual states via `GetState(index)`. OpenTK's existing API doesn't allow to do this effectively however - there's no way to get current number of devices, and there's no way to re-use old `JoystickState`. So let's measure before getting into a massive osuTK patch ;)

**Comment by peppy** [comment]
Sorry for the delayed response. I can't see any noticeable regressions in memory usage from this. Let's go with it for now.

**Pull request merged**
