### PR TITLE
Fix rearrangeable lists don't react on collection `Move` events

### PR DESCRIPTION
**Pull request by Feodor0090**
See added test.

### CODE REVIEW

**Comment by bdach** [comment]
Just for general information, can you provide context where you encountered this / what this is for?

**Comment by Feodor0090** [comment]
> Just for general information, can you provide context where you encountered this / what this is for?

I have two screens with lists bound to single `BindableList`, i noticed that after i drag an item in one screen, list in the other screen doesn't update. Test shows this case.

**Comment by bdach** [comment]
So this is in some external project / un-PR'd code? It's not related to any issue in the game?

**Comment by Feodor0090** [comment]
> So this is in some external project / un-PR'd code? It's not related to any issue in the game?
No, it is not.

**Comment by Feodor0090** [comment]
I had feeling that i saw cross-bound rearrangeable usages somewhere in osu!, well, i managed to find one.

https://github.com/ppy/osu-framework/assets/53872073/98bee4d2-f52d-458e-9e01-823a0b6082af

Exactly my use case: two screens, two bound lists. Notice that when i move "easy" diff down, it's still on top when i return to playlist setup screen.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
