### PR TITLE
Make RelativePositionAxes virtual.

### PR DESCRIPTION
**Pull request by smoogipooo**

### CODE REVIEW

**Comment by Tom94** [comment]
Nooooo! (I really don't like making Drawable things virtual if it can be somehow avoided. Do you think there is another way?)

**Comment by smoogipooo** [comment]
So when you have a container that expects children to be relatively positioned to work correctly (e.g. in the case of relativechildsize) how would you handle this?
xmldoccing "don't change the relative position axes of this container" while setting the default and hoping the user doesn't just set it themselves? Overloading these properties with `new` and hoping that the user only ever refers to a member of X type by X and not (Drawable)X? Should we just not care what the user does?

**Comment by smoogipooo** [comment]
Maybe relativechildsize/relativechildoffet should enforce children to be relatively positioned? But that brings up questions of inconsistency with size doing the same (e.g. normal notes are absolutely sized but hold notes are relatively sized).

**Comment by Tom94** [comment]
I think just writing in the doc is fine in this case.

**Comment by smoogipooo** [comment]
Hum, ok.

**Pull request closed without merging**
