### PR TITLE
Rewrite dependency injection to support injection/caching via class attributes

### LINKED ISSUE #1724: Register dependencies via field/property/class attributes
Rather than overriding `CreateChildDependencies`, should be able to attach dependencies to various members and have them automatically cache, e.g.:

```
[DependencyCache] // Objects can cache themselves for children
class MyObject : Drawable
    [DependencyCache] // Equivalent to Cache()
    public float MyFloat;

    [DependencyCache(typeof(MyDerivedType))] // Equivalent to CacheAs<T>()
    public object MyObject;
```

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/60967465-register-dependencies-via-field-property-class-attributes?utm_campaign=plugin&utm_content=tracker%2F44024461&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F44024461&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by smoogipoo**
Resolves #1724

PRing as an RFC for now.

* Preserves previous functionality for `load()`.
* Adds `ResolvedAttribute`. Available on properties.
  * Values from the `DependencyContainer` are injected into this.
* Adds `CachedAttribute`. Available on classes and fields. Multiple definitions allowed.
  * These values are cached to the `DependencyContainer` for children.

The flow order is:

1. Caching for children via `CachedAttribute` (via `Drawable.CreateChildDependencies()`).
2. Injection via `ResolvedAttribute`.
3. Injection via `BackgroundDependencyLoaderAttribute`.

Examples provided in test cases.

---

### CODE REVIEW

**Comment by smoogipoo** [comment]
Some caveats:

1. Requires using properties with a `set;`. Otherwise you get both compiler and resharper warnings about unused fields. The resharper warnings can be stopped, but I've not found a way to fix compiler warnings other than per-project/global.
2. Fields/properties have to be marked as private. I thought this was a sane value.

**Comment by peppy** [comment]
Not a huge fan of `Dependency` and `DependencyCached`. Are you against making it`DependencyResolved` and `Cached` (or even `DependencyCached`)? When reading code it's hard to quickly understand whether `Dependency` means it's being exposed or consumed.

**Comment by smoogipoo** [comment]
I agree, just couldn't think of any other names.

**Comment by smoogipoo** [comment]
Although I'd add that `Cached` is a bad idea due to conflicts with the `Cached` type.

**Comment by peppy** [comment]
```[runtime:important] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invoc
ation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. -
--> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Syst
em.ArgumentException: IBindable<RulesetInfo> must be a class to be cached as a dependency.
Parameter name: type
```

Attempting to cache interfaces seems to fail currently.

**Pull request merged**
