### PR TITLE
Use polling in conjunction with window events to support raw input

### PR DESCRIPTION
**Pull request by peppy**
Tested on windows to work correctly, including bypassing acceleration and cursor exiting window correctly.

### CODE REVIEW

**Comment by Tom94** [comment]
Can this be a separate input handler? E.g. `RawOpenTKMouseHandler`? Many people have drifting issues with raw input (can mostly be found in CS:GO forums) and would prefer windows handling (myself included). Nothing against always polling, though.

**Comment by peppy** [comment]
Yep, as mentioned in discord, this breaks input completely on my VM. Just a testing branch, which I'll iterate towards a final implementation.

**Comment by peppy** [comment]
Also see the referenced PR where I try to use the event-driven OpenTK stuff. Turns out it doesn't correctly return raw data, so I'm sticking with polling `GetState` for now.

**Comment by Tom94** [comment]
If both return the same data, what's the advantage of sticking with polling?

**Comment by peppy** [comment]
Point is they don't.

**Comment by Tom94** [comment]
So how do they differ? You said OpenTK events don't return raw data, so I assumed it'd return the same data as the previous polling-based solution. I'm talking about using your referenced PR instead of the old polling-based approach for _windows_ input.

**Comment by peppy** [comment]
maybe. although it doesn't fire events when the mouse cursor is outside the window so we will need to handle that accordingly

**Comment by peppy** [comment]
See https://github.com/ppy/osu-framework/pull/778

**Pull request closed without merging**
