### PR TITLE
Refactor TextBox to simplify Caret and Selection logic

### PR DESCRIPTION
**Pull request by Aergwyn**
I'm not sure if this is the direction that was envisioned but it does
- split out some caret logic
- split out some selection logic
- make TextBox aware of the Y axis
- make TextSize customizable

This is also a preparation for MultiLineTextBox.

### CODE REVIEW

**Comment by peppy** [comment]
New logic is visually different/flawed:

screencast 2018-07-09 15-49-53

**Comment by Aergwyn** [comment]
I'm a bit busy atm but I'll try to look over it on the coming weekend. I'm still not completely sure about the selection (independent from the visual regression I introduced). I need to wrap my head around all of this again.

**Comment by Aergwyn** [comment]
Can I have this marked as WIP? I don't think i can get this fixed up in July as well.
I'm not sure if I like the current `SelectionArea` and also I don't know how to go about the visual regression... yet. Before it was just the caret that was expanded and that logic is now split between `DrawableCaret` and `SelectionArea` so if it stays like this I need to figure out how to sync that up.

**Comment by peppy** [comment]
Yeah, not sure how to approach this. It may be best to just close for the time being and reopen when you have a chance to look into it. It's not high priority and I don't think anynone else will be looking into it.

**Comment by Aergwyn** [comment]
Okay, will do that.

**Comment by peppy** [comment]
Probably don't want to delete the branch for now, may be good for reference.

**Pull request closed without merging**
