### PR TITLE
Introduce ICommand interface with basic implementation

### PR DESCRIPTION
**Pull request by UselessToucan**
Basic implementation of Command design pattern. I will probably extend or rework it in the future.

Command is a behavioral design pattern that turns a request into a stand-alone object that contains all information about the request.

Command design pattern is used in the following scenarios:
1. Imagine we have a text editor like Notepad. It has a search feature. There are two ways to call it: click the menu item or press Ctrl+F. I.e. the same call is performed in a multiple places. In order not to duplicate it, we can encapsulate it in a Command object.
2. Command pattern allows us to undo/redo operations. It can be done by performing contrary operation, or using memento design pattern.

### CODE REVIEW

**Comment by peppy** [comment]
This breaks backwards compatibility, so we better be 100% sure we want this.

In repsonse to point 1, we can already do this by re-using an `Action`.
In response to point 2, the scenarios you'd used it would never require this behaviour. We have already discussed something similar to this for the editor, for instance, but having it used for things like drawable buttons doesn't make a lot of sense if this is the motivation.

**Comment by smoogipoo** [comment]
Yeah I'm not really sure what we gain from this, all the logic has to pass to the ICommand before being passed back to the object / a continuation. In what scenario would you see this encapsulation actually being useful? What sort of logic would you expect in a complex `ICommand`?

**Comment by UselessToucan** [comment]
More complex usage scenario.
https://github.com/ppy/osu/pull/4826/commits/898a6e437abebb3d3cdd69e1da0428fdf84a5064

Social overlay. I shouldn't be able to open it when I am unauthenticated(since it won't work anyway). I.e. we should be able to disable the 'call' for all triggers(hotkey, ui button). Command allows us to do it in one place using its `Execute` and `CanExecute` members. Re-using an Action does not allow to do the same because `Action` does not have `CanExecute` feature.

**Comment by smoogipoo** [comment]
There are a few problems that I see with that:

1. What if someone calls `socialOverlay.ToggleOverlay()` manually, without a command?
2. If the overlay should be hidden when logged out, the logic will reside in either `OsuGame` or `SocialOverlay`, thus you now have a splitting of the logic where the overlay is shown/hidden, and the conditions therein.
3. What if the overlay _should_ display, but when logged out it will display data from a guest API?
4. This makes me anxious that commands are prone to memory leaks since they're intended to be stored at higher levels and re-used, holding references to the target values (your overlays in the example provided.

From a stylistic p.o.v, it's also not nice to pass in every single component that the command needs to do its thing.

The overlay itself should be handling whether to show or hide and how to.

**Comment by UselessToucan** [comment]
> What if someone calls socialOverlay.ToggleOverlay() manually, without a command?

Don't know. But, as far as I understand, current code is not protected against this too.

> If the overlay should be hidden when logged out, the logic will reside in either OsuGame or SocialOverlay, thus you now have a splitting of the logic where the overlay is shown/hidden, and the conditions therein.

This logic can be placed in the ToggleOnlineOverlayCommand since it is already tracking your auth status. However, this won't be an obvious solution for the reader.

> What if the overlay should display, but when logged out it will display data from a guest API?

Then don't use command which requires being authenticated. `ToggleOverlayCommand` from the framework looks suitable for this case.

> This makes me anxious that commands are prone to memory leaks since they're intended to be stored at higher levels and re-used, holding references to the target values (your overlays in the example provided.

Yes. But aren't actions have the same problem? I mean, action may have long lifetime and it can capture objects in a closure.

> From a stylistic p.o.v, it's also not nice to pass in every single component that the command needs to do its thing.

Since Command is not `Drawable`, it can't use DI. :(

> The overlay itself should be handling whether to show or hide and how to.

Commands usage is not limited to overlays. I probably chose a bad example.

**Comment by smoogipoo** [comment]
> Don't know. But, as far as I understand, current code is not protected against this too.

The idea is that you can't protect against this through just commands. You can protect against it at the overlay level, however. Maybe it's not done yet and that's a bad thing, but it's certainly at least possible.

> This logic can be placed in the ToggleOnlineOverlayCommand since it is already tracking your auth status.

Then you have a user that creates a new command rather than using one via DI and you get this multiple-handling-of-hiding logic, and potentially more dangerous stuff.

How do you implement a `ShowUserProfileCommand` which handles this stuff? I see the following problems when doing so myself:

1. For the hide-when-offline logic to be contained within the command, the command must be a singleton at a `GameBase` level. Tracking API status otherwise will lead to a memory leak.
2. If it is a singleton, I don't see how the command could be used. It can't have publicly-settable fields as it's a singleton, it can't have a `ShowUser()` method because that's not going to be invoked by the action...
3. Let's put the hide-when-offline logic in the overlay itself. Then we have the command which handles half of the logic, and the overlay that handles the other half of the logic, and we get into the same issue I pointed in the first quote, where potentially the command's half of the logic is completely bypassed.

The point I want to get across here is that this logic is in the wrong place. It's doing too much. But if we have to handle this logic elsewhere (in the overlay, as per my proposal), then what logic is left for the command to do other than being a delegate?
I believe this is the general case for these commands.

Based on that, and based on discussions we've had internally, I'm concluding this is not the path forward. Thanks for the contribution though.

**Pull request closed without merging**
