### PR TITLE
Revert assembly load logic change to attempt to fix tests

### PR DESCRIPTION
**Pull request by peppy**

### CODE REVIEW

**Comment by huoyaoyuan** [comment]
The game side usages can get better fix by switching to `typeof(XXX).Assembly` to get rid of loading logic.
Despite of that, agree for reverting the exact-same behaviour.

**Comment by peppy** [comment]
Can you make a PR showing how that should be done? It's not immediately obvious to me how that would work in `RulesetStore`.

**Comment by huoyaoyuan** [comment]
Looks so weird. `RulesetStore` shouldn't have any path calling this. No idea.

May get resolved if `public virtual IResourceStore<byte[]> CreateResourceStore() => new NamespacedResourceStore<byte[]>(new DllResourceStore(GetType().Assembly.Location), @"Resources");` gets updated.

**Comment by peppy** [comment]
Without looking to deep, I'd argue it's something to do with the way assemblies are loaded via the different methods, causing them to be incorrectly reloaded.

I remember now that when writing the `DllResourceStore` code, I had to do it in a *very* specific way to make NUnit happy.

**Comment by huoyaoyuan** [comment]
At my sight, we should avoid loading assembly ourselves anywhere, unless extremely necessary. `typeof` guarantees a correct result when the type is available.

**Comment by peppy** [comment]
That sounds fair as a direction forward. DllResourceStore may be best replaced/renamed to `AssemblyResourceStore` and take a type/generic if it turns out to be the culprit.

**Pull request merged**
