### PR TITLE
Unify BOM in repository

### PR DESCRIPTION
**Pull request by huoyaoyuan**
BOM wins on amount among current files. (505 vs 277)

### CODE REVIEW

**Comment by peppy** [comment]
Could you include the command you used to unify the BOM in the PR description for future reference?

**Comment by peppy** [comment]
Also we may want to add support to `CodeFileSanity` to keep this in check if it's something we care about. Else there's no way of checking/ensuring new files are correctly committed.

**Comment by jai-x** [comment]
I'm not sure we would want to use UTF-8-BOM over plain UTF-8.

Taken from the [Unicode spec](http://www.unicode.org/versions/Unicode5.0.0/ch02.pdf):
> Use of a BOM is neither required nor recommended for UTF-8, but may be encountered in contexts where UTF-8 data is converted from other encoding forms that use  a  BOM  or  where  the  BOM  is  used  as  a  UTF-8  signature.

**Comment by huoyaoyuan** [comment]
> Could you include the command you used to unify the BOM in the PR description for future reference?

Just a quick run in interactive window. `dotnet format` guards for trailing new line, but not for BOM.
```csharp
UTF8Encoding utf8 = new UTF8Encoding(true);
foreach (var cs in Directory.EnumerateFiles(@"C:\Users\Meow\Source\Repos\osu-framework\", "*.cs", SearchOption.AllDirectories))
{
    var content = File.ReadAllText(cs);
    File.WriteAllText(cs, content, utf8);
}
```

> I'm not sure we would want to use UTF-8-BOM over plain UTF-8.

I just pick the majority. Let's discuss for the preference.

**Comment by jai-x** [comment]
Is there an update on this? I would still prefer using UTF-8 without BOM.

**Comment by huoyaoyuan** [comment]
Closing as no decision.

**Pull request closed without merging**
