### PR TITLE
Separate out colour and presence invalidations

### PR DESCRIPTION
**Pull request by smoogipoo**
- Creates a new invalidation value (`Invalidation.Presence`).
  - `Scale`, `Alpha`, and `AlwaysPresent` trigger this, if the IsPresent state changes.
  - Propagates upwards only.
- `Invalidation.Colour` propagates downwards only.
- Flow containers/other components that would handle colour invalidations for presence, now handle `Invalidation.Presence` instead.

Accepting suggestions for what to call `DrawColourInfo`...

I go up from 30 -> 55 FPS on the following stresstest:

```
public class TestCaseScratch : TestCase
{
    [BackgroundDependencyLoader]
    private void load()
    {
        var topContainer = new Container { Size = new Vector2(10) };
        var currentContainer = topContainer;

        for (int i = 0; i < 50; i++)
        {
            var newContainer = new Container { RelativeSizeAxes = Axes.Both };
            for (int j = 0; j < 200; j++)
                newContainer.Add(new Box { RelativeSizeAxes = Axes.Both });

            currentContainer.Add(newContainer);
            currentContainer = newContainer;
        }

        currentContainer.Add(new Box { RelativeSizeAxes = Axes.Both });

        Add(topContainer);

        Scheduler.AddDelayed(() => topContainer.Colour = Color4.White.Opacity(RNG.NextSingle()), 0, true);
    }
}
```

### CODE REVIEW

**Comment by peppy** [comment]
Needs conflict resolution

**Comment by smoogipoo** [comment]
@Tom94 This will make #223 apply once more since they're split out, so:

```csharp
Invalidate(Invalidation.All);
DoSomething(drawable.ScreenSpaceDrawQuad);
Invalidate(Invalidation.Colour); // Won't propagate because drawColourInfoBacking is already invalid
```

But I'm not sure this is a bad thing? There's one case that I can see would fail, but it's less due to invalidation logic and more so about where it's computed - the interpolation in the `!isSingleColour` case.

**Comment by Tom94** [comment]
The invalid state all-the-way-down was why I thought it would _not_ trigger #223. Are you sure it actually does? If so, can it be fixed by further separating things out?

**Comment by smoogipoo** [comment]
@Tom94 sorry I initially misinterpreted the scenario in the issue thread.

If you `Invalidate(Invalidation.Colour)`, then `Invalidate(Invalidation.DrawSize)`, an intermediate e.g. `FlowContainer` *will* receive the second invalidation, because they're split apart now.

So it won't trigger the issues in the mentioned issue as it is _expected_ that the colour invalidation won't propagate.

**Comment by smoogipoo** [comment]
Don't merge just yet, still figuring out how to fix the `!IsSingleColour` case.

**Comment by smoogipoo** [comment]
Should be ready to go.

**Pull request merged**
