### PR TITLE
Add some methods to get more granular control over shader compilation

### PR DESCRIPTION
**Pull request by peppy**

### CODE REVIEW

**Comment by Tom94** [comment]
Would it not be sufficient to simply enqueue shader compilations within each `Shader`'s contructor, and to then only run a single one per frame within `GlWrapper`? That should compile the shaders way before they're first used (at which point they should be force-compiled if they haven't been compiled yet.)

**Comment by peppy** [comment]
We can do that, sure.

**Comment by Tom94** [comment]
I'm just thinking that this would make the complicated osu-side logic unnecessary while at the same time providing a more general solution at a framework level.

**Comment by peppy** [comment]
It won't reduce complexity as I still want to preload shaders which aren't going to be used until far in the future.

**Comment by peppy** [comment]
the `prepareNext` function will no longer be required at the osu! side, so you could say it is a bit simpler.

**Comment by Tom94** [comment]
The way I thought it could work was to simply instantiate those shaders well in advance (e.g. in `OsuGame` or whatever loads stuff in the beginning) and pass them to the elements that need them via DI. That would be the only code needed on the osu! side.

**Comment by peppy** [comment]
I want it to happen specifically in the loading sequence, where frame drops are tolerated.

**Comment by peppy** [comment]
excess DI isn't required. shaders are shared at `ShaderManager`.

apart from that, my code is doing exactly what you say (with a wait until all are loaded before continuing).

**Comment by Tom94** [comment]
I see. Sounds like a good solution then. My main gripe was with having the queueing logic within the osu! repo.

**Comment by smoogipoo** [comment]
the queueing logic definitely needs to be moved to the framework.

**Pull request merged**
